.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching func_8003C2D4, 0x190

glabel func_8003C2D4
    /* 2CAD4 8003C2D4 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2CAD8 8003C2D8 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2CADC 8003C2DC 21988000 */  addu       $s3, $a0, $zero
    /* 2CAE0 8003C2E0 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2CAE4 8003C2E4 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2CAE8 8003C2E8 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2CAEC 8003C2EC 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2CAF0 8003C2F0 3800628E */  lw         $v0, 0x38($s3)
    /* 2CAF4 8003C2F4 00000000 */  nop
    /* 2CAF8 8003C2F8 53004010 */  beqz       $v0, .L8003C448
    /* 2CAFC 8003C2FC 801F113C */   lui       $s1, %hi(D_1F800000)
    /* 2CB00 8003C300 00003126 */  addiu      $s1, $s1, %lo(D_1F800000)
    /* 2CB04 8003C304 E545010C */  jal        func_80051794
    /* 2CB08 8003C308 21202002 */   addu      $a0, $s1, $zero
    /* 2CB0C 8003C30C 801F103C */  lui        $s0, %hi(D_1F800020)
    /* 2CB10 8003C310 20001026 */  addiu      $s0, $s0, %lo(D_1F800020)
    /* 2CB14 8003C314 E545010C */  jal        func_80051794
    /* 2CB18 8003C318 21200002 */   addu      $a0, $s0, $zero
    /* 2CB1C 8003C31C 5A006486 */  lh         $a0, 0x5A($s3)
    /* 2CB20 8003C320 1414020C */  jal        func_80085050
    /* 2CB24 8003C324 21280002 */   addu      $a1, $s0, $zero
    /* 2CB28 8003C328 21200002 */  addu       $a0, $s0, $zero
    /* 2CB2C 8003C32C 21282002 */  addu       $a1, $s1, $zero
    /* 2CB30 8003C330 801F103C */  lui        $s0, %hi(D_1F800040)
    /* 2CB34 8003C334 40001026 */  addiu      $s0, $s0, %lo(D_1F800040)
    /* 2CB38 8003C338 47007292 */  lbu        $s2, 0x47($s3)
    /* 2CB3C 8003C33C 21300002 */  addu       $a2, $s0, $zero
    /* 2CB40 8003C340 4410020C */  jal        func_80084110
    /* 2CB44 8003C344 01005232 */   andi      $s2, $s2, 0x1
    /* 2CB48 8003C348 801F023C */  lui        $v0, (0x1F8000C0 >> 16)
    /* 2CB4C 8003C34C 2E006396 */  lhu        $v1, 0x2E($s3)
    /* 2CB50 8003C350 801F073C */  lui        $a3, %hi(D_1F8000F8)
    /* 2CB54 8003C354 C00043A4 */  sh         $v1, (0x1F8000C0 & 0xFFFF)($v0)
    /* 2CB58 8003C358 32006396 */  lhu        $v1, 0x32($s3)
    /* 2CB5C 8003C35C C0004224 */  addiu      $v0, $v0, %lo(D_1F8000C0)
    /* 2CB60 8003C360 020043A4 */  sh         $v1, 0x2($v0)
    /* 2CB64 8003C364 36006396 */  lhu        $v1, 0x36($s3)
    /* 2CB68 8003C368 F800E724 */  addiu      $a3, $a3, %lo(D_1F8000F8)
    /* 2CB6C 8003C36C 040043A4 */  sh         $v1, 0x4($v0)
    /* 2CB70 8003C370 0000EC8C */  lw         $t4, 0x0($a3)
    /* 2CB74 8003C374 0400ED8C */  lw         $t5, 0x4($a3)
    /* 2CB78 8003C378 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2CB7C 8003C37C 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2CB80 8003C380 0800EC8C */  lw         $t4, 0x8($a3)
    /* 2CB84 8003C384 0C00ED8C */  lw         $t5, 0xC($a3)
    /* 2CB88 8003C388 1000EE8C */  lw         $t6, 0x10($a3)
    /* 2CB8C 8003C38C 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2CB90 8003C390 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2CB94 8003C394 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2CB98 8003C398 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2CB9C 8003C39C 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2CBA0 8003C3A0 00000000 */  nop
    /* 2CBA4 8003C3A4 00000000 */  nop
    /* 2CBA8 8003C3A8 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 2CBAC 8003C3AC 801F073C */  lui        $a3, %hi(D_1F800054)
    /* 2CBB0 8003C3B0 5400E724 */  addiu      $a3, $a3, %lo(D_1F800054)
    /* 2CBB4 8003C3B4 0000F9E8 */  swc2       $25, 0x0($a3)
    /* 2CBB8 8003C3B8 0400FAE8 */  swc2       $26, 0x4($a3) /* handwritten instruction */
    /* 2CBBC 8003C3BC 0800FBE8 */  swc2       $27, 0x8($a3) /* handwritten instruction */
    /* 2CBC0 8003C3C0 801F043C */  lui        $a0, %hi(D_1F8000D0)
    /* 2CBC4 8003C3C4 D0008424 */  addiu      $a0, $a0, %lo(D_1F8000D0)
    /* 2CBC8 8003C3C8 1400028E */  lw         $v0, 0x14($s0)
    /* 2CBCC 8003C3CC 3C00838C */  lw         $v1, 0x3C($a0)
    /* 2CBD0 8003C3D0 00000000 */  nop
    /* 2CBD4 8003C3D4 21104300 */  addu       $v0, $v0, $v1
    /* 2CBD8 8003C3D8 140002AE */  sw         $v0, 0x14($s0)
    /* 2CBDC 8003C3DC 1800028E */  lw         $v0, 0x18($s0)
    /* 2CBE0 8003C3E0 4000858C */  lw         $a1, 0x40($a0)
    /* 2CBE4 8003C3E4 1C00038E */  lw         $v1, 0x1C($s0)
    /* 2CBE8 8003C3E8 4400848C */  lw         $a0, 0x44($a0)
    /* 2CBEC 8003C3EC 21104500 */  addu       $v0, $v0, $a1
    /* 2CBF0 8003C3F0 21186400 */  addu       $v1, $v1, $a0
    /* 2CBF4 8003C3F4 180002AE */  sw         $v0, 0x18($s0)
    /* 2CBF8 8003C3F8 1C0003AE */  sw         $v1, 0x1C($s0)
    /* 2CBFC 8003C3FC 00000C8E */  lw         $t4, 0x0($s0)
    /* 2CC00 8003C400 04000D8E */  lw         $t5, 0x4($s0)
    /* 2CC04 8003C404 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2CC08 8003C408 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2CC0C 8003C40C 08000C8E */  lw         $t4, 0x8($s0)
    /* 2CC10 8003C410 0C000D8E */  lw         $t5, 0xC($s0)
    /* 2CC14 8003C414 10000E8E */  lw         $t6, 0x10($s0)
    /* 2CC18 8003C418 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2CC1C 8003C41C 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2CC20 8003C420 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2CC24 8003C424 14000C8E */  lw         $t4, 0x14($s0)
    /* 2CC28 8003C428 18000D8E */  lw         $t5, 0x18($s0)
    /* 2CC2C 8003C42C 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2CC30 8003C430 1C000E8E */  lw         $t6, 0x1C($s0)
    /* 2CC34 8003C434 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2CC38 8003C438 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2CC3C 8003C43C 21206002 */  addu       $a0, $s3, $zero
    /* 2CC40 8003C440 3DF2000C */  jal        func_8003C8F4
    /* 2CC44 8003C444 21284002 */   addu      $a1, $s2, $zero
  .L8003C448:
    /* 2CC48 8003C448 2000BF8F */  lw         $ra, 0x20($sp)
    /* 2CC4C 8003C44C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2CC50 8003C450 1800B28F */  lw         $s2, 0x18($sp)
    /* 2CC54 8003C454 1400B18F */  lw         $s1, 0x14($sp)
    /* 2CC58 8003C458 1000B08F */  lw         $s0, 0x10($sp)
    /* 2CC5C 8003C45C 0800E003 */  jr         $ra
    /* 2CC60 8003C460 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel func_8003C2D4

/* Handwritten function */
nonmatching func_8003C464, 0x194

glabel func_8003C464
    /* 2CC64 8003C464 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2CC68 8003C468 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2CC6C 8003C46C 21908000 */  addu       $s2, $a0, $zero
    /* 2CC70 8003C470 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 2CC74 8003C474 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2CC78 8003C478 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2CC7C 8003C47C 3800428E */  lw         $v0, 0x38($s2)
    /* 2CC80 8003C480 00000000 */  nop
    /* 2CC84 8003C484 56004010 */  beqz       $v0, .L8003C5E0
    /* 2CC88 8003C488 801F113C */   lui       $s1, %hi(D_1F800000)
    /* 2CC8C 8003C48C 00003126 */  addiu      $s1, $s1, %lo(D_1F800000)
    /* 2CC90 8003C490 7A004586 */  lh         $a1, 0x7A($s2)
    /* 2CC94 8003C494 7C004686 */  lh         $a2, 0x7C($s2)
    /* 2CC98 8003C498 7E004786 */  lh         $a3, 0x7E($s2)
    /* 2CC9C 8003C49C EF45010C */  jal        func_800517BC
    /* 2CCA0 8003C4A0 21202002 */   addu      $a0, $s1, $zero
    /* 2CCA4 8003C4A4 801F103C */  lui        $s0, %hi(D_1F800020)
    /* 2CCA8 8003C4A8 20001026 */  addiu      $s0, $s0, %lo(D_1F800020)
    /* 2CCAC 8003C4AC E545010C */  jal        func_80051794
    /* 2CCB0 8003C4B0 21200002 */   addu      $a0, $s0, $zero
    /* 2CCB4 8003C4B4 5A004486 */  lh         $a0, 0x5A($s2)
    /* 2CCB8 8003C4B8 1414020C */  jal        func_80085050
    /* 2CCBC 8003C4BC 21280002 */   addu      $a1, $s0, $zero
    /* 2CCC0 8003C4C0 21200002 */  addu       $a0, $s0, $zero
    /* 2CCC4 8003C4C4 21282002 */  addu       $a1, $s1, $zero
    /* 2CCC8 8003C4C8 801F103C */  lui        $s0, %hi(D_1F800040)
    /* 2CCCC 8003C4CC 40001026 */  addiu      $s0, $s0, %lo(D_1F800040)
    /* 2CCD0 8003C4D0 47005192 */  lbu        $s1, 0x47($s2)
    /* 2CCD4 8003C4D4 21300002 */  addu       $a2, $s0, $zero
    /* 2CCD8 8003C4D8 4410020C */  jal        func_80084110
    /* 2CCDC 8003C4DC 01003132 */   andi      $s1, $s1, 0x1
    /* 2CCE0 8003C4E0 801F023C */  lui        $v0, (0x1F8000C0 >> 16)
    /* 2CCE4 8003C4E4 2E004396 */  lhu        $v1, 0x2E($s2)
    /* 2CCE8 8003C4E8 801F083C */  lui        $t0, %hi(D_1F8000F8)
    /* 2CCEC 8003C4EC C00043A4 */  sh         $v1, (0x1F8000C0 & 0xFFFF)($v0)
    /* 2CCF0 8003C4F0 32004396 */  lhu        $v1, 0x32($s2)
    /* 2CCF4 8003C4F4 C0004224 */  addiu      $v0, $v0, %lo(D_1F8000C0)
    /* 2CCF8 8003C4F8 020043A4 */  sh         $v1, 0x2($v0)
    /* 2CCFC 8003C4FC 36004396 */  lhu        $v1, 0x36($s2)
    /* 2CD00 8003C500 F8000825 */  addiu      $t0, $t0, %lo(D_1F8000F8)
    /* 2CD04 8003C504 040043A4 */  sh         $v1, 0x4($v0)
    /* 2CD08 8003C508 00000C8D */  lw         $t4, 0x0($t0)
    /* 2CD0C 8003C50C 04000D8D */  lw         $t5, 0x4($t0)
    /* 2CD10 8003C510 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2CD14 8003C514 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2CD18 8003C518 08000C8D */  lw         $t4, 0x8($t0)
    /* 2CD1C 8003C51C 0C000D8D */  lw         $t5, 0xC($t0)
    /* 2CD20 8003C520 10000E8D */  lw         $t6, 0x10($t0)
    /* 2CD24 8003C524 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2CD28 8003C528 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2CD2C 8003C52C 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2CD30 8003C530 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2CD34 8003C534 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2CD38 8003C538 00000000 */  nop
    /* 2CD3C 8003C53C 00000000 */  nop
    /* 2CD40 8003C540 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 2CD44 8003C544 801F083C */  lui        $t0, %hi(D_1F800054)
    /* 2CD48 8003C548 54000825 */  addiu      $t0, $t0, %lo(D_1F800054)
    /* 2CD4C 8003C54C 000019E9 */  swc2       $25, 0x0($t0)
    /* 2CD50 8003C550 04001AE9 */  swc2       $26, 0x4($t0) /* handwritten instruction */
    /* 2CD54 8003C554 08001BE9 */  swc2       $27, 0x8($t0) /* handwritten instruction */
    /* 2CD58 8003C558 801F043C */  lui        $a0, %hi(D_1F8000D0)
    /* 2CD5C 8003C55C D0008424 */  addiu      $a0, $a0, %lo(D_1F8000D0)
    /* 2CD60 8003C560 1400028E */  lw         $v0, 0x14($s0)
    /* 2CD64 8003C564 3C00838C */  lw         $v1, 0x3C($a0)
    /* 2CD68 8003C568 00000000 */  nop
    /* 2CD6C 8003C56C 21104300 */  addu       $v0, $v0, $v1
    /* 2CD70 8003C570 140002AE */  sw         $v0, 0x14($s0)
    /* 2CD74 8003C574 1800028E */  lw         $v0, 0x18($s0)
    /* 2CD78 8003C578 4000858C */  lw         $a1, 0x40($a0)
    /* 2CD7C 8003C57C 1C00038E */  lw         $v1, 0x1C($s0)
    /* 2CD80 8003C580 4400848C */  lw         $a0, 0x44($a0)
    /* 2CD84 8003C584 21104500 */  addu       $v0, $v0, $a1
    /* 2CD88 8003C588 21186400 */  addu       $v1, $v1, $a0
    /* 2CD8C 8003C58C 180002AE */  sw         $v0, 0x18($s0)
    /* 2CD90 8003C590 1C0003AE */  sw         $v1, 0x1C($s0)
    /* 2CD94 8003C594 00000C8E */  lw         $t4, 0x0($s0)
    /* 2CD98 8003C598 04000D8E */  lw         $t5, 0x4($s0)
    /* 2CD9C 8003C59C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2CDA0 8003C5A0 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2CDA4 8003C5A4 08000C8E */  lw         $t4, 0x8($s0)
    /* 2CDA8 8003C5A8 0C000D8E */  lw         $t5, 0xC($s0)
    /* 2CDAC 8003C5AC 10000E8E */  lw         $t6, 0x10($s0)
    /* 2CDB0 8003C5B0 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2CDB4 8003C5B4 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2CDB8 8003C5B8 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2CDBC 8003C5BC 14000C8E */  lw         $t4, 0x14($s0)
    /* 2CDC0 8003C5C0 18000D8E */  lw         $t5, 0x18($s0)
    /* 2CDC4 8003C5C4 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2CDC8 8003C5C8 1C000E8E */  lw         $t6, 0x1C($s0)
    /* 2CDCC 8003C5CC 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2CDD0 8003C5D0 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2CDD4 8003C5D4 21204002 */  addu       $a0, $s2, $zero
    /* 2CDD8 8003C5D8 3DF2000C */  jal        func_8003C8F4
    /* 2CDDC 8003C5DC 21282002 */   addu      $a1, $s1, $zero
  .L8003C5E0:
    /* 2CDE0 8003C5E0 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 2CDE4 8003C5E4 1800B28F */  lw         $s2, 0x18($sp)
    /* 2CDE8 8003C5E8 1400B18F */  lw         $s1, 0x14($sp)
    /* 2CDEC 8003C5EC 1000B08F */  lw         $s0, 0x10($sp)
    /* 2CDF0 8003C5F0 0800E003 */  jr         $ra
    /* 2CDF4 8003C5F4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_8003C464

/* Handwritten function */
nonmatching func_8003C5F8, 0x190

glabel func_8003C5F8
    /* 2CDF8 8003C5F8 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2CDFC 8003C5FC 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2CE00 8003C600 21988000 */  addu       $s3, $a0, $zero
    /* 2CE04 8003C604 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2CE08 8003C608 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2CE0C 8003C60C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2CE10 8003C610 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2CE14 8003C614 3800628E */  lw         $v0, 0x38($s3)
    /* 2CE18 8003C618 00000000 */  nop
    /* 2CE1C 8003C61C 53004010 */  beqz       $v0, .L8003C76C
    /* 2CE20 8003C620 801F113C */   lui       $s1, %hi(D_1F800000)
    /* 2CE24 8003C624 00003126 */  addiu      $s1, $s1, %lo(D_1F800000)
    /* 2CE28 8003C628 E545010C */  jal        func_80051794
    /* 2CE2C 8003C62C 21202002 */   addu      $a0, $s1, $zero
    /* 2CE30 8003C630 801F103C */  lui        $s0, %hi(D_1F800020)
    /* 2CE34 8003C634 20001026 */  addiu      $s0, $s0, %lo(D_1F800020)
    /* 2CE38 8003C638 E545010C */  jal        func_80051794
    /* 2CE3C 8003C63C 21200002 */   addu      $a0, $s0, $zero
    /* 2CE40 8003C640 54006426 */  addiu      $a0, $s3, 0x54
    /* 2CE44 8003C644 FC11020C */  jal        func_800847F0
    /* 2CE48 8003C648 21280002 */   addu      $a1, $s0, $zero
    /* 2CE4C 8003C64C 21200002 */  addu       $a0, $s0, $zero
    /* 2CE50 8003C650 21282002 */  addu       $a1, $s1, $zero
    /* 2CE54 8003C654 801F103C */  lui        $s0, %hi(D_1F800040)
    /* 2CE58 8003C658 40001026 */  addiu      $s0, $s0, %lo(D_1F800040)
    /* 2CE5C 8003C65C 47007292 */  lbu        $s2, 0x47($s3)
    /* 2CE60 8003C660 21300002 */  addu       $a2, $s0, $zero
    /* 2CE64 8003C664 4410020C */  jal        func_80084110
    /* 2CE68 8003C668 01005232 */   andi      $s2, $s2, 0x1
    /* 2CE6C 8003C66C 801F023C */  lui        $v0, (0x1F8000C0 >> 16)
    /* 2CE70 8003C670 2E006396 */  lhu        $v1, 0x2E($s3)
    /* 2CE74 8003C674 801F073C */  lui        $a3, %hi(D_1F8000F8)
    /* 2CE78 8003C678 C00043A4 */  sh         $v1, (0x1F8000C0 & 0xFFFF)($v0)
    /* 2CE7C 8003C67C 32006396 */  lhu        $v1, 0x32($s3)
    /* 2CE80 8003C680 C0004224 */  addiu      $v0, $v0, %lo(D_1F8000C0)
    /* 2CE84 8003C684 020043A4 */  sh         $v1, 0x2($v0)
    /* 2CE88 8003C688 36006396 */  lhu        $v1, 0x36($s3)
    /* 2CE8C 8003C68C F800E724 */  addiu      $a3, $a3, %lo(D_1F8000F8)
    /* 2CE90 8003C690 040043A4 */  sh         $v1, 0x4($v0)
    /* 2CE94 8003C694 0000EC8C */  lw         $t4, 0x0($a3)
    /* 2CE98 8003C698 0400ED8C */  lw         $t5, 0x4($a3)
    /* 2CE9C 8003C69C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2CEA0 8003C6A0 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2CEA4 8003C6A4 0800EC8C */  lw         $t4, 0x8($a3)
    /* 2CEA8 8003C6A8 0C00ED8C */  lw         $t5, 0xC($a3)
    /* 2CEAC 8003C6AC 1000EE8C */  lw         $t6, 0x10($a3)
    /* 2CEB0 8003C6B0 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2CEB4 8003C6B4 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2CEB8 8003C6B8 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2CEBC 8003C6BC 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2CEC0 8003C6C0 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2CEC4 8003C6C4 00000000 */  nop
    /* 2CEC8 8003C6C8 00000000 */  nop
    /* 2CECC 8003C6CC 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 2CED0 8003C6D0 801F073C */  lui        $a3, %hi(D_1F800054)
    /* 2CED4 8003C6D4 5400E724 */  addiu      $a3, $a3, %lo(D_1F800054)
    /* 2CED8 8003C6D8 0000F9E8 */  swc2       $25, 0x0($a3)
    /* 2CEDC 8003C6DC 0400FAE8 */  swc2       $26, 0x4($a3) /* handwritten instruction */
    /* 2CEE0 8003C6E0 0800FBE8 */  swc2       $27, 0x8($a3) /* handwritten instruction */
    /* 2CEE4 8003C6E4 801F043C */  lui        $a0, %hi(D_1F8000D0)
    /* 2CEE8 8003C6E8 D0008424 */  addiu      $a0, $a0, %lo(D_1F8000D0)
    /* 2CEEC 8003C6EC 1400028E */  lw         $v0, 0x14($s0)
    /* 2CEF0 8003C6F0 3C00838C */  lw         $v1, 0x3C($a0)
    /* 2CEF4 8003C6F4 00000000 */  nop
    /* 2CEF8 8003C6F8 21104300 */  addu       $v0, $v0, $v1
    /* 2CEFC 8003C6FC 140002AE */  sw         $v0, 0x14($s0)
    /* 2CF00 8003C700 1800028E */  lw         $v0, 0x18($s0)
    /* 2CF04 8003C704 4000858C */  lw         $a1, 0x40($a0)
    /* 2CF08 8003C708 1C00038E */  lw         $v1, 0x1C($s0)
    /* 2CF0C 8003C70C 4400848C */  lw         $a0, 0x44($a0)
    /* 2CF10 8003C710 21104500 */  addu       $v0, $v0, $a1
    /* 2CF14 8003C714 21186400 */  addu       $v1, $v1, $a0
    /* 2CF18 8003C718 180002AE */  sw         $v0, 0x18($s0)
    /* 2CF1C 8003C71C 1C0003AE */  sw         $v1, 0x1C($s0)
    /* 2CF20 8003C720 00000C8E */  lw         $t4, 0x0($s0)
    /* 2CF24 8003C724 04000D8E */  lw         $t5, 0x4($s0)
    /* 2CF28 8003C728 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2CF2C 8003C72C 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2CF30 8003C730 08000C8E */  lw         $t4, 0x8($s0)
    /* 2CF34 8003C734 0C000D8E */  lw         $t5, 0xC($s0)
    /* 2CF38 8003C738 10000E8E */  lw         $t6, 0x10($s0)
    /* 2CF3C 8003C73C 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2CF40 8003C740 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2CF44 8003C744 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2CF48 8003C748 14000C8E */  lw         $t4, 0x14($s0)
    /* 2CF4C 8003C74C 18000D8E */  lw         $t5, 0x18($s0)
    /* 2CF50 8003C750 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2CF54 8003C754 1C000E8E */  lw         $t6, 0x1C($s0)
    /* 2CF58 8003C758 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2CF5C 8003C75C 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2CF60 8003C760 21206002 */  addu       $a0, $s3, $zero
    /* 2CF64 8003C764 3DF2000C */  jal        func_8003C8F4
    /* 2CF68 8003C768 21284002 */   addu      $a1, $s2, $zero
  .L8003C76C:
    /* 2CF6C 8003C76C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 2CF70 8003C770 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2CF74 8003C774 1800B28F */  lw         $s2, 0x18($sp)
    /* 2CF78 8003C778 1400B18F */  lw         $s1, 0x14($sp)
    /* 2CF7C 8003C77C 1000B08F */  lw         $s0, 0x10($sp)
    /* 2CF80 8003C780 0800E003 */  jr         $ra
    /* 2CF84 8003C784 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel func_8003C5F8

/* Handwritten function */
nonmatching func_8003C788, 0x16C

glabel func_8003C788
    /* 2CF88 8003C788 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2CF8C 8003C78C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2CF90 8003C790 21908000 */  addu       $s2, $a0, $zero
    /* 2CF94 8003C794 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 2CF98 8003C798 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2CF9C 8003C79C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2CFA0 8003C7A0 3800428E */  lw         $v0, 0x38($s2)
    /* 2CFA4 8003C7A4 00000000 */  nop
    /* 2CFA8 8003C7A8 4C004010 */  beqz       $v0, .L8003C8DC
    /* 2CFAC 8003C7AC 801F103C */   lui       $s0, %hi(D_1F800000)
    /* 2CFB0 8003C7B0 00001026 */  addiu      $s0, $s0, %lo(D_1F800000)
    /* 2CFB4 8003C7B4 E545010C */  jal        func_80051794
    /* 2CFB8 8003C7B8 21200002 */   addu      $a0, $s0, $zero
    /* 2CFBC 8003C7BC 98004426 */  addiu      $a0, $s2, 0x98
    /* 2CFC0 8003C7C0 21280002 */  addu       $a1, $s0, $zero
    /* 2CFC4 8003C7C4 801F103C */  lui        $s0, %hi(D_1F800020)
    /* 2CFC8 8003C7C8 20001026 */  addiu      $s0, $s0, %lo(D_1F800020)
    /* 2CFCC 8003C7CC 47005192 */  lbu        $s1, 0x47($s2)
    /* 2CFD0 8003C7D0 21300002 */  addu       $a2, $s0, $zero
    /* 2CFD4 8003C7D4 4410020C */  jal        func_80084110
    /* 2CFD8 8003C7D8 01003132 */   andi      $s1, $s1, 0x1
    /* 2CFDC 8003C7DC 801F023C */  lui        $v0, (0x1F8000C0 >> 16)
    /* 2CFE0 8003C7E0 2E004396 */  lhu        $v1, 0x2E($s2)
    /* 2CFE4 8003C7E4 801F073C */  lui        $a3, %hi(D_1F8000F8)
    /* 2CFE8 8003C7E8 C00043A4 */  sh         $v1, (0x1F8000C0 & 0xFFFF)($v0)
    /* 2CFEC 8003C7EC 32004396 */  lhu        $v1, 0x32($s2)
    /* 2CFF0 8003C7F0 C0004224 */  addiu      $v0, $v0, %lo(D_1F8000C0)
    /* 2CFF4 8003C7F4 020043A4 */  sh         $v1, 0x2($v0)
    /* 2CFF8 8003C7F8 36004396 */  lhu        $v1, 0x36($s2)
    /* 2CFFC 8003C7FC F800E724 */  addiu      $a3, $a3, %lo(D_1F8000F8)
    /* 2D000 8003C800 040043A4 */  sh         $v1, 0x4($v0)
    /* 2D004 8003C804 0000EC8C */  lw         $t4, 0x0($a3)
    /* 2D008 8003C808 0400ED8C */  lw         $t5, 0x4($a3)
    /* 2D00C 8003C80C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2D010 8003C810 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2D014 8003C814 0800EC8C */  lw         $t4, 0x8($a3)
    /* 2D018 8003C818 0C00ED8C */  lw         $t5, 0xC($a3)
    /* 2D01C 8003C81C 1000EE8C */  lw         $t6, 0x10($a3)
    /* 2D020 8003C820 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2D024 8003C824 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2D028 8003C828 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2D02C 8003C82C 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2D030 8003C830 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2D034 8003C834 00000000 */  nop
    /* 2D038 8003C838 00000000 */  nop
    /* 2D03C 8003C83C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 2D040 8003C840 801F073C */  lui        $a3, %hi(D_1F800034)
    /* 2D044 8003C844 3400E724 */  addiu      $a3, $a3, %lo(D_1F800034)
    /* 2D048 8003C848 0000F9E8 */  swc2       $25, 0x0($a3)
    /* 2D04C 8003C84C 0400FAE8 */  swc2       $26, 0x4($a3) /* handwritten instruction */
    /* 2D050 8003C850 0800FBE8 */  swc2       $27, 0x8($a3) /* handwritten instruction */
    /* 2D054 8003C854 801F043C */  lui        $a0, %hi(D_1F8000D0)
    /* 2D058 8003C858 D0008424 */  addiu      $a0, $a0, %lo(D_1F8000D0)
    /* 2D05C 8003C85C 1400028E */  lw         $v0, 0x14($s0)
    /* 2D060 8003C860 3C00838C */  lw         $v1, 0x3C($a0)
    /* 2D064 8003C864 00000000 */  nop
    /* 2D068 8003C868 21104300 */  addu       $v0, $v0, $v1
    /* 2D06C 8003C86C 140002AE */  sw         $v0, 0x14($s0)
    /* 2D070 8003C870 1800028E */  lw         $v0, 0x18($s0)
    /* 2D074 8003C874 4000858C */  lw         $a1, 0x40($a0)
    /* 2D078 8003C878 1C00038E */  lw         $v1, 0x1C($s0)
    /* 2D07C 8003C87C 4400848C */  lw         $a0, 0x44($a0)
    /* 2D080 8003C880 21104500 */  addu       $v0, $v0, $a1
    /* 2D084 8003C884 21186400 */  addu       $v1, $v1, $a0
    /* 2D088 8003C888 180002AE */  sw         $v0, 0x18($s0)
    /* 2D08C 8003C88C 1C0003AE */  sw         $v1, 0x1C($s0)
    /* 2D090 8003C890 00000C8E */  lw         $t4, 0x0($s0)
    /* 2D094 8003C894 04000D8E */  lw         $t5, 0x4($s0)
    /* 2D098 8003C898 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2D09C 8003C89C 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2D0A0 8003C8A0 08000C8E */  lw         $t4, 0x8($s0)
    /* 2D0A4 8003C8A4 0C000D8E */  lw         $t5, 0xC($s0)
    /* 2D0A8 8003C8A8 10000E8E */  lw         $t6, 0x10($s0)
    /* 2D0AC 8003C8AC 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2D0B0 8003C8B0 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2D0B4 8003C8B4 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2D0B8 8003C8B8 14000C8E */  lw         $t4, 0x14($s0)
    /* 2D0BC 8003C8BC 18000D8E */  lw         $t5, 0x18($s0)
    /* 2D0C0 8003C8C0 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2D0C4 8003C8C4 1C000E8E */  lw         $t6, 0x1C($s0)
    /* 2D0C8 8003C8C8 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2D0CC 8003C8CC 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2D0D0 8003C8D0 21204002 */  addu       $a0, $s2, $zero
    /* 2D0D4 8003C8D4 3DF2000C */  jal        func_8003C8F4
    /* 2D0D8 8003C8D8 21282002 */   addu      $a1, $s1, $zero
  .L8003C8DC:
    /* 2D0DC 8003C8DC 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 2D0E0 8003C8E0 1800B28F */  lw         $s2, 0x18($sp)
    /* 2D0E4 8003C8E4 1400B18F */  lw         $s1, 0x14($sp)
    /* 2D0E8 8003C8E8 1000B08F */  lw         $s0, 0x10($sp)
    /* 2D0EC 8003C8EC 0800E003 */  jr         $ra
    /* 2D0F0 8003C8F0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_8003C788

/* Handwritten function */
nonmatching func_8003C8F4, 0x3B0

glabel func_8003C8F4
    /* 2D0F4 8003C8F4 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 2D0F8 8003C8F8 4400B1AF */  sw         $s1, 0x44($sp)
    /* 2D0FC 8003C8FC 21888000 */  addu       $s1, $a0, $zero
    /* 2D100 8003C900 5800B6AF */  sw         $s6, 0x58($sp)
    /* 2D104 8003C904 21B0A000 */  addu       $s6, $a1, $zero
    /* 2D108 8003C908 5C00BFAF */  sw         $ra, 0x5C($sp)
    /* 2D10C 8003C90C 5400B5AF */  sw         $s5, 0x54($sp)
    /* 2D110 8003C910 5000B4AF */  sw         $s4, 0x50($sp)
    /* 2D114 8003C914 4C00B3AF */  sw         $s3, 0x4C($sp)
    /* 2D118 8003C918 4800B2AF */  sw         $s2, 0x48($sp)
    /* 2D11C 8003C91C 4000B0AF */  sw         $s0, 0x40($sp)
    /* 2D120 8003C920 3800228E */  lw         $v0, 0x38($s1)
    /* 2D124 8003C924 00000000 */  nop
    /* 2D128 8003C928 D4004010 */  beqz       $v0, .L8003CC7C
    /* 2D12C 8003C92C 801F103C */   lui       $s0, (0x1F800018 >> 16)
    /* 2D130 8003C930 3000B227 */  addiu      $s2, $sp, 0x30
    /* 2D134 8003C934 FFFF1524 */  addiu      $s5, $zero, -0x1
    /* 2D138 8003C938 00004284 */  lh         $v0, 0x0($v0)
    /* 2D13C 8003C93C 3C00238E */  lw         $v1, 0x3C($s1)
    /* 2D140 8003C940 80100200 */  sll        $v0, $v0, 2
    /* 2D144 8003C944 21186200 */  addu       $v1, $v1, $v0
    /* 2D148 8003C948 02006484 */  lh         $a0, 0x2($v1)
    /* 2D14C 8003C94C 3C00228E */  lw         $v0, 0x3C($s1)
    /* 2D150 8003C950 00007484 */  lh         $s4, 0x0($v1)
    /* 2D154 8003C954 21984400 */  addu       $s3, $v0, $a0
  .L8003C958:
    /* 2D158 8003C958 1000A427 */  addiu      $a0, $sp, 0x10
    /* 2D15C 8003C95C 21280000 */  addu       $a1, $zero, $zero
    /* 2D160 8003C960 88EC000C */  jal        func_8003B220
    /* 2D164 8003C964 21306002 */   addu      $a2, $s3, $zero
    /* 2D168 8003C968 1000A227 */  addiu      $v0, $sp, 0x10
    /* 2D16C 8003C96C 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2D170 8003C970 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2D174 8003C974 080042C8 */  lwc2       $2, 0x8($v0)
    /* 2D178 8003C978 0C0043C8 */  lwc2       $3, 0xC($v0)
    /* 2D17C 8003C97C 100044C8 */  lwc2       $4, 0x10($v0)
    /* 2D180 8003C980 140045C8 */  lwc2       $5, 0x14($v0)
    /* 2D184 8003C984 00000000 */  nop
    /* 2D188 8003C988 00000000 */  nop
    /* 2D18C 8003C98C 3000284A */  rtpt
    /* 2D190 8003C990 00F84C48 */  cfc2       $t4, $31 /* handwritten instruction */
    /* 2D194 8003C994 00000000 */  nop
    /* 2D198 8003C998 00004CAE */  sw         $t4, 0x0($s2)
    /* 2D19C 8003C99C 0000428E */  lw         $v0, 0x0($s2)
    /* 2D1A0 8003C9A0 00000000 */  nop
    /* 2D1A4 8003C9A4 15004004 */  bltz       $v0, .L8003C9FC
    /* 2D1A8 8003C9A8 00000000 */   nop
    /* 2D1AC 8003C9AC 08000CEA */  swc2       $12, (0x1F800008 & 0xFFFF)($s0)
    /* 2D1B0 8003C9B0 10000DEA */  swc2       $13, (0x1F800010 & 0xFFFF)($s0)
    /* 2D1B4 8003C9B4 18000EEA */  swc2       $14, (0x1F800018 & 0xFFFF)($s0)
    /* 2D1B8 8003C9B8 00000000 */  nop
    /* 2D1BC 8003C9BC 00000000 */  nop
    /* 2D1C0 8003C9C0 0600404B */  nclip
    /* 2D1C4 8003C9C4 000058EA */  swc2       $24, 0x0($s2)
    /* 2D1C8 8003C9C8 2800A227 */  addiu      $v0, $sp, 0x28
    /* 2D1CC 8003C9CC 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2D1D0 8003C9D0 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2D1D4 8003C9D4 00000000 */  nop
    /* 2D1D8 8003C9D8 00000000 */  nop
    /* 2D1DC 8003C9DC 0100184A */  rtps
    /* 2D1E0 8003C9E0 00F84C48 */  cfc2       $t4, $31 /* handwritten instruction */
    /* 2D1E4 8003C9E4 00000000 */  nop
    /* 2D1E8 8003C9E8 00004CAE */  sw         $t4, 0x0($s2)
    /* 2D1EC 8003C9EC 0000428E */  lw         $v0, 0x0($s2)
    /* 2D1F0 8003C9F0 00000000 */  nop
    /* 2D1F4 8003C9F4 03004104 */  bgez       $v0, .L8003CA04
    /* 2D1F8 8003C9F8 20000226 */   addiu     $v0, $s0, %lo(D_1F800020)
  .L8003C9FC:
    /* 2D1FC 8003C9FC 8AF20008 */  j          .L8003CA28
    /* 2D200 8003CA00 3800B5AF */   sw        $s5, 0x38($sp)
  .L8003CA04:
    /* 2D204 8003CA04 00004EE8 */  swc2       $14, 0x0($v0)
    /* 2D208 8003CA08 00000000 */  nop
    /* 2D20C 8003CA0C 00000000 */  nop
    /* 2D210 8003CA10 2E00684B */  avsz4
    /* 2D214 8003CA14 3400A227 */  addiu      $v0, $sp, 0x34
    /* 2D218 8003CA18 000047E8 */  swc2       $7, 0x0($v0)
    /* 2D21C 8003CA1C 3400A28F */  lw         $v0, 0x34($sp)
    /* 2D220 8003CA20 00000000 */  nop
    /* 2D224 8003CA24 3800A2AF */  sw         $v0, 0x38($sp)
  .L8003CA28:
    /* 2D228 8003CA28 08000296 */  lhu        $v0, (0x1F800008 & 0xFFFF)($s0)
    /* 2D22C 8003CA2C 00000000 */  nop
    /* 2D230 8003CA30 4001422C */  sltiu      $v0, $v0, 0x140
    /* 2D234 8003CA34 10004014 */  bnez       $v0, .L8003CA78
    /* 2D238 8003CA38 00000000 */   nop
    /* 2D23C 8003CA3C 10000296 */  lhu        $v0, (0x1F800010 & 0xFFFF)($s0)
    /* 2D240 8003CA40 00000000 */  nop
    /* 2D244 8003CA44 4001422C */  sltiu      $v0, $v0, 0x140
    /* 2D248 8003CA48 0B004014 */  bnez       $v0, .L8003CA78
    /* 2D24C 8003CA4C 00000000 */   nop
    /* 2D250 8003CA50 18000296 */  lhu        $v0, (0x1F800018 & 0xFFFF)($s0)
    /* 2D254 8003CA54 00000000 */  nop
    /* 2D258 8003CA58 4001422C */  sltiu      $v0, $v0, 0x140
    /* 2D25C 8003CA5C 06004014 */  bnez       $v0, .L8003CA78
    /* 2D260 8003CA60 00000000 */   nop
    /* 2D264 8003CA64 20000296 */  lhu        $v0, (0x1F800020 & 0xFFFF)($s0)
    /* 2D268 8003CA68 00000000 */  nop
    /* 2D26C 8003CA6C 4001422C */  sltiu      $v0, $v0, 0x140
    /* 2D270 8003CA70 7F004010 */  beqz       $v0, .L8003CC70
    /* 2D274 8003CA74 00000000 */   nop
  .L8003CA78:
    /* 2D278 8003CA78 0A000296 */  lhu        $v0, (0x1F80000A & 0xFFFF)($s0)
    /* 2D27C 8003CA7C 00000000 */  nop
    /* 2D280 8003CA80 F000422C */  sltiu      $v0, $v0, 0xF0
    /* 2D284 8003CA84 10004014 */  bnez       $v0, .L8003CAC8
    /* 2D288 8003CA88 00000000 */   nop
    /* 2D28C 8003CA8C 12000296 */  lhu        $v0, (0x1F800012 & 0xFFFF)($s0)
    /* 2D290 8003CA90 00000000 */  nop
    /* 2D294 8003CA94 F000422C */  sltiu      $v0, $v0, 0xF0
    /* 2D298 8003CA98 0B004014 */  bnez       $v0, .L8003CAC8
    /* 2D29C 8003CA9C 00000000 */   nop
    /* 2D2A0 8003CAA0 1A000296 */  lhu        $v0, (0x1F80001A & 0xFFFF)($s0)
    /* 2D2A4 8003CAA4 00000000 */  nop
    /* 2D2A8 8003CAA8 F000422C */  sltiu      $v0, $v0, 0xF0
    /* 2D2AC 8003CAAC 06004014 */  bnez       $v0, .L8003CAC8
    /* 2D2B0 8003CAB0 00000000 */   nop
    /* 2D2B4 8003CAB4 22000296 */  lhu        $v0, (0x1F800022 & 0xFFFF)($s0)
    /* 2D2B8 8003CAB8 00000000 */  nop
    /* 2D2BC 8003CABC F000422C */  sltiu      $v0, $v0, 0xF0
    /* 2D2C0 8003CAC0 6B004010 */  beqz       $v0, .L8003CC70
    /* 2D2C4 8003CAC4 00000000 */   nop
  .L8003CAC8:
    /* 2D2C8 8003CAC8 08002282 */  lb         $v0, 0x8($s1)
    /* 2D2CC 8003CACC 3800A38F */  lw         $v1, 0x38($sp)
    /* 2D2D0 8003CAD0 00000000 */  nop
    /* 2D2D4 8003CAD4 21186200 */  addu       $v1, $v1, $v0
    /* 2D2D8 8003CAD8 83120300 */  sra        $v0, $v1, 10
    /* 2D2DC 8003CADC 07184300 */  srav       $v1, $v1, $v0
    /* 2D2E0 8003CAE0 40120200 */  sll        $v0, $v0, 9
    /* 2D2E4 8003CAE4 21186200 */  addu       $v1, $v1, $v0
    /* 2D2E8 8003CAE8 3800A3AF */  sw         $v1, 0x38($sp)
    /* 2D2EC 8003CAEC FCFF6324 */  addiu      $v1, $v1, -0x4
    /* 2D2F0 8003CAF0 FC07632C */  sltiu      $v1, $v1, 0x7FC
    /* 2D2F4 8003CAF4 02006014 */  bnez       $v1, .L8003CB00
    /* 2D2F8 8003CAF8 00000000 */   nop
    /* 2D2FC 8003CAFC 3800B5AF */  sw         $s5, 0x38($sp)
  .L8003CB00:
    /* 2D300 8003CB00 3800A28F */  lw         $v0, 0x38($sp)
    /* 2D304 8003CB04 00000000 */  nop
    /* 2D308 8003CB08 59004004 */  bltz       $v0, .L8003CC70
    /* 2D30C 8003CB0C 21200002 */   addu      $a0, $s0, $zero
    /* 2D310 8003CB10 21286002 */  addu       $a1, $s3, $zero
    /* 2D314 8003CB14 15EC000C */  jal        func_8003B054
    /* 2D318 8003CB18 2130C002 */   addu      $a2, $s6, $zero
    /* 2D31C 8003CB1C 5C002296 */  lhu        $v0, 0x5C($s1)
    /* 2D320 8003CB20 00000000 */  nop
    /* 2D324 8003CB24 02004010 */  beqz       $v0, .L8003CB30
    /* 2D328 8003CB28 00000000 */   nop
    /* 2D32C 8003CB2C 0E0002A6 */  sh         $v0, (0x1F80000E & 0xFFFF)($s0)
  .L8003CB30:
    /* 2D330 8003CB30 0D002392 */  lbu        $v1, 0xD($s1)
    /* 2D334 8003CB34 00000000 */  nop
    /* 2D338 8003CB38 2100622C */  sltiu      $v0, $v1, 0x21
    /* 2D33C 8003CB3C 22004010 */  beqz       $v0, .L8003CBC8
    /* 2D340 8003CB40 0180023C */   lui       $v0, %hi(jtbl_80014E40)
    /* 2D344 8003CB44 404E4224 */  addiu      $v0, $v0, %lo(jtbl_80014E40)
    /* 2D348 8003CB48 80180300 */  sll        $v1, $v1, 2
    /* 2D34C 8003CB4C 21186200 */  addu       $v1, $v1, $v0
    /* 2D350 8003CB50 0000628C */  lw         $v0, 0x0($v1)
    /* 2D354 8003CB54 00000000 */  nop
    /* 2D358 8003CB58 08004000 */  jr         $v0
    /* 2D35C 8003CB5C 00000000 */   nop
    /* 2D360 8003CB60 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 2D364 8003CB64 F2F20008 */  j          .L8003CBC8
    /* 2D368 8003CB68 070002A2 */   sb        $v0, 0x7($s0)
    /* 2D36C 8003CB6C 2F000224 */  addiu      $v0, $zero, 0x2F
    /* 2D370 8003CB70 F2F20008 */  j          .L8003CBC8
    /* 2D374 8003CB74 070002A2 */   sb        $v0, 0x7($s0)
    /* 2D378 8003CB78 1800228E */  lw         $v0, 0x18($s1)
    /* 2D37C 8003CB7C 00000000 */  nop
    /* 2D380 8003CB80 040002AE */  sw         $v0, 0x4($s0)
    /* 2D384 8003CB84 2C000224 */  addiu      $v0, $zero, 0x2C
    /* 2D388 8003CB88 F2F20008 */  j          .L8003CBC8
    /* 2D38C 8003CB8C 070002A2 */   sb        $v0, 0x7($s0)
    /* 2D390 8003CB90 1800228E */  lw         $v0, 0x18($s1)
    /* 2D394 8003CB94 00000000 */  nop
    /* 2D398 8003CB98 040002AE */  sw         $v0, 0x4($s0)
    /* 2D39C 8003CB9C 2E000224 */  addiu      $v0, $zero, 0x2E
    /* 2D3A0 8003CBA0 F2F20008 */  j          .L8003CBC8
    /* 2D3A4 8003CBA4 070002A2 */   sb        $v0, 0x7($s0)
    /* 2D3A8 8003CBA8 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 2D3AC 8003CBAC 070002A2 */  sb         $v0, 0x7($s0)
    /* 2D3B0 8003CBB0 18002292 */  lbu        $v0, 0x18($s1)
    /* 2D3B4 8003CBB4 00000000 */  nop
    /* 2D3B8 8003CBB8 02004014 */  bnez       $v0, .L8003CBC4
    /* 2D3BC 8003CBBC 7B400224 */   addiu     $v0, $zero, 0x407B
    /* 2D3C0 8003CBC0 3B400224 */  addiu      $v0, $zero, 0x403B
  .L8003CBC4:
    /* 2D3C4 8003CBC4 0E0002A6 */  sh         $v0, 0xE($s0)
  .L8003CBC8:
    /* 2D3C8 8003CBC8 0C80063C */  lui        $a2, %hi(D_800BF544)
    /* 2D3CC 8003CBCC 44F5C48C */  lw         $a0, %lo(D_800BF544)($a2)
    /* 2D3D0 8003CBD0 0F80033C */  lui        $v1, %hi(D_800ED8C8)
    /* 2D3D4 8003CBD4 3800A28F */  lw         $v0, 0x38($sp)
    /* 2D3D8 8003CBD8 C8D8658C */  lw         $a1, %lo(D_800ED8C8)($v1)
    /* 2D3DC 8003CBDC 80100200 */  sll        $v0, $v0, 2
    /* 2D3E0 8003CBE0 2128A200 */  addu       $a1, $a1, $v0
    /* 2D3E4 8003CBE4 0000A28C */  lw         $v0, 0x0($a1)
    /* 2D3E8 8003CBE8 0009033C */  lui        $v1, (0x9000000 >> 16)
    /* 2D3EC 8003CBEC 25104300 */  or         $v0, $v0, $v1
    /* 2D3F0 8003CBF0 000082AC */  sw         $v0, 0x0($a0)
    /* 2D3F4 8003CBF4 0000A4AC */  sw         $a0, 0x0($a1)
    /* 2D3F8 8003CBF8 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D3FC 8003CBFC 0400028E */  lw         $v0, (0x1F800004 & 0xFFFF)($s0)
    /* 2D400 8003CC00 00000000 */  nop
    /* 2D404 8003CC04 000082AC */  sw         $v0, 0x0($a0)
    /* 2D408 8003CC08 0800028E */  lw         $v0, (0x1F800008 & 0xFFFF)($s0)
    /* 2D40C 8003CC0C 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D410 8003CC10 000082AC */  sw         $v0, 0x0($a0)
    /* 2D414 8003CC14 0C00028E */  lw         $v0, (0x1F80000C & 0xFFFF)($s0)
    /* 2D418 8003CC18 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D41C 8003CC1C 000082AC */  sw         $v0, 0x0($a0)
    /* 2D420 8003CC20 1000028E */  lw         $v0, (0x1F800010 & 0xFFFF)($s0)
    /* 2D424 8003CC24 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D428 8003CC28 000082AC */  sw         $v0, 0x0($a0)
    /* 2D42C 8003CC2C 1400028E */  lw         $v0, (0x1F800014 & 0xFFFF)($s0)
    /* 2D430 8003CC30 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D434 8003CC34 000082AC */  sw         $v0, 0x0($a0)
    /* 2D438 8003CC38 1800028E */  lw         $v0, (0x1F800018 & 0xFFFF)($s0)
    /* 2D43C 8003CC3C 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D440 8003CC40 000082AC */  sw         $v0, 0x0($a0)
    /* 2D444 8003CC44 1C00028E */  lw         $v0, (0x1F80001C & 0xFFFF)($s0)
    /* 2D448 8003CC48 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D44C 8003CC4C 000082AC */  sw         $v0, 0x0($a0)
    /* 2D450 8003CC50 2000028E */  lw         $v0, (0x1F800020 & 0xFFFF)($s0)
    /* 2D454 8003CC54 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D458 8003CC58 000082AC */  sw         $v0, 0x0($a0)
    /* 2D45C 8003CC5C 2400028E */  lw         $v0, (0x1F800024 & 0xFFFF)($s0)
    /* 2D460 8003CC60 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D464 8003CC64 000082AC */  sw         $v0, 0x0($a0)
    /* 2D468 8003CC68 04008424 */  addiu      $a0, $a0, 0x4
    /* 2D46C 8003CC6C 44F5C4AC */  sw         $a0, %lo(D_800BF544)($a2)
  .L8003CC70:
    /* 2D470 8003CC70 FFFF9426 */  addiu      $s4, $s4, -0x1
    /* 2D474 8003CC74 38FF8016 */  bnez       $s4, .L8003C958
    /* 2D478 8003CC78 10007326 */   addiu     $s3, $s3, 0x10
  .L8003CC7C:
    /* 2D47C 8003CC7C 5C00BF8F */  lw         $ra, 0x5C($sp)
    /* 2D480 8003CC80 5800B68F */  lw         $s6, 0x58($sp)
    /* 2D484 8003CC84 5400B58F */  lw         $s5, 0x54($sp)
    /* 2D488 8003CC88 5000B48F */  lw         $s4, 0x50($sp)
    /* 2D48C 8003CC8C 4C00B38F */  lw         $s3, 0x4C($sp)
    /* 2D490 8003CC90 4800B28F */  lw         $s2, 0x48($sp)
    /* 2D494 8003CC94 4400B18F */  lw         $s1, 0x44($sp)
    /* 2D498 8003CC98 4000B08F */  lw         $s0, 0x40($sp)
    /* 2D49C 8003CC9C 0800E003 */  jr         $ra
    /* 2D4A0 8003CCA0 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_8003C8F4

nonmatching func_8003CCA4, 0x134

glabel func_8003CCA4
    /* 2D4A4 8003CCA4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2D4A8 8003CCA8 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2D4AC 8003CCAC 21908000 */  addu       $s2, $a0, $zero
    /* 2D4B0 8003CCB0 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 2D4B4 8003CCB4 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2D4B8 8003CCB8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2D4BC 8003CCBC 0B004392 */  lbu        $v1, 0xB($s2)
    /* 2D4C0 8003CCC0 801F023C */  lui        $v0, (0x1F80028C >> 16)
    /* 2D4C4 8003CCC4 8C0252AC */  sw         $s2, (0x1F80028C & 0xFFFF)($v0)
    /* 2D4C8 8003CCC8 0D004292 */  lbu        $v0, 0xD($s2)
    /* 2D4CC 8003CCCC 0F006338 */  xori       $v1, $v1, 0xF
    /* 2D4D0 8003CCD0 0100652C */  sltiu      $a1, $v1, 0x1
    /* 2D4D4 8003CCD4 0B004330 */  andi       $v1, $v0, 0xB
    /* 2D4D8 8003CCD8 0900622C */  sltiu      $v0, $v1, 0x9
    /* 2D4DC 8003CCDC 38004010 */  beqz       $v0, .L8003CDC0
    /* 2D4E0 8003CCE0 0180023C */   lui       $v0, %hi(jtbl_80014EC8)
    /* 2D4E4 8003CCE4 C84E4224 */  addiu      $v0, $v0, %lo(jtbl_80014EC8)
    /* 2D4E8 8003CCE8 80180300 */  sll        $v1, $v1, 2
    /* 2D4EC 8003CCEC 21186200 */  addu       $v1, $v1, $v0
    /* 2D4F0 8003CCF0 0000628C */  lw         $v0, 0x0($v1)
    /* 2D4F4 8003CCF4 00000000 */  nop
    /* 2D4F8 8003CCF8 08004000 */  jr         $v0
    /* 2D4FC 8003CCFC 00000000 */   nop
    /* 2D500 8003CD00 76F3000C */  jal        func_8003CDD8
    /* 2D504 8003CD04 21204002 */   addu      $a0, $s2, $zero
    /* 2D508 8003CD08 70F30008 */  j          .L8003CDC0
    /* 2D50C 8003CD0C 00000000 */   nop
    /* 2D510 8003CD10 0C80103C */  lui        $s0, %hi(D_800BF544)
    /* 2D514 8003CD14 44F5118E */  lw         $s1, %lo(D_800BF544)($s0)
    /* 2D518 8003CD18 76F3000C */  jal        func_8003CDD8
    /* 2D51C 8003CD1C 21204002 */   addu      $a0, $s2, $zero
    /* 2D520 8003CD20 21204002 */  addu       $a0, $s2, $zero
    /* 2D524 8003CD24 44F5068E */  lw         $a2, %lo(D_800BF544)($s0)
    /* 2D528 8003CD28 61F5000C */  jal        GPU_ModulateOTColors
    /* 2D52C 8003CD2C 21282002 */   addu      $a1, $s1, $zero
    /* 2D530 8003CD30 70F30008 */  j          .L8003CDC0
    /* 2D534 8003CD34 00000000 */   nop
    /* 2D538 8003CD38 0C80103C */  lui        $s0, %hi(D_800BF544)
    /* 2D53C 8003CD3C 44F5118E */  lw         $s1, %lo(D_800BF544)($s0)
    /* 2D540 8003CD40 76F3000C */  jal        func_8003CDD8
    /* 2D544 8003CD44 21204002 */   addu      $a0, $s2, $zero
    /* 2D548 8003CD48 21204002 */  addu       $a0, $s2, $zero
    /* 2D54C 8003CD4C 44F5068E */  lw         $a2, %lo(D_800BF544)($s0)
    /* 2D550 8003CD50 D1FC000C */  jal        func_8003F344
    /* 2D554 8003CD54 21282002 */   addu      $a1, $s1, $zero
    /* 2D558 8003CD58 70F30008 */  j          .L8003CDC0
    /* 2D55C 8003CD5C 00000000 */   nop
    /* 2D560 8003CD60 0C80103C */  lui        $s0, %hi(D_800BF544)
    /* 2D564 8003CD64 44F5118E */  lw         $s1, %lo(D_800BF544)($s0)
    /* 2D568 8003CD68 76F3000C */  jal        func_8003CDD8
    /* 2D56C 8003CD6C 21204002 */   addu      $a0, $s2, $zero
    /* 2D570 8003CD70 1B004292 */  lbu        $v0, 0x1B($s2)
    /* 2D574 8003CD74 44F5068E */  lw         $a2, %lo(D_800BF544)($s0)
    /* 2D578 8003CD78 05004010 */  beqz       $v0, .L8003CD90
    /* 2D57C 8003CD7C 21204002 */   addu      $a0, $s2, $zero
    /* 2D580 8003CD80 FDFC000C */  jal        func_8003F3F4
    /* 2D584 8003CD84 21282002 */   addu      $a1, $s1, $zero
    /* 2D588 8003CD88 70F30008 */  j          .L8003CDC0
    /* 2D58C 8003CD8C 00000000 */   nop
  .L8003CD90:
    /* 2D590 8003CD90 31FD000C */  jal        func_8003F4C4
    /* 2D594 8003CD94 21282002 */   addu      $a1, $s1, $zero
    /* 2D598 8003CD98 70F30008 */  j          .L8003CDC0
    /* 2D59C 8003CD9C 00000000 */   nop
    /* 2D5A0 8003CDA0 0C80103C */  lui        $s0, %hi(D_800BF544)
    /* 2D5A4 8003CDA4 44F5118E */  lw         $s1, %lo(D_800BF544)($s0)
    /* 2D5A8 8003CDA8 76F3000C */  jal        func_8003CDD8
    /* 2D5AC 8003CDAC 21204002 */   addu      $a0, $s2, $zero
    /* 2D5B0 8003CDB0 21204002 */  addu       $a0, $s2, $zero
    /* 2D5B4 8003CDB4 44F5068E */  lw         $a2, %lo(D_800BF544)($s0)
    /* 2D5B8 8003CDB8 65FD000C */  jal        func_8003F594
    /* 2D5BC 8003CDBC 21282002 */   addu      $a1, $s1, $zero
  .L8003CDC0:
    /* 2D5C0 8003CDC0 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 2D5C4 8003CDC4 1800B28F */  lw         $s2, 0x18($sp)
    /* 2D5C8 8003CDC8 1400B18F */  lw         $s1, 0x14($sp)
    /* 2D5CC 8003CDCC 1000B08F */  lw         $s0, 0x10($sp)
    /* 2D5D0 8003CDD0 0800E003 */  jr         $ra
    /* 2D5D4 8003CDD4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_8003CCA4

/* Handwritten function */
nonmatching func_8003CDD8, 0x2E4

glabel func_8003CDD8
    /* 2D5D8 8003CDD8 C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* 2D5DC 8003CDDC 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2D5E0 8003CDE0 21908000 */  addu       $s2, $a0, $zero
    /* 2D5E4 8003CDE4 3000BFAF */  sw         $ra, 0x30($sp)
    /* 2D5E8 8003CDE8 2C00B7AF */  sw         $s7, 0x2C($sp)
    /* 2D5EC 8003CDEC 2800B6AF */  sw         $s6, 0x28($sp)
    /* 2D5F0 8003CDF0 2400B5AF */  sw         $s5, 0x24($sp)
    /* 2D5F4 8003CDF4 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2D5F8 8003CDF8 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2D5FC 8003CDFC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2D600 8003CE00 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2D604 8003CE04 08004292 */  lbu        $v0, 0x8($s2)
    /* 2D608 8003CE08 00000000 */  nop
    /* 2D60C 8003CE0C A0004010 */  beqz       $v0, .L8003D090
    /* 2D610 8003CE10 21B0A000 */   addu      $s6, $a1, $zero
    /* 2D614 8003CE14 09004292 */  lbu        $v0, 0x9($s2)
    /* 2D618 8003CE18 00000000 */  nop
    /* 2D61C 8003CE1C 9C004010 */  beqz       $v0, .L8003D090
    /* 2D620 8003CE20 21800000 */   addu      $s0, $zero, $zero
    /* 2D624 8003CE24 801F173C */  lui        $s7, (0x1F8000C0 >> 16)
    /* 2D628 8003CE28 C000F526 */  addiu      $s5, $s7, %lo(D_1F8000C0)
    /* 2D62C 8003CE2C 801F023C */  lui        $v0, %hi(D_1F800000)
    /* 2D630 8003CE30 00005124 */  addiu      $s1, $v0, %lo(D_1F800000)
    /* 2D634 8003CE34 801F023C */  lui        $v0, %hi(D_1F8000D0)
    /* 2D638 8003CE38 D0005324 */  addiu      $s3, $v0, %lo(D_1F8000D0)
    /* 2D63C 8003CE3C 0F80143C */  lui        $s4, %hi(D_800ED8C8)
  .L8003CE40:
    /* 2D640 8003CE40 08004292 */  lbu        $v0, 0x8($s2)
    /* 2D644 8003CE44 00000000 */  nop
    /* 2D648 8003CE48 2A100202 */  slt        $v0, $s0, $v0
    /* 2D64C 8003CE4C 90004010 */  beqz       $v0, .L8003D090
    /* 2D650 8003CE50 80101000 */   sll       $v0, $s0, 2
    /* 2D654 8003CE54 21104202 */  addu       $v0, $s2, $v0
    /* 2D658 8003CE58 C000478C */  lw         $a3, 0xC0($v0)
    /* 2D65C 8003CE5C 00000000 */  nop
    /* 2D660 8003CE60 4000E28C */  lw         $v0, 0x40($a3)
    /* 2D664 8003CE64 00000000 */  nop
    /* 2D668 8003CE68 84004010 */  beqz       $v0, .L8003D07C
    /* 2D66C 8003CE6C 801F083C */   lui       $t0, %hi(D_1F8000F8)
    /* 2D670 8003CE70 2C00E294 */  lhu        $v0, 0x2C($a3)
    /* 2D674 8003CE74 00000000 */  nop
    /* 2D678 8003CE78 C000E2A6 */  sh         $v0, (0x1F8000C0 & 0xFFFF)($s7)
    /* 2D67C 8003CE7C 3000E294 */  lhu        $v0, 0x30($a3)
    /* 2D680 8003CE80 00000000 */  nop
    /* 2D684 8003CE84 0200A2A6 */  sh         $v0, 0x2($s5)
    /* 2D688 8003CE88 3400E294 */  lhu        $v0, 0x34($a3)
    /* 2D68C 8003CE8C F8000825 */  addiu      $t0, $t0, %lo(D_1F8000F8)
    /* 2D690 8003CE90 0400A2A6 */  sh         $v0, 0x4($s5)
    /* 2D694 8003CE94 00000C8D */  lw         $t4, 0x0($t0)
    /* 2D698 8003CE98 04000D8D */  lw         $t5, 0x4($t0)
    /* 2D69C 8003CE9C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2D6A0 8003CEA0 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2D6A4 8003CEA4 08000C8D */  lw         $t4, 0x8($t0)
    /* 2D6A8 8003CEA8 0C000D8D */  lw         $t5, 0xC($t0)
    /* 2D6AC 8003CEAC 10000E8D */  lw         $t6, 0x10($t0)
    /* 2D6B0 8003CEB0 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2D6B4 8003CEB4 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2D6B8 8003CEB8 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2D6BC 8003CEBC 1800E224 */  addiu      $v0, $a3, 0x18
    /* 2D6C0 8003CEC0 00004C94 */  lhu        $t4, 0x0($v0)
    /* 2D6C4 8003CEC4 06004D94 */  lhu        $t5, 0x6($v0)
    /* 2D6C8 8003CEC8 0C004E94 */  lhu        $t6, 0xC($v0)
    /* 2D6CC 8003CECC 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 2D6D0 8003CED0 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 2D6D4 8003CED4 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 2D6D8 8003CED8 00000000 */  nop
    /* 2D6DC 8003CEDC 00000000 */  nop
    /* 2D6E0 8003CEE0 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 2D6E4 8003CEE4 801F083C */  lui        $t0, %hi(D_1F800000)
    /* 2D6E8 8003CEE8 00000825 */  addiu      $t0, $t0, %lo(D_1F800000)
    /* 2D6EC 8003CEEC 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 2D6F0 8003CEF0 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 2D6F4 8003CEF4 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 2D6F8 8003CEF8 00000CA5 */  sh         $t4, 0x0($t0)
    /* 2D6FC 8003CEFC 06000DA5 */  sh         $t5, 0x6($t0)
    /* 2D700 8003CF00 0C000EA5 */  sh         $t6, 0xC($t0)
    /* 2D704 8003CF04 1A00E224 */  addiu      $v0, $a3, 0x1A
    /* 2D708 8003CF08 00004C94 */  lhu        $t4, 0x0($v0)
    /* 2D70C 8003CF0C 06004D94 */  lhu        $t5, 0x6($v0)
    /* 2D710 8003CF10 0C004E94 */  lhu        $t6, 0xC($v0)
    /* 2D714 8003CF14 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 2D718 8003CF18 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 2D71C 8003CF1C 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 2D720 8003CF20 00000000 */  nop
    /* 2D724 8003CF24 00000000 */  nop
    /* 2D728 8003CF28 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 2D72C 8003CF2C 801F083C */  lui        $t0, %hi(D_1F800002)
    /* 2D730 8003CF30 02000825 */  addiu      $t0, $t0, %lo(D_1F800002)
    /* 2D734 8003CF34 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 2D738 8003CF38 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 2D73C 8003CF3C 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 2D740 8003CF40 00000CA5 */  sh         $t4, 0x0($t0)
    /* 2D744 8003CF44 06000DA5 */  sh         $t5, 0x6($t0)
    /* 2D748 8003CF48 0C000EA5 */  sh         $t6, 0xC($t0)
    /* 2D74C 8003CF4C 1C00E224 */  addiu      $v0, $a3, 0x1C
    /* 2D750 8003CF50 00004C94 */  lhu        $t4, 0x0($v0)
    /* 2D754 8003CF54 06004D94 */  lhu        $t5, 0x6($v0)
    /* 2D758 8003CF58 0C004E94 */  lhu        $t6, 0xC($v0)
    /* 2D75C 8003CF5C 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 2D760 8003CF60 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 2D764 8003CF64 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 2D768 8003CF68 00000000 */  nop
    /* 2D76C 8003CF6C 00000000 */  nop
    /* 2D770 8003CF70 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 2D774 8003CF74 801F083C */  lui        $t0, %hi(D_1F800004)
    /* 2D778 8003CF78 04000825 */  addiu      $t0, $t0, %lo(D_1F800004)
    /* 2D77C 8003CF7C 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 2D780 8003CF80 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 2D784 8003CF84 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 2D788 8003CF88 00000CA5 */  sh         $t4, 0x0($t0)
    /* 2D78C 8003CF8C 06000DA5 */  sh         $t5, 0x6($t0)
    /* 2D790 8003CF90 0C000EA5 */  sh         $t6, 0xC($t0)
    /* 2D794 8003CF94 801F083C */  lui        $t0, %hi(D_1F8000C0)
    /* 2D798 8003CF98 C0000825 */  addiu      $t0, $t0, %lo(D_1F8000C0)
    /* 2D79C 8003CF9C 000000C9 */  lwc2       $0, 0x0($t0)
    /* 2D7A0 8003CFA0 040001C9 */  lwc2       $1, 0x4($t0)
    /* 2D7A4 8003CFA4 00000000 */  nop
    /* 2D7A8 8003CFA8 00000000 */  nop
    /* 2D7AC 8003CFAC 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 2D7B0 8003CFB0 801F083C */  lui        $t0, %hi(D_1F800014)
    /* 2D7B4 8003CFB4 14000825 */  addiu      $t0, $t0, %lo(D_1F800014)
    /* 2D7B8 8003CFB8 000019E9 */  swc2       $25, 0x0($t0)
    /* 2D7BC 8003CFBC 04001AE9 */  swc2       $26, 0x4($t0) /* handwritten instruction */
    /* 2D7C0 8003CFC0 08001BE9 */  swc2       $27, 0x8($t0) /* handwritten instruction */
    /* 2D7C4 8003CFC4 801F083C */  lui        $t0, %hi(D_1F800000)
    /* 2D7C8 8003CFC8 1400228E */  lw         $v0, 0x14($s1)
    /* 2D7CC 8003CFCC 3C00638E */  lw         $v1, 0x3C($s3)
    /* 2D7D0 8003CFD0 00000825 */  addiu      $t0, $t0, %lo(D_1F800000)
    /* 2D7D4 8003CFD4 21104300 */  addu       $v0, $v0, $v1
    /* 2D7D8 8003CFD8 140022AE */  sw         $v0, 0x14($s1)
    /* 2D7DC 8003CFDC 1800228E */  lw         $v0, 0x18($s1)
    /* 2D7E0 8003CFE0 4000648E */  lw         $a0, 0x40($s3)
    /* 2D7E4 8003CFE4 1C00238E */  lw         $v1, 0x1C($s1)
    /* 2D7E8 8003CFE8 4400658E */  lw         $a1, 0x44($s3)
    /* 2D7EC 8003CFEC 21104400 */  addu       $v0, $v0, $a0
    /* 2D7F0 8003CFF0 21186500 */  addu       $v1, $v1, $a1
    /* 2D7F4 8003CFF4 180022AE */  sw         $v0, 0x18($s1)
    /* 2D7F8 8003CFF8 1C0023AE */  sw         $v1, 0x1C($s1)
    /* 2D7FC 8003CFFC 00000C8D */  lw         $t4, 0x0($t0)
    /* 2D800 8003D000 04000D8D */  lw         $t5, 0x4($t0)
    /* 2D804 8003D004 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2D808 8003D008 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2D80C 8003D00C 08000C8D */  lw         $t4, 0x8($t0)
    /* 2D810 8003D010 0C000D8D */  lw         $t5, 0xC($t0)
    /* 2D814 8003D014 10000E8D */  lw         $t6, 0x10($t0)
    /* 2D818 8003D018 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2D81C 8003D01C 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2D820 8003D020 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2D824 8003D024 801F083C */  lui        $t0, %hi(D_1F800000)
    /* 2D828 8003D028 00000825 */  addiu      $t0, $t0, %lo(D_1F800000)
    /* 2D82C 8003D02C 14000C8D */  lw         $t4, 0x14($t0)
    /* 2D830 8003D030 18000D8D */  lw         $t5, 0x18($t0)
    /* 2D834 8003D034 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2D838 8003D038 1C000E8D */  lw         $t6, 0x1C($t0)
    /* 2D83C 8003D03C 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2D840 8003D040 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2D844 8003D044 04000324 */  addiu      $v1, $zero, 0x4
    /* 2D848 8003D048 0D004292 */  lbu        $v0, 0xD($s2)
    /* 2D84C 8003D04C 4000E48C */  lw         $a0, 0x40($a3)
    /* 2D850 8003D050 0F004230 */  andi       $v0, $v0, 0xF
    /* 2D854 8003D054 06004314 */  bne        $v0, $v1, .L8003D070
    /* 2D858 8003D058 2130C002 */   addu      $a2, $s6, $zero
    /* 2D85C 8003D05C 3F00E580 */  lb         $a1, 0x3F($a3)
    /* 2D860 8003D060 C8D8828E */  lw         $v0, %lo(D_800ED8C8)($s4)
    /* 2D864 8003D064 80280500 */  sll        $a1, $a1, 2
    /* 2D868 8003D068 1DF40008 */  j          .L8003D074
    /* 2D86C 8003D06C 21284500 */   addu      $a1, $v0, $a1
  .L8003D070:
    /* 2D870 8003D070 C8D8858E */  lw         $a1, %lo(D_800ED8C8)($s4)
  .L8003D074:
    /* 2D874 8003D074 A6FD000C */  jal        func_8003F698
    /* 2D878 8003D078 00000000 */   nop
  .L8003D07C:
    /* 2D87C 8003D07C 09004292 */  lbu        $v0, 0x9($s2)
    /* 2D880 8003D080 01001026 */  addiu      $s0, $s0, 0x1
    /* 2D884 8003D084 2A100202 */  slt        $v0, $s0, $v0
    /* 2D888 8003D088 6DFF4014 */  bnez       $v0, .L8003CE40
    /* 2D88C 8003D08C 00000000 */   nop
  .L8003D090:
    /* 2D890 8003D090 3000BF8F */  lw         $ra, 0x30($sp)
    /* 2D894 8003D094 2C00B78F */  lw         $s7, 0x2C($sp)
    /* 2D898 8003D098 2800B68F */  lw         $s6, 0x28($sp)
    /* 2D89C 8003D09C 2400B58F */  lw         $s5, 0x24($sp)
    /* 2D8A0 8003D0A0 2000B48F */  lw         $s4, 0x20($sp)
    /* 2D8A4 8003D0A4 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2D8A8 8003D0A8 1800B28F */  lw         $s2, 0x18($sp)
    /* 2D8AC 8003D0AC 1400B18F */  lw         $s1, 0x14($sp)
    /* 2D8B0 8003D0B0 1000B08F */  lw         $s0, 0x10($sp)
    /* 2D8B4 8003D0B4 0800E003 */  jr         $ra
    /* 2D8B8 8003D0B8 3800BD27 */   addiu     $sp, $sp, 0x38
endlabel func_8003CDD8
