.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80079DDC, 0x1B4

glabel func_80079DDC
    /* 6A5DC 80079DDC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 6A5E0 80079DE0 0F800A3C */  lui        $t2, %hi(D_800E80A0)
    /* 6A5E4 80079DE4 A080488D */  lw         $t0, %lo(D_800E80A0)($t2)
    /* 6A5E8 80079DE8 21488000 */  addu       $t1, $a0, $zero
    /* 6A5EC 80079DEC 61000011 */  beqz       $t0, .L80079F74
    /* 6A5F0 80079DF0 1000BFAF */   sw        $ra, 0x10($sp)
    /* 6A5F4 80079DF4 0E80033C */  lui        $v1, %hi(D_800E7E7D)
    /* 6A5F8 80079DF8 7D7E6290 */  lbu        $v0, %lo(D_800E7E7D)($v1)
    /* 6A5FC 80079DFC 2400048D */  lw         $a0, 0x24($t0)
    /* 6A600 80079E00 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 6A604 80079E04 7D7E62A0 */  sb         $v0, %lo(D_800E7E7D)($v1)
    /* 6A608 80079E08 01000224 */  addiu      $v0, $zero, 0x1
    /* 6A60C 80079E0C 0B00E210 */  beq        $a3, $v0, .L80079E3C
    /* 6A610 80079E10 A08044AD */   sw        $a0, %lo(D_800E80A0)($t2)
    /* 6A614 80079E14 0200E228 */  slti       $v0, $a3, 0x2
    /* 6A618 80079E18 04004014 */  bnez       $v0, .L80079E2C
    /* 6A61C 80079E1C 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
    /* 6A620 80079E20 02000224 */  addiu      $v0, $zero, 0x2
    /* 6A624 80079E24 0A00E210 */  beq        $a3, $v0, .L80079E50
    /* 6A628 80079E28 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
  .L80079E2C:
    /* 6A62C 80079E2C 68B14424 */  addiu      $a0, $v0, %lo(g_InactiveEntitiesList)
    /* 6A630 80079E30 0F80023C */  lui        $v0, %hi(D_800F23A8)
    /* 6A634 80079E34 98E70108 */  j          .L80079E60
    /* 6A638 80079E38 A8234324 */   addiu     $v1, $v0, %lo(D_800F23A8)
  .L80079E3C:
    /* 6A63C 80079E3C 0F80023C */  lui        $v0, %hi(g_ActiveEntitiesList)
    /* 6A640 80079E40 24264424 */  addiu      $a0, $v0, %lo(g_ActiveEntitiesList)
    /* 6A644 80079E44 0F80023C */  lui        $v0, %hi(D_800F239C)
    /* 6A648 80079E48 98E70108 */  j          .L80079E60
    /* 6A64C 80079E4C 9C234324 */   addiu     $v1, $v0, %lo(D_800F239C)
  .L80079E50:
    /* 6A650 80079E50 0F80023C */  lui        $v0, %hi(g_BackgroundEntitiesList)
    /* 6A654 80079E54 38274424 */  addiu      $a0, $v0, %lo(g_BackgroundEntitiesList)
    /* 6A658 80079E58 0F80023C */  lui        $v0, %hi(D_800F23A0)
    /* 6A65C 80079E5C A0234324 */  addiu      $v1, $v0, %lo(D_800F23A0)
  .L80079E60:
    /* 6A660 80079E60 01000224 */  addiu      $v0, $zero, 0x1
    /* 6A664 80079E64 1800C210 */  beq        $a2, $v0, .L80079EC8
    /* 6A668 80079E68 0200C228 */   slti      $v0, $a2, 0x2
    /* 6A66C 80079E6C 05004010 */  beqz       $v0, .L80079E84
    /* 6A670 80079E70 02000224 */   addiu     $v0, $zero, 0x2
    /* 6A674 80079E74 0900C010 */  beqz       $a2, .L80079E9C
    /* 6A678 80079E78 21100001 */   addu      $v0, $t0, $zero
    /* 6A67C 80079E7C D9E70108 */  j          .L80079F64
    /* 6A680 80079E80 02000324 */   addiu     $v1, $zero, 0x2
  .L80079E84:
    /* 6A684 80079E84 1D00C210 */  beq        $a2, $v0, .L80079EFC
    /* 6A688 80079E88 03000224 */   addiu     $v0, $zero, 0x3
    /* 6A68C 80079E8C 2800C210 */  beq        $a2, $v0, .L80079F30
    /* 6A690 80079E90 21100001 */   addu      $v0, $t0, $zero
    /* 6A694 80079E94 D9E70108 */  j          .L80079F64
    /* 6A698 80079E98 02000324 */   addiu     $v1, $zero, 0x2
  .L80079E9C:
    /* 6A69C 80079E9C 2000228D */  lw         $v0, 0x20($t1)
    /* 6A6A0 80079EA0 00000000 */  nop
    /* 6A6A4 80079EA4 08004010 */  beqz       $v0, .L80079EC8
    /* 6A6A8 80079EA8 00000000 */   nop
    /* 6A6AC 80079EAC 200002AD */  sw         $v0, 0x20($t0)
    /* 6A6B0 80079EB0 240009AD */  sw         $t1, 0x24($t0)
    /* 6A6B4 80079EB4 2000228D */  lw         $v0, 0x20($t1)
    /* 6A6B8 80079EB8 00000000 */  nop
    /* 6A6BC 80079EBC 240048AC */  sw         $t0, 0x24($v0)
    /* 6A6C0 80079EC0 D7E70108 */  j          .L80079F5C
    /* 6A6C4 80079EC4 200028AD */   sw        $t0, 0x20($t1)
  .L80079EC8:
    /* 6A6C8 80079EC8 200000AD */  sw         $zero, 0x20($t0)
    /* 6A6CC 80079ECC 0000828C */  lw         $v0, 0x0($a0)
    /* 6A6D0 80079ED0 00000000 */  nop
    /* 6A6D4 80079ED4 240002AD */  sw         $v0, 0x24($t0)
    /* 6A6D8 80079ED8 0000828C */  lw         $v0, 0x0($a0)
    /* 6A6DC 80079EDC 00000000 */  nop
    /* 6A6E0 80079EE0 03004014 */  bnez       $v0, .L80079EF0
    /* 6A6E4 80079EE4 00000000 */   nop
    /* 6A6E8 80079EE8 BDE70108 */  j          .L80079EF4
    /* 6A6EC 80079EEC 000068AC */   sw        $t0, 0x0($v1)
  .L80079EF0:
    /* 6A6F0 80079EF0 200048AC */  sw         $t0, 0x20($v0)
  .L80079EF4:
    /* 6A6F4 80079EF4 D7E70108 */  j          .L80079F5C
    /* 6A6F8 80079EF8 000088AC */   sw        $t0, 0x0($a0)
  .L80079EFC:
    /* 6A6FC 80079EFC 2400228D */  lw         $v0, 0x24($t1)
    /* 6A700 80079F00 00000000 */  nop
    /* 6A704 80079F04 0A004010 */  beqz       $v0, .L80079F30
    /* 6A708 80079F08 00000000 */   nop
    /* 6A70C 80079F0C 200009AD */  sw         $t1, 0x20($t0)
    /* 6A710 80079F10 2400228D */  lw         $v0, 0x24($t1)
    /* 6A714 80079F14 00000000 */  nop
    /* 6A718 80079F18 240002AD */  sw         $v0, 0x24($t0)
    /* 6A71C 80079F1C 2400228D */  lw         $v0, 0x24($t1)
    /* 6A720 80079F20 00000000 */  nop
    /* 6A724 80079F24 200048AC */  sw         $t0, 0x20($v0)
    /* 6A728 80079F28 D7E70108 */  j          .L80079F5C
    /* 6A72C 80079F2C 240028AD */   sw        $t0, 0x24($t1)
  .L80079F30:
    /* 6A730 80079F30 0000628C */  lw         $v0, 0x0($v1)
    /* 6A734 80079F34 240000AD */  sw         $zero, 0x24($t0)
    /* 6A738 80079F38 200002AD */  sw         $v0, 0x20($t0)
    /* 6A73C 80079F3C 0000628C */  lw         $v0, 0x0($v1)
    /* 6A740 80079F40 00000000 */  nop
    /* 6A744 80079F44 03004014 */  bnez       $v0, .L80079F54
    /* 6A748 80079F48 00000000 */   nop
    /* 6A74C 80079F4C D6E70108 */  j          .L80079F58
    /* 6A750 80079F50 000088AC */   sw        $t0, 0x0($a0)
  .L80079F54:
    /* 6A754 80079F54 240048AC */  sw         $t0, 0x24($v0)
  .L80079F58:
    /* 6A758 80079F58 000068AC */  sw         $t0, 0x0($v1)
  .L80079F5C:
    /* 6A75C 80079F5C 21100001 */  addu       $v0, $t0, $zero
    /* 6A760 80079F60 02000324 */  addiu      $v1, $zero, 0x2
  .L80079F64:
    /* 6A764 80079F64 0A0047A0 */  sb         $a3, 0xA($v0)
    /* 6A768 80079F68 000043A0 */  sb         $v1, 0x0($v0)
    /* 6A76C 80079F6C E0E70108 */  j          .L80079F80
    /* 6A770 80079F70 0C0045A0 */   sb        $a1, 0xC($v0)
  .L80079F74:
    /* 6A774 80079F74 21202001 */  addu       $a0, $t1, $zero
    /* 6A778 80079F78 E4E7010C */  jal        func_80079F90
    /* 6A77C 80079F7C FF00A530 */   andi      $a1, $a1, 0xFF
  .L80079F80:
    /* 6A780 80079F80 1000BF8F */  lw         $ra, 0x10($sp)
    /* 6A784 80079F84 00000000 */  nop
    /* 6A788 80079F88 0800E003 */  jr         $ra
    /* 6A78C 80079F8C 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel func_80079DDC

nonmatching func_80079F90, 0x19C

glabel func_80079F90
    /* 6A790 80079F90 0F800A3C */  lui        $t2, %hi(D_800F2398)
    /* 6A794 80079F94 9823488D */  lw         $t0, %lo(D_800F2398)($t2)
    /* 6A798 80079F98 00000000 */  nop
    /* 6A79C 80079F9C 61000011 */  beqz       $t0, .L8007A124
    /* 6A7A0 80079FA0 21488000 */   addu      $t1, $a0, $zero
    /* 6A7A4 80079FA4 0F80033C */  lui        $v1, %hi(D_800ED8CC)
    /* 6A7A8 80079FA8 CCD86290 */  lbu        $v0, %lo(D_800ED8CC)($v1)
    /* 6A7AC 80079FAC 2400048D */  lw         $a0, 0x24($t0)
    /* 6A7B0 80079FB0 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 6A7B4 80079FB4 CCD862A0 */  sb         $v0, %lo(D_800ED8CC)($v1)
    /* 6A7B8 80079FB8 01000224 */  addiu      $v0, $zero, 0x1
    /* 6A7BC 80079FBC 0B00E210 */  beq        $a3, $v0, .L80079FEC
    /* 6A7C0 80079FC0 982344AD */   sw        $a0, %lo(D_800F2398)($t2)
    /* 6A7C4 80079FC4 0200E228 */  slti       $v0, $a3, 0x2
    /* 6A7C8 80079FC8 04004014 */  bnez       $v0, .L80079FDC
    /* 6A7CC 80079FCC 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
    /* 6A7D0 80079FD0 02000224 */  addiu      $v0, $zero, 0x2
    /* 6A7D4 80079FD4 0A00E210 */  beq        $a3, $v0, .L8007A000
    /* 6A7D8 80079FD8 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
  .L80079FDC:
    /* 6A7DC 80079FDC 68B14424 */  addiu      $a0, $v0, %lo(g_InactiveEntitiesList)
    /* 6A7E0 80079FE0 0F80023C */  lui        $v0, %hi(D_800F23A8)
    /* 6A7E4 80079FE4 04E80108 */  j          .L8007A010
    /* 6A7E8 80079FE8 A8234324 */   addiu     $v1, $v0, %lo(D_800F23A8)
  .L80079FEC:
    /* 6A7EC 80079FEC 0F80023C */  lui        $v0, %hi(g_ActiveEntitiesList)
    /* 6A7F0 80079FF0 24264424 */  addiu      $a0, $v0, %lo(g_ActiveEntitiesList)
    /* 6A7F4 80079FF4 0F80023C */  lui        $v0, %hi(D_800F239C)
    /* 6A7F8 80079FF8 04E80108 */  j          .L8007A010
    /* 6A7FC 80079FFC 9C234324 */   addiu     $v1, $v0, %lo(D_800F239C)
  .L8007A000:
    /* 6A800 8007A000 0F80023C */  lui        $v0, %hi(g_BackgroundEntitiesList)
    /* 6A804 8007A004 38274424 */  addiu      $a0, $v0, %lo(g_BackgroundEntitiesList)
    /* 6A808 8007A008 0F80023C */  lui        $v0, %hi(D_800F23A0)
    /* 6A80C 8007A00C A0234324 */  addiu      $v1, $v0, %lo(D_800F23A0)
  .L8007A010:
    /* 6A810 8007A010 01000224 */  addiu      $v0, $zero, 0x1
    /* 6A814 8007A014 1800C210 */  beq        $a2, $v0, .L8007A078
    /* 6A818 8007A018 0200C228 */   slti      $v0, $a2, 0x2
    /* 6A81C 8007A01C 05004010 */  beqz       $v0, .L8007A034
    /* 6A820 8007A020 02000224 */   addiu     $v0, $zero, 0x2
    /* 6A824 8007A024 0900C010 */  beqz       $a2, .L8007A04C
    /* 6A828 8007A028 21100001 */   addu      $v0, $t0, $zero
    /* 6A82C 8007A02C 45E80108 */  j          .L8007A114
    /* 6A830 8007A030 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A034:
    /* 6A834 8007A034 1D00C210 */  beq        $a2, $v0, .L8007A0AC
    /* 6A838 8007A038 03000224 */   addiu     $v0, $zero, 0x3
    /* 6A83C 8007A03C 2800C210 */  beq        $a2, $v0, .L8007A0E0
    /* 6A840 8007A040 21100001 */   addu      $v0, $t0, $zero
    /* 6A844 8007A044 45E80108 */  j          .L8007A114
    /* 6A848 8007A048 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A04C:
    /* 6A84C 8007A04C 2000228D */  lw         $v0, 0x20($t1)
    /* 6A850 8007A050 00000000 */  nop
    /* 6A854 8007A054 08004010 */  beqz       $v0, .L8007A078
    /* 6A858 8007A058 00000000 */   nop
    /* 6A85C 8007A05C 200002AD */  sw         $v0, 0x20($t0)
    /* 6A860 8007A060 240009AD */  sw         $t1, 0x24($t0)
    /* 6A864 8007A064 2000228D */  lw         $v0, 0x20($t1)
    /* 6A868 8007A068 00000000 */  nop
    /* 6A86C 8007A06C 240048AC */  sw         $t0, 0x24($v0)
    /* 6A870 8007A070 43E80108 */  j          .L8007A10C
    /* 6A874 8007A074 200028AD */   sw        $t0, 0x20($t1)
  .L8007A078:
    /* 6A878 8007A078 200000AD */  sw         $zero, 0x20($t0)
    /* 6A87C 8007A07C 0000828C */  lw         $v0, 0x0($a0)
    /* 6A880 8007A080 00000000 */  nop
    /* 6A884 8007A084 240002AD */  sw         $v0, 0x24($t0)
    /* 6A888 8007A088 0000828C */  lw         $v0, 0x0($a0)
    /* 6A88C 8007A08C 00000000 */  nop
    /* 6A890 8007A090 03004014 */  bnez       $v0, .L8007A0A0
    /* 6A894 8007A094 00000000 */   nop
    /* 6A898 8007A098 29E80108 */  j          .L8007A0A4
    /* 6A89C 8007A09C 000068AC */   sw        $t0, 0x0($v1)
  .L8007A0A0:
    /* 6A8A0 8007A0A0 200048AC */  sw         $t0, 0x20($v0)
  .L8007A0A4:
    /* 6A8A4 8007A0A4 43E80108 */  j          .L8007A10C
    /* 6A8A8 8007A0A8 000088AC */   sw        $t0, 0x0($a0)
  .L8007A0AC:
    /* 6A8AC 8007A0AC 2400228D */  lw         $v0, 0x24($t1)
    /* 6A8B0 8007A0B0 00000000 */  nop
    /* 6A8B4 8007A0B4 0A004010 */  beqz       $v0, .L8007A0E0
    /* 6A8B8 8007A0B8 00000000 */   nop
    /* 6A8BC 8007A0BC 200009AD */  sw         $t1, 0x20($t0)
    /* 6A8C0 8007A0C0 2400228D */  lw         $v0, 0x24($t1)
    /* 6A8C4 8007A0C4 00000000 */  nop
    /* 6A8C8 8007A0C8 240002AD */  sw         $v0, 0x24($t0)
    /* 6A8CC 8007A0CC 2400228D */  lw         $v0, 0x24($t1)
    /* 6A8D0 8007A0D0 00000000 */  nop
    /* 6A8D4 8007A0D4 200048AC */  sw         $t0, 0x20($v0)
    /* 6A8D8 8007A0D8 43E80108 */  j          .L8007A10C
    /* 6A8DC 8007A0DC 240028AD */   sw        $t0, 0x24($t1)
  .L8007A0E0:
    /* 6A8E0 8007A0E0 0000628C */  lw         $v0, 0x0($v1)
    /* 6A8E4 8007A0E4 240000AD */  sw         $zero, 0x24($t0)
    /* 6A8E8 8007A0E8 200002AD */  sw         $v0, 0x20($t0)
    /* 6A8EC 8007A0EC 0000628C */  lw         $v0, 0x0($v1)
    /* 6A8F0 8007A0F0 00000000 */  nop
    /* 6A8F4 8007A0F4 03004014 */  bnez       $v0, .L8007A104
    /* 6A8F8 8007A0F8 00000000 */   nop
    /* 6A8FC 8007A0FC 42E80108 */  j          .L8007A108
    /* 6A900 8007A100 000088AC */   sw        $t0, 0x0($a0)
  .L8007A104:
    /* 6A904 8007A104 240048AC */  sw         $t0, 0x24($v0)
  .L8007A108:
    /* 6A908 8007A108 000068AC */  sw         $t0, 0x0($v1)
  .L8007A10C:
    /* 6A90C 8007A10C 21100001 */  addu       $v0, $t0, $zero
    /* 6A910 8007A110 02000324 */  addiu      $v1, $zero, 0x2
  .L8007A114:
    /* 6A914 8007A114 0A0047A0 */  sb         $a3, 0xA($v0)
    /* 6A918 8007A118 000043A0 */  sb         $v1, 0x0($v0)
    /* 6A91C 8007A11C 0800E003 */  jr         $ra
    /* 6A920 8007A120 0C0045A0 */   sb        $a1, 0xC($v0)
  .L8007A124:
    /* 6A924 8007A124 0800E003 */  jr         $ra
    /* 6A928 8007A128 21100000 */   addu      $v0, $zero, $zero
endlabel func_80079F90

nonmatching func_8007A12C, 0x19C

glabel func_8007A12C
    /* 6A92C 8007A12C 0F800A3C */  lui        $t2, %hi(D_800ED8D4)
    /* 6A930 8007A130 D4D8488D */  lw         $t0, %lo(D_800ED8D4)($t2)
    /* 6A934 8007A134 00000000 */  nop
    /* 6A938 8007A138 61000011 */  beqz       $t0, .L8007A2C0
    /* 6A93C 8007A13C 21488000 */   addu      $t1, $a0, $zero
    /* 6A940 8007A140 0F80033C */  lui        $v1, %hi(D_800ED8C5)
    /* 6A944 8007A144 C5D86290 */  lbu        $v0, %lo(D_800ED8C5)($v1)
    /* 6A948 8007A148 2400048D */  lw         $a0, 0x24($t0)
    /* 6A94C 8007A14C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 6A950 8007A150 C5D862A0 */  sb         $v0, %lo(D_800ED8C5)($v1)
    /* 6A954 8007A154 01000224 */  addiu      $v0, $zero, 0x1
    /* 6A958 8007A158 0B00E210 */  beq        $a3, $v0, .L8007A188
    /* 6A95C 8007A15C D4D844AD */   sw        $a0, %lo(D_800ED8D4)($t2)
    /* 6A960 8007A160 0200E228 */  slti       $v0, $a3, 0x2
    /* 6A964 8007A164 04004014 */  bnez       $v0, .L8007A178
    /* 6A968 8007A168 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
    /* 6A96C 8007A16C 02000224 */  addiu      $v0, $zero, 0x2
    /* 6A970 8007A170 0A00E210 */  beq        $a3, $v0, .L8007A19C
    /* 6A974 8007A174 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
  .L8007A178:
    /* 6A978 8007A178 68B14424 */  addiu      $a0, $v0, %lo(g_InactiveEntitiesList)
    /* 6A97C 8007A17C 0F80023C */  lui        $v0, %hi(D_800F23A8)
    /* 6A980 8007A180 6BE80108 */  j          .L8007A1AC
    /* 6A984 8007A184 A8234324 */   addiu     $v1, $v0, %lo(D_800F23A8)
  .L8007A188:
    /* 6A988 8007A188 0F80023C */  lui        $v0, %hi(g_ActiveEntitiesList)
    /* 6A98C 8007A18C 24264424 */  addiu      $a0, $v0, %lo(g_ActiveEntitiesList)
    /* 6A990 8007A190 0F80023C */  lui        $v0, %hi(D_800F239C)
    /* 6A994 8007A194 6BE80108 */  j          .L8007A1AC
    /* 6A998 8007A198 9C234324 */   addiu     $v1, $v0, %lo(D_800F239C)
  .L8007A19C:
    /* 6A99C 8007A19C 0F80023C */  lui        $v0, %hi(g_BackgroundEntitiesList)
    /* 6A9A0 8007A1A0 38274424 */  addiu      $a0, $v0, %lo(g_BackgroundEntitiesList)
    /* 6A9A4 8007A1A4 0F80023C */  lui        $v0, %hi(D_800F23A0)
    /* 6A9A8 8007A1A8 A0234324 */  addiu      $v1, $v0, %lo(D_800F23A0)
  .L8007A1AC:
    /* 6A9AC 8007A1AC 01000224 */  addiu      $v0, $zero, 0x1
    /* 6A9B0 8007A1B0 1800C210 */  beq        $a2, $v0, .L8007A214
    /* 6A9B4 8007A1B4 0200C228 */   slti      $v0, $a2, 0x2
    /* 6A9B8 8007A1B8 05004010 */  beqz       $v0, .L8007A1D0
    /* 6A9BC 8007A1BC 02000224 */   addiu     $v0, $zero, 0x2
    /* 6A9C0 8007A1C0 0900C010 */  beqz       $a2, .L8007A1E8
    /* 6A9C4 8007A1C4 21100001 */   addu      $v0, $t0, $zero
    /* 6A9C8 8007A1C8 ACE80108 */  j          .L8007A2B0
    /* 6A9CC 8007A1CC 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A1D0:
    /* 6A9D0 8007A1D0 1D00C210 */  beq        $a2, $v0, .L8007A248
    /* 6A9D4 8007A1D4 03000224 */   addiu     $v0, $zero, 0x3
    /* 6A9D8 8007A1D8 2800C210 */  beq        $a2, $v0, .L8007A27C
    /* 6A9DC 8007A1DC 21100001 */   addu      $v0, $t0, $zero
    /* 6A9E0 8007A1E0 ACE80108 */  j          .L8007A2B0
    /* 6A9E4 8007A1E4 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A1E8:
    /* 6A9E8 8007A1E8 2000228D */  lw         $v0, 0x20($t1)
    /* 6A9EC 8007A1EC 00000000 */  nop
    /* 6A9F0 8007A1F0 08004010 */  beqz       $v0, .L8007A214
    /* 6A9F4 8007A1F4 00000000 */   nop
    /* 6A9F8 8007A1F8 200002AD */  sw         $v0, 0x20($t0)
    /* 6A9FC 8007A1FC 240009AD */  sw         $t1, 0x24($t0)
    /* 6AA00 8007A200 2000228D */  lw         $v0, 0x20($t1)
    /* 6AA04 8007A204 00000000 */  nop
    /* 6AA08 8007A208 240048AC */  sw         $t0, 0x24($v0)
    /* 6AA0C 8007A20C AAE80108 */  j          .L8007A2A8
    /* 6AA10 8007A210 200028AD */   sw        $t0, 0x20($t1)
  .L8007A214:
    /* 6AA14 8007A214 200000AD */  sw         $zero, 0x20($t0)
    /* 6AA18 8007A218 0000828C */  lw         $v0, 0x0($a0)
    /* 6AA1C 8007A21C 00000000 */  nop
    /* 6AA20 8007A220 240002AD */  sw         $v0, 0x24($t0)
    /* 6AA24 8007A224 0000828C */  lw         $v0, 0x0($a0)
    /* 6AA28 8007A228 00000000 */  nop
    /* 6AA2C 8007A22C 03004014 */  bnez       $v0, .L8007A23C
    /* 6AA30 8007A230 00000000 */   nop
    /* 6AA34 8007A234 90E80108 */  j          .L8007A240
    /* 6AA38 8007A238 000068AC */   sw        $t0, 0x0($v1)
  .L8007A23C:
    /* 6AA3C 8007A23C 200048AC */  sw         $t0, 0x20($v0)
  .L8007A240:
    /* 6AA40 8007A240 AAE80108 */  j          .L8007A2A8
    /* 6AA44 8007A244 000088AC */   sw        $t0, 0x0($a0)
  .L8007A248:
    /* 6AA48 8007A248 2400228D */  lw         $v0, 0x24($t1)
    /* 6AA4C 8007A24C 00000000 */  nop
    /* 6AA50 8007A250 0A004010 */  beqz       $v0, .L8007A27C
    /* 6AA54 8007A254 00000000 */   nop
    /* 6AA58 8007A258 200009AD */  sw         $t1, 0x20($t0)
    /* 6AA5C 8007A25C 2400228D */  lw         $v0, 0x24($t1)
    /* 6AA60 8007A260 00000000 */  nop
    /* 6AA64 8007A264 240002AD */  sw         $v0, 0x24($t0)
    /* 6AA68 8007A268 2400228D */  lw         $v0, 0x24($t1)
    /* 6AA6C 8007A26C 00000000 */  nop
    /* 6AA70 8007A270 200048AC */  sw         $t0, 0x20($v0)
    /* 6AA74 8007A274 AAE80108 */  j          .L8007A2A8
    /* 6AA78 8007A278 240028AD */   sw        $t0, 0x24($t1)
  .L8007A27C:
    /* 6AA7C 8007A27C 0000628C */  lw         $v0, 0x0($v1)
    /* 6AA80 8007A280 240000AD */  sw         $zero, 0x24($t0)
    /* 6AA84 8007A284 200002AD */  sw         $v0, 0x20($t0)
    /* 6AA88 8007A288 0000628C */  lw         $v0, 0x0($v1)
    /* 6AA8C 8007A28C 00000000 */  nop
    /* 6AA90 8007A290 03004014 */  bnez       $v0, .L8007A2A0
    /* 6AA94 8007A294 00000000 */   nop
    /* 6AA98 8007A298 A9E80108 */  j          .L8007A2A4
    /* 6AA9C 8007A29C 000088AC */   sw        $t0, 0x0($a0)
  .L8007A2A0:
    /* 6AAA0 8007A2A0 240048AC */  sw         $t0, 0x24($v0)
  .L8007A2A4:
    /* 6AAA4 8007A2A4 000068AC */  sw         $t0, 0x0($v1)
  .L8007A2A8:
    /* 6AAA8 8007A2A8 21100001 */  addu       $v0, $t0, $zero
    /* 6AAAC 8007A2AC 02000324 */  addiu      $v1, $zero, 0x2
  .L8007A2B0:
    /* 6AAB0 8007A2B0 0A0047A0 */  sb         $a3, 0xA($v0)
    /* 6AAB4 8007A2B4 000043A0 */  sb         $v1, 0x0($v0)
    /* 6AAB8 8007A2B8 0800E003 */  jr         $ra
    /* 6AABC 8007A2BC 0C0045A0 */   sb        $a1, 0xC($v0)
  .L8007A2C0:
    /* 6AAC0 8007A2C0 0800E003 */  jr         $ra
    /* 6AAC4 8007A2C4 21100000 */   addu      $v0, $zero, $zero
endlabel func_8007A12C

nonmatching func_8007A2C8, 0x19C

glabel func_8007A2C8
    /* 6AAC8 8007A2C8 0F800A3C */  lui        $t2, %hi(D_800ED8D0)
    /* 6AACC 8007A2CC D0D8488D */  lw         $t0, %lo(D_800ED8D0)($t2)
    /* 6AAD0 8007A2D0 00000000 */  nop
    /* 6AAD4 8007A2D4 61000011 */  beqz       $t0, .L8007A45C
    /* 6AAD8 8007A2D8 21488000 */   addu      $t1, $a0, $zero
    /* 6AADC 8007A2DC 0F80033C */  lui        $v1, %hi(D_800ED8C4)
    /* 6AAE0 8007A2E0 C4D86290 */  lbu        $v0, %lo(D_800ED8C4)($v1)
    /* 6AAE4 8007A2E4 2400048D */  lw         $a0, 0x24($t0)
    /* 6AAE8 8007A2E8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 6AAEC 8007A2EC C4D862A0 */  sb         $v0, %lo(D_800ED8C4)($v1)
    /* 6AAF0 8007A2F0 01000224 */  addiu      $v0, $zero, 0x1
    /* 6AAF4 8007A2F4 0B00E210 */  beq        $a3, $v0, .L8007A324
    /* 6AAF8 8007A2F8 D0D844AD */   sw        $a0, %lo(D_800ED8D0)($t2)
    /* 6AAFC 8007A2FC 0200E228 */  slti       $v0, $a3, 0x2
    /* 6AB00 8007A300 04004014 */  bnez       $v0, .L8007A314
    /* 6AB04 8007A304 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
    /* 6AB08 8007A308 02000224 */  addiu      $v0, $zero, 0x2
    /* 6AB0C 8007A30C 0A00E210 */  beq        $a3, $v0, .L8007A338
    /* 6AB10 8007A310 1080023C */   lui       $v0, %hi(g_InactiveEntitiesList)
  .L8007A314:
    /* 6AB14 8007A314 68B14424 */  addiu      $a0, $v0, %lo(g_InactiveEntitiesList)
    /* 6AB18 8007A318 0F80023C */  lui        $v0, %hi(D_800F23A8)
    /* 6AB1C 8007A31C D2E80108 */  j          .L8007A348
    /* 6AB20 8007A320 A8234324 */   addiu     $v1, $v0, %lo(D_800F23A8)
  .L8007A324:
    /* 6AB24 8007A324 0F80023C */  lui        $v0, %hi(g_ActiveEntitiesList)
    /* 6AB28 8007A328 24264424 */  addiu      $a0, $v0, %lo(g_ActiveEntitiesList)
    /* 6AB2C 8007A32C 0F80023C */  lui        $v0, %hi(D_800F239C)
    /* 6AB30 8007A330 D2E80108 */  j          .L8007A348
    /* 6AB34 8007A334 9C234324 */   addiu     $v1, $v0, %lo(D_800F239C)
  .L8007A338:
    /* 6AB38 8007A338 0F80023C */  lui        $v0, %hi(g_BackgroundEntitiesList)
    /* 6AB3C 8007A33C 38274424 */  addiu      $a0, $v0, %lo(g_BackgroundEntitiesList)
    /* 6AB40 8007A340 0F80023C */  lui        $v0, %hi(D_800F23A0)
    /* 6AB44 8007A344 A0234324 */  addiu      $v1, $v0, %lo(D_800F23A0)
  .L8007A348:
    /* 6AB48 8007A348 01000224 */  addiu      $v0, $zero, 0x1
    /* 6AB4C 8007A34C 1800C210 */  beq        $a2, $v0, .L8007A3B0
    /* 6AB50 8007A350 0200C228 */   slti      $v0, $a2, 0x2
    /* 6AB54 8007A354 05004010 */  beqz       $v0, .L8007A36C
    /* 6AB58 8007A358 02000224 */   addiu     $v0, $zero, 0x2
    /* 6AB5C 8007A35C 0900C010 */  beqz       $a2, .L8007A384
    /* 6AB60 8007A360 21100001 */   addu      $v0, $t0, $zero
    /* 6AB64 8007A364 13E90108 */  j          .L8007A44C
    /* 6AB68 8007A368 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A36C:
    /* 6AB6C 8007A36C 1D00C210 */  beq        $a2, $v0, .L8007A3E4
    /* 6AB70 8007A370 03000224 */   addiu     $v0, $zero, 0x3
    /* 6AB74 8007A374 2800C210 */  beq        $a2, $v0, .L8007A418
    /* 6AB78 8007A378 21100001 */   addu      $v0, $t0, $zero
    /* 6AB7C 8007A37C 13E90108 */  j          .L8007A44C
    /* 6AB80 8007A380 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A384:
    /* 6AB84 8007A384 2000228D */  lw         $v0, 0x20($t1)
    /* 6AB88 8007A388 00000000 */  nop
    /* 6AB8C 8007A38C 08004010 */  beqz       $v0, .L8007A3B0
    /* 6AB90 8007A390 00000000 */   nop
    /* 6AB94 8007A394 200002AD */  sw         $v0, 0x20($t0)
    /* 6AB98 8007A398 240009AD */  sw         $t1, 0x24($t0)
    /* 6AB9C 8007A39C 2000228D */  lw         $v0, 0x20($t1)
    /* 6ABA0 8007A3A0 00000000 */  nop
    /* 6ABA4 8007A3A4 240048AC */  sw         $t0, 0x24($v0)
    /* 6ABA8 8007A3A8 11E90108 */  j          .L8007A444
    /* 6ABAC 8007A3AC 200028AD */   sw        $t0, 0x20($t1)
  .L8007A3B0:
    /* 6ABB0 8007A3B0 200000AD */  sw         $zero, 0x20($t0)
    /* 6ABB4 8007A3B4 0000828C */  lw         $v0, 0x0($a0)
    /* 6ABB8 8007A3B8 00000000 */  nop
    /* 6ABBC 8007A3BC 240002AD */  sw         $v0, 0x24($t0)
    /* 6ABC0 8007A3C0 0000828C */  lw         $v0, 0x0($a0)
    /* 6ABC4 8007A3C4 00000000 */  nop
    /* 6ABC8 8007A3C8 03004014 */  bnez       $v0, .L8007A3D8
    /* 6ABCC 8007A3CC 00000000 */   nop
    /* 6ABD0 8007A3D0 F7E80108 */  j          .L8007A3DC
    /* 6ABD4 8007A3D4 000068AC */   sw        $t0, 0x0($v1)
  .L8007A3D8:
    /* 6ABD8 8007A3D8 200048AC */  sw         $t0, 0x20($v0)
  .L8007A3DC:
    /* 6ABDC 8007A3DC 11E90108 */  j          .L8007A444
    /* 6ABE0 8007A3E0 000088AC */   sw        $t0, 0x0($a0)
  .L8007A3E4:
    /* 6ABE4 8007A3E4 2400228D */  lw         $v0, 0x24($t1)
    /* 6ABE8 8007A3E8 00000000 */  nop
    /* 6ABEC 8007A3EC 0A004010 */  beqz       $v0, .L8007A418
    /* 6ABF0 8007A3F0 00000000 */   nop
    /* 6ABF4 8007A3F4 200009AD */  sw         $t1, 0x20($t0)
    /* 6ABF8 8007A3F8 2400228D */  lw         $v0, 0x24($t1)
    /* 6ABFC 8007A3FC 00000000 */  nop
    /* 6AC00 8007A400 240002AD */  sw         $v0, 0x24($t0)
    /* 6AC04 8007A404 2400228D */  lw         $v0, 0x24($t1)
    /* 6AC08 8007A408 00000000 */  nop
    /* 6AC0C 8007A40C 200048AC */  sw         $t0, 0x20($v0)
    /* 6AC10 8007A410 11E90108 */  j          .L8007A444
    /* 6AC14 8007A414 240028AD */   sw        $t0, 0x24($t1)
  .L8007A418:
    /* 6AC18 8007A418 0000628C */  lw         $v0, 0x0($v1)
    /* 6AC1C 8007A41C 240000AD */  sw         $zero, 0x24($t0)
    /* 6AC20 8007A420 200002AD */  sw         $v0, 0x20($t0)
    /* 6AC24 8007A424 0000628C */  lw         $v0, 0x0($v1)
    /* 6AC28 8007A428 00000000 */  nop
    /* 6AC2C 8007A42C 03004014 */  bnez       $v0, .L8007A43C
    /* 6AC30 8007A430 00000000 */   nop
    /* 6AC34 8007A434 10E90108 */  j          .L8007A440
    /* 6AC38 8007A438 000088AC */   sw        $t0, 0x0($a0)
  .L8007A43C:
    /* 6AC3C 8007A43C 240048AC */  sw         $t0, 0x24($v0)
  .L8007A440:
    /* 6AC40 8007A440 000068AC */  sw         $t0, 0x0($v1)
  .L8007A444:
    /* 6AC44 8007A444 21100001 */  addu       $v0, $t0, $zero
    /* 6AC48 8007A448 02000324 */  addiu      $v1, $zero, 0x2
  .L8007A44C:
    /* 6AC4C 8007A44C 0A0047A0 */  sb         $a3, 0xA($v0)
    /* 6AC50 8007A450 000043A0 */  sb         $v1, 0x0($v0)
    /* 6AC54 8007A454 0800E003 */  jr         $ra
    /* 6AC58 8007A458 0C0045A0 */   sb        $a1, 0xC($v0)
  .L8007A45C:
    /* 6AC5C 8007A45C 0800E003 */  jr         $ra
    /* 6AC60 8007A460 21100000 */   addu      $v0, $zero, $zero
endlabel func_8007A2C8

nonmatching func_8007A464, 0x144

glabel func_8007A464
    /* 6AC64 8007A464 0F80083C */  lui        $t0, %hi(D_800F273C)
    /* 6AC68 8007A468 3C27068D */  lw         $a2, %lo(D_800F273C)($t0)
    /* 6AC6C 8007A46C 00000000 */  nop
    /* 6AC70 8007A470 4B00C010 */  beqz       $a2, .L8007A5A0
    /* 6AC74 8007A474 21388000 */   addu      $a3, $a0, $zero
    /* 6AC78 8007A478 0F80033C */  lui        $v1, %hi(D_800F2410)
    /* 6AC7C 8007A47C 10246290 */  lbu        $v0, %lo(D_800F2410)($v1)
    /* 6AC80 8007A480 2400C48C */  lw         $a0, 0x24($a2)
    /* 6AC84 8007A484 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 6AC88 8007A488 102462A0 */  sb         $v0, %lo(D_800F2410)($v1)
    /* 6AC8C 8007A48C 0F80023C */  lui        $v0, %hi(g_BackgroundEntitiesList)
    /* 6AC90 8007A490 3C2704AD */  sw         $a0, %lo(D_800F273C)($t0)
    /* 6AC94 8007A494 38274824 */  addiu      $t0, $v0, %lo(g_BackgroundEntitiesList)
    /* 6AC98 8007A498 0F80023C */  lui        $v0, %hi(D_800F23A0)
    /* 6AC9C 8007A49C A0234424 */  addiu      $a0, $v0, %lo(D_800F23A0)
    /* 6ACA0 8007A4A0 01000224 */  addiu      $v0, $zero, 0x1
    /* 6ACA4 8007A4A4 1800A210 */  beq        $a1, $v0, .L8007A508
    /* 6ACA8 8007A4A8 0200A228 */   slti      $v0, $a1, 0x2
    /* 6ACAC 8007A4AC 05004010 */  beqz       $v0, .L8007A4C4
    /* 6ACB0 8007A4B0 02000224 */   addiu     $v0, $zero, 0x2
    /* 6ACB4 8007A4B4 0900A010 */  beqz       $a1, .L8007A4DC
    /* 6ACB8 8007A4B8 2110C000 */   addu      $v0, $a2, $zero
    /* 6ACBC 8007A4BC 64E90108 */  j          .L8007A590
    /* 6ACC0 8007A4C0 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A4C4:
    /* 6ACC4 8007A4C4 1A00A210 */  beq        $a1, $v0, .L8007A530
    /* 6ACC8 8007A4C8 03000224 */   addiu     $v0, $zero, 0x3
    /* 6ACCC 8007A4CC 2500A210 */  beq        $a1, $v0, .L8007A564
    /* 6ACD0 8007A4D0 2110C000 */   addu      $v0, $a2, $zero
    /* 6ACD4 8007A4D4 64E90108 */  j          .L8007A590
    /* 6ACD8 8007A4D8 02000324 */   addiu     $v1, $zero, 0x2
  .L8007A4DC:
    /* 6ACDC 8007A4DC 2000E28C */  lw         $v0, 0x20($a3)
    /* 6ACE0 8007A4E0 00000000 */  nop
    /* 6ACE4 8007A4E4 08004010 */  beqz       $v0, .L8007A508
    /* 6ACE8 8007A4E8 00000000 */   nop
    /* 6ACEC 8007A4EC 2000C2AC */  sw         $v0, 0x20($a2)
    /* 6ACF0 8007A4F0 2400C7AC */  sw         $a3, 0x24($a2)
    /* 6ACF4 8007A4F4 2000E28C */  lw         $v0, 0x20($a3)
    /* 6ACF8 8007A4F8 00000000 */  nop
    /* 6ACFC 8007A4FC 240046AC */  sw         $a2, 0x24($v0)
    /* 6AD00 8007A500 62E90108 */  j          .L8007A588
    /* 6AD04 8007A504 2000E6AC */   sw        $a2, 0x20($a3)
  .L8007A508:
    /* 6AD08 8007A508 0000028D */  lw         $v0, 0x0($t0)
    /* 6AD0C 8007A50C 2000C0AC */  sw         $zero, 0x20($a2)
    /* 6AD10 8007A510 21184000 */  addu       $v1, $v0, $zero
    /* 6AD14 8007A514 03006014 */  bnez       $v1, .L8007A524
    /* 6AD18 8007A518 2400C2AC */   sw        $v0, 0x24($a2)
    /* 6AD1C 8007A51C 4AE90108 */  j          .L8007A528
    /* 6AD20 8007A520 000086AC */   sw        $a2, 0x0($a0)
  .L8007A524:
    /* 6AD24 8007A524 200066AC */  sw         $a2, 0x20($v1)
  .L8007A528:
    /* 6AD28 8007A528 62E90108 */  j          .L8007A588
    /* 6AD2C 8007A52C 000006AD */   sw        $a2, 0x0($t0)
  .L8007A530:
    /* 6AD30 8007A530 2400E28C */  lw         $v0, 0x24($a3)
    /* 6AD34 8007A534 00000000 */  nop
    /* 6AD38 8007A538 0A004010 */  beqz       $v0, .L8007A564
    /* 6AD3C 8007A53C 00000000 */   nop
    /* 6AD40 8007A540 2000C7AC */  sw         $a3, 0x20($a2)
    /* 6AD44 8007A544 2400E28C */  lw         $v0, 0x24($a3)
    /* 6AD48 8007A548 00000000 */  nop
    /* 6AD4C 8007A54C 2400C2AC */  sw         $v0, 0x24($a2)
    /* 6AD50 8007A550 2400E28C */  lw         $v0, 0x24($a3)
    /* 6AD54 8007A554 00000000 */  nop
    /* 6AD58 8007A558 200046AC */  sw         $a2, 0x20($v0)
    /* 6AD5C 8007A55C 62E90108 */  j          .L8007A588
    /* 6AD60 8007A560 2400E6AC */   sw        $a2, 0x24($a3)
  .L8007A564:
    /* 6AD64 8007A564 0000828C */  lw         $v0, 0x0($a0)
    /* 6AD68 8007A568 2400C0AC */  sw         $zero, 0x24($a2)
    /* 6AD6C 8007A56C 21184000 */  addu       $v1, $v0, $zero
    /* 6AD70 8007A570 03006014 */  bnez       $v1, .L8007A580
    /* 6AD74 8007A574 2000C2AC */   sw        $v0, 0x20($a2)
    /* 6AD78 8007A578 61E90108 */  j          .L8007A584
    /* 6AD7C 8007A57C 000006AD */   sw        $a2, 0x0($t0)
  .L8007A580:
    /* 6AD80 8007A580 240066AC */  sw         $a2, 0x24($v1)
  .L8007A584:
    /* 6AD84 8007A584 000086AC */  sw         $a2, 0x0($a0)
  .L8007A588:
    /* 6AD88 8007A588 2110C000 */  addu       $v0, $a2, $zero
    /* 6AD8C 8007A58C 02000324 */  addiu      $v1, $zero, 0x2
  .L8007A590:
    /* 6AD90 8007A590 000043A0 */  sb         $v1, 0x0($v0)
    /* 6AD94 8007A594 01000324 */  addiu      $v1, $zero, 0x1
    /* 6AD98 8007A598 0800E003 */  jr         $ra
    /* 6AD9C 8007A59C 0C0043A0 */   sb        $v1, 0xC($v0)
  .L8007A5A0:
    /* 6ADA0 8007A5A0 0800E003 */  jr         $ra
    /* 6ADA4 8007A5A4 21100000 */   addu      $v0, $zero, $zero
endlabel func_8007A464

nonmatching func_8007A5A8, 0x7C

glabel func_8007A5A8
    /* 6ADA8 8007A5A8 0F80083C */  lui        $t0, %hi(D_800E8098)
    /* 6ADAC 8007A5AC 9880068D */  lw         $a2, %lo(D_800E8098)($t0)
    /* 6ADB0 8007A5B0 00000000 */  nop
    /* 6ADB4 8007A5B4 1900C010 */  beqz       $a2, .L8007A61C
    /* 6ADB8 8007A5B8 21488000 */   addu      $t1, $a0, $zero
    /* 6ADBC 8007A5BC 0E80033C */  lui        $v1, %hi(D_800E7E7C)
    /* 6ADC0 8007A5C0 0F80043C */  lui        $a0, %hi(D_800F239C)
    /* 6ADC4 8007A5C4 2400C58C */  lw         $a1, 0x24($a2)
    /* 6ADC8 8007A5C8 7C7E6290 */  lbu        $v0, %lo(D_800E7E7C)($v1)
    /* 6ADCC 8007A5CC 9C23878C */  lw         $a3, %lo(D_800F239C)($a0)
    /* 6ADD0 8007A5D0 9C238424 */  addiu      $a0, $a0, %lo(D_800F239C)
    /* 6ADD4 8007A5D4 2400C0AC */  sw         $zero, 0x24($a2)
    /* 6ADD8 8007A5D8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 6ADDC 8007A5DC 7C7E62A0 */  sb         $v0, %lo(D_800E7E7C)($v1)
    /* 6ADE0 8007A5E0 988005AD */  sw         $a1, %lo(D_800E8098)($t0)
    /* 6ADE4 8007A5E4 0400E014 */  bnez       $a3, .L8007A5F8
    /* 6ADE8 8007A5E8 2000C7AC */   sw        $a3, 0x20($a2)
    /* 6ADEC 8007A5EC 0F80023C */  lui        $v0, %hi(g_ActiveEntitiesList)
    /* 6ADF0 8007A5F0 7FE90108 */  j          .L8007A5FC
    /* 6ADF4 8007A5F4 242646AC */   sw        $a2, %lo(g_ActiveEntitiesList)($v0)
  .L8007A5F8:
    /* 6ADF8 8007A5F8 2400E6AC */  sw         $a2, 0x24($a3)
  .L8007A5FC:
    /* 6ADFC 8007A5FC 2110C000 */  addu       $v0, $a2, $zero
    /* 6AE00 8007A600 01000324 */  addiu      $v1, $zero, 0x1
    /* 6AE04 8007A604 000082AC */  sw         $v0, 0x0($a0)
    /* 6AE08 8007A608 0A0043A0 */  sb         $v1, 0xA($v0)
    /* 6AE0C 8007A60C 02000324 */  addiu      $v1, $zero, 0x2
    /* 6AE10 8007A610 000043A0 */  sb         $v1, 0x0($v0)
    /* 6AE14 8007A614 0800E003 */  jr         $ra
    /* 6AE18 8007A618 0C0049A0 */   sb        $t1, 0xC($v0)
  .L8007A61C:
    /* 6AE1C 8007A61C 0800E003 */  jr         $ra
    /* 6AE20 8007A620 21100000 */   addu      $v0, $zero, $zero
endlabel func_8007A5A8

nonmatching func_8007A624, 0x1EC

glabel func_8007A624
    /* 6AE24 8007A624 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 6AE28 8007A628 1000B0AF */  sw         $s0, 0x10($sp)
    /* 6AE2C 8007A62C 21808000 */  addu       $s0, $a0, $zero
    /* 6AE30 8007A630 1400BFAF */  sw         $ra, 0x14($sp)
    /* 6AE34 8007A634 0A000292 */  lbu        $v0, 0xA($s0)
    /* 6AE38 8007A638 00000000 */  nop
    /* 6AE3C 8007A63C 05004010 */  beqz       $v0, .L8007A654
    /* 6AE40 8007A640 0F80023C */   lui       $v0, %hi(g_ActiveEntitiesList)
    /* 6AE44 8007A644 24264424 */  addiu      $a0, $v0, %lo(g_ActiveEntitiesList)
    /* 6AE48 8007A648 0F80023C */  lui        $v0, %hi(D_800F239C)
    /* 6AE4C 8007A64C 99E90108 */  j          .L8007A664
    /* 6AE50 8007A650 9C234524 */   addiu     $a1, $v0, %lo(D_800F239C)
  .L8007A654:
    /* 6AE54 8007A654 1080023C */  lui        $v0, %hi(g_InactiveEntitiesList)
    /* 6AE58 8007A658 68B14424 */  addiu      $a0, $v0, %lo(g_InactiveEntitiesList)
    /* 6AE5C 8007A65C 0F80023C */  lui        $v0, %hi(D_800F23A8)
    /* 6AE60 8007A660 A8234524 */  addiu      $a1, $v0, %lo(D_800F23A8)
  .L8007A664:
    /* 6AE64 8007A664 2000038E */  lw         $v1, 0x20($s0)
    /* 6AE68 8007A668 00000000 */  nop
    /* 6AE6C 8007A66C 04006010 */  beqz       $v1, .L8007A680
    /* 6AE70 8007A670 00000000 */   nop
    /* 6AE74 8007A674 2400028E */  lw         $v0, 0x24($s0)
    /* 6AE78 8007A678 A8E90108 */  j          .L8007A6A0
    /* 6AE7C 8007A67C 240062AC */   sw        $v0, 0x24($v1)
  .L8007A680:
    /* 6AE80 8007A680 2400028E */  lw         $v0, 0x24($s0)
    /* 6AE84 8007A684 00000000 */  nop
    /* 6AE88 8007A688 000082AC */  sw         $v0, 0x0($a0)
    /* 6AE8C 8007A68C 2400028E */  lw         $v0, 0x24($s0)
    /* 6AE90 8007A690 00000000 */  nop
    /* 6AE94 8007A694 09004010 */  beqz       $v0, .L8007A6BC
    /* 6AE98 8007A698 00000000 */   nop
    /* 6AE9C 8007A69C 200040AC */  sw         $zero, 0x20($v0)
  .L8007A6A0:
    /* 6AEA0 8007A6A0 2400038E */  lw         $v1, 0x24($s0)
    /* 6AEA4 8007A6A4 00000000 */  nop
    /* 6AEA8 8007A6A8 04006010 */  beqz       $v1, .L8007A6BC
    /* 6AEAC 8007A6AC 00000000 */   nop
    /* 6AEB0 8007A6B0 2000028E */  lw         $v0, 0x20($s0)
    /* 6AEB4 8007A6B4 B7E90108 */  j          .L8007A6DC
    /* 6AEB8 8007A6B8 200062AC */   sw        $v0, 0x20($v1)
  .L8007A6BC:
    /* 6AEBC 8007A6BC 2000028E */  lw         $v0, 0x20($s0)
    /* 6AEC0 8007A6C0 00000000 */  nop
    /* 6AEC4 8007A6C4 0000A2AC */  sw         $v0, 0x0($a1)
    /* 6AEC8 8007A6C8 2000028E */  lw         $v0, 0x20($s0)
    /* 6AECC 8007A6CC 00000000 */  nop
    /* 6AED0 8007A6D0 02004010 */  beqz       $v0, .L8007A6DC
    /* 6AED4 8007A6D4 00000000 */   nop
    /* 6AED8 8007A6D8 240040AC */  sw         $zero, 0x24($v0)
  .L8007A6DC:
    /* 6AEDC 8007A6DC 28000292 */  lbu        $v0, 0x28($s0)
    /* 6AEE0 8007A6E0 00000000 */  nop
    /* 6AEE4 8007A6E4 7F004230 */  andi       $v0, $v0, 0x7F
    /* 6AEE8 8007A6E8 280002A2 */  sb         $v0, 0x28($s0)
    /* 6AEEC 8007A6EC FF004330 */  andi       $v1, $v0, 0xFF
    /* 6AEF0 8007A6F0 0500622C */  sltiu      $v0, $v1, 0x5
    /* 6AEF4 8007A6F4 36004010 */  beqz       $v0, .L8007A7D0
    /* 6AEF8 8007A6F8 0180023C */   lui       $v0, %hi(jtbl_80016E34)
    /* 6AEFC 8007A6FC 346E4224 */  addiu      $v0, $v0, %lo(jtbl_80016E34)
    /* 6AF00 8007A700 80180300 */  sll        $v1, $v1, 2
    /* 6AF04 8007A704 21186200 */  addu       $v1, $v1, $v0
    /* 6AF08 8007A708 0000628C */  lw         $v0, 0x0($v1)
    /* 6AF0C 8007A70C 00000000 */  nop
    /* 6AF10 8007A710 08004000 */  jr         $v0
    /* 6AF14 8007A714 00000000 */   nop
    /* 6AF18 8007A718 0E80043C */  lui        $a0, %hi(D_800E7E7C)
    /* 6AF1C 8007A71C 0F80033C */  lui        $v1, %hi(D_800E8098)
    /* 6AF20 8007A720 7C7E8290 */  lbu        $v0, %lo(D_800E7E7C)($a0)
    /* 6AF24 8007A724 9880658C */  lw         $a1, %lo(D_800E8098)($v1)
    /* 6AF28 8007A728 988070AC */  sw         $s0, %lo(D_800E8098)($v1)
    /* 6AF2C 8007A72C 01004224 */  addiu      $v0, $v0, 0x1
    /* 6AF30 8007A730 7C7E82A0 */  sb         $v0, %lo(D_800E7E7C)($a0)
    /* 6AF34 8007A734 F4E90108 */  j          .L8007A7D0
    /* 6AF38 8007A738 240005AE */   sw        $a1, 0x24($s0)
    /* 6AF3C 8007A73C 0E80053C */  lui        $a1, %hi(D_800E7E7D)
    /* 6AF40 8007A740 0F80033C */  lui        $v1, %hi(D_800E80A0)
    /* 6AF44 8007A744 7D7EA290 */  lbu        $v0, %lo(D_800E7E7D)($a1)
    /* 6AF48 8007A748 A080668C */  lw         $a2, %lo(D_800E80A0)($v1)
    /* 6AF4C 8007A74C 21200002 */  addu       $a0, $s0, $zero
    /* 6AF50 8007A750 A08070AC */  sw         $s0, %lo(D_800E80A0)($v1)
    /* 6AF54 8007A754 01004224 */  addiu      $v0, $v0, 0x1
    /* 6AF58 8007A758 F2E90108 */  j          .L8007A7C8
    /* 6AF5C 8007A75C 7D7EA2A0 */   sb        $v0, %lo(D_800E7E7D)($a1)
    /* 6AF60 8007A760 0F80053C */  lui        $a1, %hi(D_800ED8CC)
    /* 6AF64 8007A764 0F80033C */  lui        $v1, %hi(D_800F2398)
    /* 6AF68 8007A768 CCD8A290 */  lbu        $v0, %lo(D_800ED8CC)($a1)
    /* 6AF6C 8007A76C 9823668C */  lw         $a2, %lo(D_800F2398)($v1)
    /* 6AF70 8007A770 21200002 */  addu       $a0, $s0, $zero
    /* 6AF74 8007A774 982370AC */  sw         $s0, %lo(D_800F2398)($v1)
    /* 6AF78 8007A778 01004224 */  addiu      $v0, $v0, 0x1
    /* 6AF7C 8007A77C F2E90108 */  j          .L8007A7C8
    /* 6AF80 8007A780 CCD8A2A0 */   sb        $v0, %lo(D_800ED8CC)($a1)
    /* 6AF84 8007A784 0F80053C */  lui        $a1, %hi(D_800ED8C5)
    /* 6AF88 8007A788 0F80033C */  lui        $v1, %hi(D_800ED8D4)
    /* 6AF8C 8007A78C C5D8A290 */  lbu        $v0, %lo(D_800ED8C5)($a1)
    /* 6AF90 8007A790 D4D8668C */  lw         $a2, %lo(D_800ED8D4)($v1)
    /* 6AF94 8007A794 21200002 */  addu       $a0, $s0, $zero
    /* 6AF98 8007A798 D4D870AC */  sw         $s0, %lo(D_800ED8D4)($v1)
    /* 6AF9C 8007A79C 01004224 */  addiu      $v0, $v0, 0x1
    /* 6AFA0 8007A7A0 F2E90108 */  j          .L8007A7C8
    /* 6AFA4 8007A7A4 C5D8A2A0 */   sb        $v0, %lo(D_800ED8C5)($a1)
    /* 6AFA8 8007A7A8 0F80053C */  lui        $a1, %hi(D_800ED8C4)
    /* 6AFAC 8007A7AC 0F80033C */  lui        $v1, %hi(D_800ED8D0)
    /* 6AFB0 8007A7B0 C4D8A290 */  lbu        $v0, %lo(D_800ED8C4)($a1)
    /* 6AFB4 8007A7B4 D0D8668C */  lw         $a2, %lo(D_800ED8D0)($v1)
    /* 6AFB8 8007A7B8 21200002 */  addu       $a0, $s0, $zero
    /* 6AFBC 8007A7BC D0D870AC */  sw         $s0, %lo(D_800ED8D0)($v1)
    /* 6AFC0 8007A7C0 01004224 */  addiu      $v0, $v0, 0x1
    /* 6AFC4 8007A7C4 C4D8A2A0 */  sb         $v0, %lo(D_800ED8C4)($a1)
  .L8007A7C8:
    /* 6AFC8 8007A7C8 77EB010C */  jal        func_8007ADDC
    /* 6AFCC 8007A7CC 240006AE */   sw        $a2, 0x24($s0)
  .L8007A7D0:
    /* 6AFD0 8007A7D0 000000AE */  sw         $zero, 0x0($s0)
    /* 6AFD4 8007A7D4 040000AE */  sw         $zero, 0x4($s0)
    /* 6AFD8 8007A7D8 080000AE */  sw         $zero, 0x8($s0)
    /* 6AFDC 8007A7DC 0C0000AE */  sw         $zero, 0xC($s0)
    /* 6AFE0 8007A7E0 100000AE */  sw         $zero, 0x10($s0)
    /* 6AFE4 8007A7E4 140000AE */  sw         $zero, 0x14($s0)
    /* 6AFE8 8007A7E8 180000AE */  sw         $zero, 0x18($s0)
    /* 6AFEC 8007A7EC 380000AE */  sw         $zero, 0x38($s0)
    /* 6AFF0 8007A7F0 2A0000A2 */  sb         $zero, 0x2A($s0)
    /* 6AFF4 8007A7F4 2B0000A2 */  sb         $zero, 0x2B($s0)
    /* 6AFF8 8007A7F8 290000A2 */  sb         $zero, 0x29($s0)
    /* 6AFFC 8007A7FC 5E0000A2 */  sb         $zero, 0x5E($s0)
    /* 6B000 8007A800 1400BF8F */  lw         $ra, 0x14($sp)
    /* 6B004 8007A804 1000B08F */  lw         $s0, 0x10($sp)
    /* 6B008 8007A808 0800E003 */  jr         $ra
    /* 6B00C 8007A80C 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel func_8007A624

nonmatching func_8007A810, 0xD0

glabel func_8007A810
    /* 6B010 8007A810 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 6B014 8007A814 0E80043C */  lui        $a0, %hi(D_800E7E80)
    /* 6B018 8007A818 807E8424 */  addiu      $a0, $a0, %lo(D_800E7E80)
    /* 6B01C 8007A81C 21280000 */  addu       $a1, $zero, $zero
    /* 6B020 8007A820 84010624 */  addiu      $a2, $zero, 0x184
    /* 6B024 8007A824 2000BFAF */  sw         $ra, 0x20($sp)
    /* 6B028 8007A828 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 6B02C 8007A82C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 6B030 8007A830 1400B1AF */  sw         $s1, 0x14($sp)
    /* 6B034 8007A834 0869020C */  jal        func_8009A420
    /* 6B038 8007A838 1000B0AF */   sw        $s0, 0x10($sp)
    /* 6B03C 8007A83C 21880000 */  addu       $s1, $zero, $zero
    /* 6B040 8007A840 05001324 */  addiu      $s3, $zero, 0x5
    /* 6B044 8007A844 1080023C */  lui        $v0, %hi(D_80100690)
    /* 6B048 8007A848 90064224 */  addiu      $v0, $v0, %lo(D_80100690)
    /* 6B04C 8007A84C 08015224 */  addiu      $s2, $v0, 0x108
    /* 6B050 8007A850 21804000 */  addu       $s0, $v0, $zero
    /* 6B054 8007A854 0F80023C */  lui        $v0, %hi(g_BackgroundEntitiesList)
    /* 6B058 8007A858 382740AC */  sw         $zero, %lo(g_BackgroundEntitiesList)($v0)
    /* 6B05C 8007A85C 0F80023C */  lui        $v0, %hi(D_800F23A0)
    /* 6B060 8007A860 A02340AC */  sw         $zero, %lo(D_800F23A0)($v0)
  .L8007A864:
    /* 6B064 8007A864 21200002 */  addu       $a0, $s0, $zero
    /* 6B068 8007A868 21280000 */  addu       $a1, $zero, $zero
    /* 6B06C 8007A86C 0869020C */  jal        func_8009A420
    /* 6B070 8007A870 08010624 */   addiu     $a2, $zero, 0x108
    /* 6B074 8007A874 240012AE */  sw         $s2, 0x24($s0)
    /* 6B078 8007A878 08015226 */  addiu      $s2, $s2, 0x108
    /* 6B07C 8007A87C 280013A2 */  sb         $s3, 0x28($s0)
    /* 6B080 8007A880 01003126 */  addiu      $s1, $s1, 0x1
    /* 6B084 8007A884 0400222A */  slti       $v0, $s1, 0x4
    /* 6B088 8007A888 F6FF4014 */  bnez       $v0, .L8007A864
    /* 6B08C 8007A88C 08011026 */   addiu     $s0, $s0, 0x108
    /* 6B090 8007A890 1080043C */  lui        $a0, %hi(D_80100690)
    /* 6B094 8007A894 90068424 */  addiu      $a0, $a0, %lo(D_80100690)
    /* 6B098 8007A898 FFFF2326 */  addiu      $v1, $s1, -0x1
    /* 6B09C 8007A89C 40110300 */  sll        $v0, $v1, 5
    /* 6B0A0 8007A8A0 21104300 */  addu       $v0, $v0, $v1
    /* 6B0A4 8007A8A4 C0100200 */  sll        $v0, $v0, 3
    /* 6B0A8 8007A8A8 21104400 */  addu       $v0, $v0, $a0
    /* 6B0AC 8007A8AC 240040AC */  sw         $zero, 0x24($v0)
    /* 6B0B0 8007A8B0 0F80023C */  lui        $v0, %hi(D_800F273C)
    /* 6B0B4 8007A8B4 2000BF8F */  lw         $ra, 0x20($sp)
    /* 6B0B8 8007A8B8 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 6B0BC 8007A8BC 1800B28F */  lw         $s2, 0x18($sp)
    /* 6B0C0 8007A8C0 1400B18F */  lw         $s1, 0x14($sp)
    /* 6B0C4 8007A8C4 1000B08F */  lw         $s0, 0x10($sp)
    /* 6B0C8 8007A8C8 0F80033C */  lui        $v1, %hi(D_800F2410)
    /* 6B0CC 8007A8CC 3C2744AC */  sw         $a0, %lo(D_800F273C)($v0)
    /* 6B0D0 8007A8D0 04000224 */  addiu      $v0, $zero, 0x4
    /* 6B0D4 8007A8D4 102462A0 */  sb         $v0, %lo(D_800F2410)($v1)
    /* 6B0D8 8007A8D8 0800E003 */  jr         $ra
    /* 6B0DC 8007A8DC 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel func_8007A810

nonmatching func_8007A8E0, 0x24

glabel func_8007A8E0
    /* 6B0E0 8007A8E0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 6B0E4 8007A8E4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 6B0E8 8007A8E8 0BE6010C */  jal        func_8007982C
    /* 6B0EC 8007A8EC 00000000 */   nop
    /* 6B0F0 8007A8F0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 6B0F4 8007A8F4 801F023C */  lui        $v0, (0x1F80017C >> 16)
    /* 6B0F8 8007A8F8 7C0140A4 */  sh         $zero, (0x1F80017C & 0xFFFF)($v0)
    /* 6B0FC 8007A8FC 0800E003 */  jr         $ra
    /* 6B100 8007A900 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel func_8007A8E0

nonmatching func_8007A904, 0x7C

glabel func_8007A904
    /* 6B104 8007A904 1080023C */  lui        $v0, %hi(g_InactiveEntitiesList)
    /* 6B108 8007A908 68B1448C */  lw         $a0, %lo(g_InactiveEntitiesList)($v0)
    /* 6B10C 8007A90C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 6B110 8007A910 1400BFAF */  sw         $ra, 0x14($sp)
    /* 6B114 8007A914 09008010 */  beqz       $a0, .L8007A93C
    /* 6B118 8007A918 1000B0AF */   sw        $s0, 0x10($sp)
  .L8007A91C:
    /* 6B11C 8007A91C 2400908C */  lw         $s0, 0x24($a0)
    /* 6B120 8007A920 1C00828C */  lw         $v0, 0x1C($a0)
    /* 6B124 8007A924 00000000 */  nop
    /* 6B128 8007A928 09F84000 */  jalr       $v0
    /* 6B12C 8007A92C 010080A0 */   sb        $zero, 0x1($a0)
    /* 6B130 8007A930 21200002 */  addu       $a0, $s0, $zero
    /* 6B134 8007A934 F9FF8014 */  bnez       $a0, .L8007A91C
    /* 6B138 8007A938 00000000 */   nop
  .L8007A93C:
    /* 6B13C 8007A93C 0F80023C */  lui        $v0, %hi(g_ActiveEntitiesList)
    /* 6B140 8007A940 2426448C */  lw         $a0, %lo(g_ActiveEntitiesList)($v0)
    /* 6B144 8007A944 00000000 */  nop
    /* 6B148 8007A948 09008010 */  beqz       $a0, .L8007A970
    /* 6B14C 8007A94C 00000000 */   nop
  .L8007A950:
    /* 6B150 8007A950 2400908C */  lw         $s0, 0x24($a0)
    /* 6B154 8007A954 1C00828C */  lw         $v0, 0x1C($a0)
    /* 6B158 8007A958 00000000 */  nop
    /* 6B15C 8007A95C 09F84000 */  jalr       $v0
    /* 6B160 8007A960 010080A0 */   sb        $zero, 0x1($a0)
    /* 6B164 8007A964 21200002 */  addu       $a0, $s0, $zero
    /* 6B168 8007A968 F9FF8014 */  bnez       $a0, .L8007A950
    /* 6B16C 8007A96C 00000000 */   nop
  .L8007A970:
    /* 6B170 8007A970 1400BF8F */  lw         $ra, 0x14($sp)
    /* 6B174 8007A974 1000B08F */  lw         $s0, 0x10($sp)
    /* 6B178 8007A978 0800E003 */  jr         $ra
    /* 6B17C 8007A97C 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel func_8007A904
