.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_800313A0, 0xD0

glabel func_800313A0
    /* 21BA0 800313A0 0E80023C */  lui        $v0, %hi(D_800E7E7C)
    /* 21BA4 800313A4 7C7E4290 */  lbu        $v0, %lo(D_800E7E7C)($v0)
    /* 21BA8 800313A8 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 21BAC 800313AC 2000B4AF */  sw         $s4, 0x20($sp)
    /* 21BB0 800313B0 21A08000 */  addu       $s4, $a0, $zero
    /* 21BB4 800313B4 1400B1AF */  sw         $s1, 0x14($sp)
    /* 21BB8 800313B8 2188A000 */  addu       $s1, $a1, $zero
    /* 21BBC 800313BC 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 21BC0 800313C0 2198C000 */  addu       $s3, $a2, $zero
    /* 21BC4 800313C4 1800B2AF */  sw         $s2, 0x18($sp)
    /* 21BC8 800313C8 2190E000 */  addu       $s2, $a3, $zero
    /* 21BCC 800313CC 2400BFAF */  sw         $ra, 0x24($sp)
    /* 21BD0 800313D0 0700422C */  sltiu      $v0, $v0, 0x7
    /* 21BD4 800313D4 1D004014 */  bnez       $v0, .L8003144C
    /* 21BD8 800313D8 1000B0AF */   sw        $s0, 0x10($sp)
    /* 21BDC 800313DC 21200000 */  addu       $a0, $zero, $zero
    /* 21BE0 800313E0 06000524 */  addiu      $a1, $zero, 0x6
    /* 21BE4 800313E4 60EA010C */  jal        func_8007A980
    /* 21BE8 800313E8 01000624 */   addiu     $a2, $zero, 0x1
    /* 21BEC 800313EC 21804000 */  addu       $s0, $v0, $zero
    /* 21BF0 800313F0 16000012 */  beqz       $s0, .L8003144C
    /* 21BF4 800313F4 21200002 */   addu      $a0, $s0, $zero
    /* 21BF8 800313F8 02002296 */  lhu        $v0, 0x2($s1)
    /* 21BFC 800313FC 00000000 */  nop
    /* 21C00 80031400 2C0002A6 */  sh         $v0, 0x2C($s0)
    /* 21C04 80031404 06002296 */  lhu        $v0, 0x6($s1)
    /* 21C08 80031408 00000000 */  nop
    /* 21C0C 8003140C 2E0002A6 */  sh         $v0, 0x2E($s0)
    /* 21C10 80031410 0A002296 */  lhu        $v0, 0xA($s1)
    /* 21C14 80031414 320013A6 */  sh         $s3, 0x32($s0)
    /* 21C18 80031418 300002A6 */  sh         $v0, 0x30($s0)
    /* 21C1C 8003141C 00004296 */  lhu        $v0, 0x0($s2)
    /* 21C20 80031420 00000000 */  nop
    /* 21C24 80031424 480002A6 */  sh         $v0, 0x48($s0)
    /* 21C28 80031428 02004296 */  lhu        $v0, 0x2($s2)
    /* 21C2C 8003142C 00000000 */  nop
    /* 21C30 80031430 4A0002A6 */  sh         $v0, 0x4A($s0)
    /* 21C34 80031434 04004296 */  lhu        $v0, 0x4($s2)
    /* 21C38 80031438 21288002 */  addu       $a1, $s4, $zero
    /* 21C3C 8003143C 84A3000C */  jal        func_80028E10
    /* 21C40 80031440 4C0002A6 */   sh        $v0, 0x4C($s0)
    /* 21C44 80031444 14C50008 */  j          .L80031450
    /* 21C48 80031448 21100002 */   addu      $v0, $s0, $zero
  .L8003144C:
    /* 21C4C 8003144C 21100000 */  addu       $v0, $zero, $zero
  .L80031450:
    /* 21C50 80031450 2400BF8F */  lw         $ra, 0x24($sp)
    /* 21C54 80031454 2000B48F */  lw         $s4, 0x20($sp)
    /* 21C58 80031458 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 21C5C 8003145C 1800B28F */  lw         $s2, 0x18($sp)
    /* 21C60 80031460 1400B18F */  lw         $s1, 0x14($sp)
    /* 21C64 80031464 1000B08F */  lw         $s0, 0x10($sp)
    /* 21C68 80031468 0800E003 */  jr         $ra
    /* 21C6C 8003146C 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel func_800313A0
