.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8003E030, 0x234

glabel func_8003E030
    /* 2E830 8003E030 B8FFBD27 */  addiu      $sp, $sp, -0x48
    /* 2E834 8003E034 0A80023C */  lui        $v0, %hi(D_800A3B0C)
    /* 2E838 8003E038 0C3B4390 */  lbu        $v1, %lo(D_800A3B0C)($v0)
    /* 2E83C 8003E03C 02000224 */  addiu      $v0, $zero, 0x2
    /* 2E840 8003E040 4400BFAF */  sw         $ra, 0x44($sp)
    /* 2E844 8003E044 4000BEAF */  sw         $fp, 0x40($sp)
    /* 2E848 8003E048 3C00B7AF */  sw         $s7, 0x3C($sp)
    /* 2E84C 8003E04C 3800B6AF */  sw         $s6, 0x38($sp)
    /* 2E850 8003E050 3400B5AF */  sw         $s5, 0x34($sp)
    /* 2E854 8003E054 3000B4AF */  sw         $s4, 0x30($sp)
    /* 2E858 8003E058 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* 2E85C 8003E05C 2800B2AF */  sw         $s2, 0x28($sp)
    /* 2E860 8003E060 2400B1AF */  sw         $s1, 0x24($sp)
    /* 2E864 8003E064 73006214 */  bne        $v1, $v0, .L8003E234
    /* 2E868 8003E068 2000B0AF */   sw        $s0, 0x20($sp)
    /* 2E86C 8003E06C 801F023C */  lui        $v0, (0x1F800094 >> 16)
    /* 2E870 8003E070 9400428C */  lw         $v0, (0x1F800094 & 0xFFFF)($v0)
    /* 2E874 8003E074 80011124 */  addiu      $s1, $zero, 0x180
    /* 2E878 8003E078 18005100 */  mult       $v0, $s1
    /* 2E87C 8003E07C 0A80103C */  lui        $s0, %hi(D_800A3B10)
    /* 2E880 8003E080 0A80033C */  lui        $v1, %hi(D_800A3B14)
    /* 2E884 8003E084 103B048E */  lw         $a0, %lo(D_800A3B10)($s0)
    /* 2E888 8003E088 143B628C */  lw         $v0, %lo(D_800A3B14)($v1)
    /* 2E88C 8003E08C 88008424 */  addiu      $a0, $a0, 0x88
    /* 2E890 8003E090 103B04AE */  sw         $a0, %lo(D_800A3B10)($s0)
    /* 2E894 8003E094 20004224 */  addiu      $v0, $v0, 0x20
    /* 2E898 8003E098 143B62AC */  sw         $v0, %lo(D_800A3B14)($v1)
    /* 2E89C 8003E09C 12480000 */  mflo       $t1
    /* 2E8A0 8003E0A0 D40F020C */  jal        func_80083F50
    /* 2E8A4 8003E0A4 038A0900 */   sra       $s1, $t1, 8
    /* 2E8A8 8003E0A8 18005100 */  mult       $v0, $s1
    /* 2E8AC 8003E0AC 103B048E */  lw         $a0, %lo(D_800A3B10)($s0)
    /* 2E8B0 8003E0B0 12100000 */  mflo       $v0
    /* 2E8B4 8003E0B4 40180200 */  sll        $v1, $v0, 1
    /* 2E8B8 8003E0B8 21186200 */  addu       $v1, $v1, $v0
    /* 2E8BC 8003E0BC 831C0300 */  sra        $v1, $v1, 18
    /* 2E8C0 8003E0C0 A00F020C */  jal        func_80083E80
    /* 2E8C4 8003E0C4 1800A3A7 */   sh        $v1, 0x18($sp)
    /* 2E8C8 8003E0C8 18005100 */  mult       $v0, $s1
    /* 2E8CC 8003E0CC 21880000 */  addu       $s1, $zero, $zero
    /* 2E8D0 8003E0D0 0C80023C */  lui        $v0, %hi(D_800BF544)
    /* 2E8D4 8003E0D4 21984000 */  addu       $s3, $v0, $zero
    /* 2E8D8 8003E0D8 80001624 */  addiu      $s6, $zero, 0x80
    /* 2E8DC 8003E0DC FF00143C */  lui        $s4, (0xFFFFFF >> 16)
    /* 2E8E0 8003E0E0 FFFF9436 */  ori        $s4, $s4, (0xFFFFFF & 0xFFFF)
    /* 2E8E4 8003E0E4 00FF173C */  lui        $s7, (0xFF000000 >> 16)
    /* 2E8E8 8003E0E8 44F5708E */  lw         $s0, %lo(D_800BF544)($s3)
    /* 2E8EC 8003E0EC 21280000 */  addu       $a1, $zero, $zero
    /* 2E8F0 8003E0F0 21200002 */  addu       $a0, $s0, $zero
    /* 2E8F4 8003E0F4 12180000 */  mflo       $v1
    /* 2E8F8 8003E0F8 6C0F020C */  jal        func_80083DB0
    /* 2E8FC 8003E0FC 83F40300 */   sra       $fp, $v1, 18
    /* 2E900 8003E100 FF00063C */  lui        $a2, (0xFFFFFF >> 16)
    /* 2E904 8003E104 FFFFC634 */  ori        $a2, $a2, (0xFFFFFF & 0xFFFF)
    /* 2E908 8003E108 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2E90C 8003E10C 21A84000 */  addu       $s5, $v0, $zero
    /* 2E910 8003E110 2138E002 */  addu       $a3, $s7, $zero
    /* 2E914 8003E114 801F023C */  lui        $v0, (0x1F800135 >> 16)
    /* 2E918 8003E118 0000048E */  lw         $a0, 0x0($s0)
    /* 2E91C 8003E11C 35014390 */  lbu        $v1, (0x1F800135 & 0xFFFF)($v0)
    /* 2E920 8003E120 C8D8A58E */  lw         $a1, %lo(D_800ED8C8)($s5)
    /* 2E924 8003E124 24208700 */  and        $a0, $a0, $a3
    /* 2E928 8003E128 0100632C */  sltiu      $v1, $v1, 0x1
    /* 2E92C 8003E12C 0000A28C */  lw         $v0, 0x0($a1)
    /* 2E930 8003E130 00920300 */  sll        $s2, $v1, 8
    /* 2E934 8003E134 24104600 */  and        $v0, $v0, $a2
    /* 2E938 8003E138 25208200 */  or         $a0, $a0, $v0
    /* 2E93C 8003E13C 24300602 */  and        $a2, $s0, $a2
    /* 2E940 8003E140 000004AE */  sw         $a0, 0x0($s0)
    /* 2E944 8003E144 0000A28C */  lw         $v0, 0x0($a1)
    /* 2E948 8003E148 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2E94C 8003E14C 44F570AE */  sw         $s0, %lo(D_800BF544)($s3)
    /* 2E950 8003E150 24104700 */  and        $v0, $v0, $a3
    /* 2E954 8003E154 25104600 */  or         $v0, $v0, $a2
    /* 2E958 8003E158 0000A2AC */  sw         $v0, 0x0($a1)
  .L8003E15C:
    /* 2E95C 8003E15C 44F5708E */  lw         $s0, %lo(D_800BF544)($s3)
    /* 2E960 8003E160 00000000 */  nop
    /* 2E964 8003E164 060016A2 */  sb         $s6, 0x6($s0)
    /* 2E968 8003E168 050016A2 */  sb         $s6, 0x5($s0)
    /* 2E96C 8003E16C 040016A2 */  sb         $s6, 0x4($s0)
    /* 2E970 8003E170 1800A897 */  lhu        $t0, 0x18($sp)
    /* 2E974 8003E174 21200002 */  addu       $a0, $s0, $zero
    /* 2E978 8003E178 0A001EA6 */  sh         $fp, 0xA($s0)
    /* 2E97C 8003E17C 0D0000A2 */  sb         $zero, 0xD($s0)
    /* 2E980 8003E180 0C0000A2 */  sb         $zero, 0xC($s0)
    /* 2E984 8003E184 0E0000A6 */  sh         $zero, 0xE($s0)
    /* 2E988 8003E188 21102802 */  addu       $v0, $s1, $t0
    /* 2E98C 8003E18C 080002A6 */  sh         $v0, 0x8($s0)
    /* 2E990 8003E190 40000224 */  addiu      $v0, $zero, 0x40
    /* 2E994 8003E194 100002A6 */  sh         $v0, 0x10($s0)
    /* 2E998 8003E198 00010224 */  addiu      $v0, $zero, 0x100
    /* 2E99C 8003E19C 300F020C */  jal        func_80083CC0
    /* 2E9A0 8003E1A0 120002A6 */   sh        $v0, 0x12($s0)
    /* 2E9A4 8003E1A4 21200002 */  addu       $a0, $s0, $zero
    /* 2E9A8 8003E1A8 1C0F020C */  jal        func_80083C70
    /* 2E9AC 8003E1AC 01000524 */   addiu     $a1, $zero, 0x1
    /* 2E9B0 8003E1B0 C8D8A48E */  lw         $a0, %lo(D_800ED8C8)($s5)
    /* 2E9B4 8003E1B4 0000038E */  lw         $v1, 0x0($s0)
    /* 2E9B8 8003E1B8 0000828C */  lw         $v0, 0x0($a0)
    /* 2E9BC 8003E1BC 24187700 */  and        $v1, $v1, $s7
    /* 2E9C0 8003E1C0 24105400 */  and        $v0, $v0, $s4
    /* 2E9C4 8003E1C4 25186200 */  or         $v1, $v1, $v0
    /* 2E9C8 8003E1C8 000003AE */  sw         $v1, 0x0($s0)
    /* 2E9CC 8003E1CC 24181402 */  and        $v1, $s0, $s4
    /* 2E9D0 8003E1D0 0000828C */  lw         $v0, 0x0($a0)
    /* 2E9D4 8003E1D4 14001026 */  addiu      $s0, $s0, 0x14
    /* 2E9D8 8003E1D8 44F570AE */  sw         $s0, %lo(D_800BF544)($s3)
    /* 2E9DC 8003E1DC 24105700 */  and        $v0, $v0, $s7
    /* 2E9E0 8003E1E0 25104300 */  or         $v0, $v0, $v1
    /* 2E9E4 8003E1E4 000082AC */  sw         $v0, 0x0($a0)
    /* 2E9E8 8003E1E8 02111200 */  srl        $v0, $s2, 4
    /* 2E9EC 8003E1EC 21200002 */  addu       $a0, $s0, $zero
    /* 2E9F0 8003E1F0 01000524 */  addiu      $a1, $zero, 0x1
    /* 2E9F4 8003E1F4 FF032732 */  andi       $a3, $s1, 0x3FF
    /* 2E9F8 8003E1F8 82390700 */  srl        $a3, $a3, 6
    /* 2E9FC 8003E1FC 0001E734 */  ori        $a3, $a3, 0x100
    /* 2EA00 8003E200 2130A000 */  addu       $a2, $a1, $zero
    /* 2EA04 8003E204 25384700 */  or         $a3, $v0, $a3
    /* 2EA08 8003E208 780F020C */  jal        func_80083DE0
    /* 2EA0C 8003E20C 1000A0AF */   sw        $zero, 0x10($sp)
    /* 2EA10 8003E210 C8D8A48E */  lw         $a0, %lo(D_800ED8C8)($s5)
    /* 2EA14 8003E214 0C0F020C */  jal        func_80083C30
    /* 2EA18 8003E218 21280002 */   addu      $a1, $s0, $zero
    /* 2EA1C 8003E21C 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2EA20 8003E220 40003126 */  addiu      $s1, $s1, 0x40
    /* 2EA24 8003E224 FFFF2232 */  andi       $v0, $s1, 0xFFFF
    /* 2EA28 8003E228 4001422C */  sltiu      $v0, $v0, 0x140
    /* 2EA2C 8003E22C CBFF4014 */  bnez       $v0, .L8003E15C
    /* 2EA30 8003E230 44F570AE */   sw        $s0, %lo(D_800BF544)($s3)
  .L8003E234:
    /* 2EA34 8003E234 4400BF8F */  lw         $ra, 0x44($sp)
    /* 2EA38 8003E238 4000BE8F */  lw         $fp, 0x40($sp)
    /* 2EA3C 8003E23C 3C00B78F */  lw         $s7, 0x3C($sp)
    /* 2EA40 8003E240 3800B68F */  lw         $s6, 0x38($sp)
    /* 2EA44 8003E244 3400B58F */  lw         $s5, 0x34($sp)
    /* 2EA48 8003E248 3000B48F */  lw         $s4, 0x30($sp)
    /* 2EA4C 8003E24C 2C00B38F */  lw         $s3, 0x2C($sp)
    /* 2EA50 8003E250 2800B28F */  lw         $s2, 0x28($sp)
    /* 2EA54 8003E254 2400B18F */  lw         $s1, 0x24($sp)
    /* 2EA58 8003E258 2000B08F */  lw         $s0, 0x20($sp)
    /* 2EA5C 8003E25C 0800E003 */  jr         $ra
    /* 2EA60 8003E260 4800BD27 */   addiu     $sp, $sp, 0x48
endlabel func_8003E030

nonmatching func_8003E264, 0x1E4

glabel func_8003E264
    /* 2EA64 8003E264 B8FFBD27 */  addiu      $sp, $sp, -0x48
    /* 2EA68 8003E268 2400B1AF */  sw         $s1, 0x24($sp)
    /* 2EA6C 8003E26C 21880000 */  addu       $s1, $zero, $zero
    /* 2EA70 8003E270 3000B4AF */  sw         $s4, 0x30($sp)
    /* 2EA74 8003E274 0C80143C */  lui        $s4, %hi(D_800BF544)
    /* 2EA78 8003E278 3400B5AF */  sw         $s5, 0x34($sp)
    /* 2EA7C 8003E27C 80001524 */  addiu      $s5, $zero, 0x80
    /* 2EA80 8003E280 3800B6AF */  sw         $s6, 0x38($sp)
    /* 2EA84 8003E284 0F80163C */  lui        $s6, %hi(D_800ED8C8)
    /* 2EA88 8003E288 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* 2EA8C 8003E28C FF00133C */  lui        $s3, (0xFFFFFF >> 16)
    /* 2EA90 8003E290 801F023C */  lui        $v0, (0x1F800135 >> 16)
    /* 2EA94 8003E294 35014290 */  lbu        $v0, (0x1F800135 & 0xFFFF)($v0)
    /* 2EA98 8003E298 FFFF7336 */  ori        $s3, $s3, (0xFFFFFF & 0xFFFF)
    /* 2EA9C 8003E29C 3C00B7AF */  sw         $s7, 0x3C($sp)
    /* 2EAA0 8003E2A0 00FF173C */  lui        $s7, (0xFF000000 >> 16)
    /* 2EAA4 8003E2A4 4000BFAF */  sw         $ra, 0x40($sp)
    /* 2EAA8 8003E2A8 2800B2AF */  sw         $s2, 0x28($sp)
    /* 2EAAC 8003E2AC 2000B0AF */  sw         $s0, 0x20($sp)
    /* 2EAB0 8003E2B0 0100422C */  sltiu      $v0, $v0, 0x1
    /* 2EAB4 8003E2B4 00920200 */  sll        $s2, $v0, 8
  .L8003E2B8:
    /* 2EAB8 8003E2B8 44F5908E */  lw         $s0, %lo(D_800BF544)($s4)
    /* 2EABC 8003E2BC 40000224 */  addiu      $v0, $zero, 0x40
    /* 2EAC0 8003E2C0 21200002 */  addu       $a0, $s0, $zero
    /* 2EAC4 8003E2C4 100002A6 */  sh         $v0, 0x10($s0)
    /* 2EAC8 8003E2C8 00010224 */  addiu      $v0, $zero, 0x100
    /* 2EACC 8003E2CC 060015A2 */  sb         $s5, 0x6($s0)
    /* 2EAD0 8003E2D0 050015A2 */  sb         $s5, 0x5($s0)
    /* 2EAD4 8003E2D4 040015A2 */  sb         $s5, 0x4($s0)
    /* 2EAD8 8003E2D8 080011A6 */  sh         $s1, 0x8($s0)
    /* 2EADC 8003E2DC 0A0000A6 */  sh         $zero, 0xA($s0)
    /* 2EAE0 8003E2E0 0D0000A2 */  sb         $zero, 0xD($s0)
    /* 2EAE4 8003E2E4 0C0000A2 */  sb         $zero, 0xC($s0)
    /* 2EAE8 8003E2E8 0E0000A6 */  sh         $zero, 0xE($s0)
    /* 2EAEC 8003E2EC 300F020C */  jal        func_80083CC0
    /* 2EAF0 8003E2F0 120002A6 */   sh        $v0, 0x12($s0)
    /* 2EAF4 8003E2F4 21200002 */  addu       $a0, $s0, $zero
    /* 2EAF8 8003E2F8 1C0F020C */  jal        func_80083C70
    /* 2EAFC 8003E2FC 21280000 */   addu      $a1, $zero, $zero
    /* 2EB00 8003E300 C8D8C48E */  lw         $a0, %lo(D_800ED8C8)($s6)
    /* 2EB04 8003E304 0000038E */  lw         $v1, 0x0($s0)
    /* 2EB08 8003E308 0000828C */  lw         $v0, 0x0($a0)
    /* 2EB0C 8003E30C 24187700 */  and        $v1, $v1, $s7
    /* 2EB10 8003E310 24105300 */  and        $v0, $v0, $s3
    /* 2EB14 8003E314 25186200 */  or         $v1, $v1, $v0
    /* 2EB18 8003E318 000003AE */  sw         $v1, 0x0($s0)
    /* 2EB1C 8003E31C 24181302 */  and        $v1, $s0, $s3
    /* 2EB20 8003E320 0000828C */  lw         $v0, 0x0($a0)
    /* 2EB24 8003E324 14001026 */  addiu      $s0, $s0, 0x14
    /* 2EB28 8003E328 44F590AE */  sw         $s0, %lo(D_800BF544)($s4)
    /* 2EB2C 8003E32C 24105700 */  and        $v0, $v0, $s7
    /* 2EB30 8003E330 25104300 */  or         $v0, $v0, $v1
    /* 2EB34 8003E334 000082AC */  sw         $v0, 0x0($a0)
    /* 2EB38 8003E338 02111200 */  srl        $v0, $s2, 4
    /* 2EB3C 8003E33C 21200002 */  addu       $a0, $s0, $zero
    /* 2EB40 8003E340 01000524 */  addiu      $a1, $zero, 0x1
    /* 2EB44 8003E344 FF032732 */  andi       $a3, $s1, 0x3FF
    /* 2EB48 8003E348 82390700 */  srl        $a3, $a3, 6
    /* 2EB4C 8003E34C 0001E734 */  ori        $a3, $a3, 0x100
    /* 2EB50 8003E350 2130A000 */  addu       $a2, $a1, $zero
    /* 2EB54 8003E354 25384700 */  or         $a3, $v0, $a3
    /* 2EB58 8003E358 780F020C */  jal        func_80083DE0
    /* 2EB5C 8003E35C 1000A0AF */   sw        $zero, 0x10($sp)
    /* 2EB60 8003E360 C8D8C48E */  lw         $a0, %lo(D_800ED8C8)($s6)
    /* 2EB64 8003E364 0C0F020C */  jal        func_80083C30
    /* 2EB68 8003E368 21280002 */   addu      $a1, $s0, $zero
    /* 2EB6C 8003E36C 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2EB70 8003E370 40003126 */  addiu      $s1, $s1, 0x40
    /* 2EB74 8003E374 FFFF2232 */  andi       $v0, $s1, 0xFFFF
    /* 2EB78 8003E378 4001422C */  sltiu      $v0, $v0, 0x140
    /* 2EB7C 8003E37C CEFF4014 */  bnez       $v0, .L8003E2B8
    /* 2EB80 8003E380 44F590AE */   sw        $s0, %lo(D_800BF544)($s4)
    /* 2EB84 8003E384 0C80113C */  lui        $s1, %hi(D_800BF544)
    /* 2EB88 8003E388 44F5308E */  lw         $s0, %lo(D_800BF544)($s1)
    /* 2EB8C 8003E38C 01000524 */  addiu      $a1, $zero, 0x1
    /* 2EB90 8003E390 6C0F020C */  jal        func_80083DB0
    /* 2EB94 8003E394 21200002 */   addu      $a0, $s0, $zero
    /* 2EB98 8003E398 FF00053C */  lui        $a1, (0xFFFFFF >> 16)
    /* 2EB9C 8003E39C FFFFA534 */  ori        $a1, $a1, (0xFFFFFF & 0xFFFF)
    /* 2EBA0 8003E3A0 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2EBA4 8003E3A4 00FF073C */  lui        $a3, (0xFF000000 >> 16)
    /* 2EBA8 8003E3A8 06000424 */  addiu      $a0, $zero, 0x6
    /* 2EBAC 8003E3AC C8D8468C */  lw         $a2, %lo(D_800ED8C8)($v0)
    /* 2EBB0 8003E3B0 0000038E */  lw         $v1, 0x0($s0)
    /* 2EBB4 8003E3B4 FC1FC28C */  lw         $v0, 0x1FFC($a2)
    /* 2EBB8 8003E3B8 24186700 */  and        $v1, $v1, $a3
    /* 2EBBC 8003E3BC 24104500 */  and        $v0, $v0, $a1
    /* 2EBC0 8003E3C0 25186200 */  or         $v1, $v1, $v0
    /* 2EBC4 8003E3C4 000003AE */  sw         $v1, 0x0($s0)
    /* 2EBC8 8003E3C8 FC1FC28C */  lw         $v0, 0x1FFC($a2)
    /* 2EBCC 8003E3CC 24280502 */  and        $a1, $s0, $a1
    /* 2EBD0 8003E3D0 24104700 */  and        $v0, $v0, $a3
    /* 2EBD4 8003E3D4 25104500 */  or         $v0, $v0, $a1
    /* 2EBD8 8003E3D8 FC1FC2AC */  sw         $v0, 0x1FFC($a2)
    /* 2EBDC 8003E3DC 0E80023C */  lui        $v0, %hi(D_800E7E80)
    /* 2EBE0 8003E3E0 807E4224 */  addiu      $v0, $v0, %lo(D_800E7E80)
    /* 2EBE4 8003E3E4 2E004394 */  lhu        $v1, 0x2E($v0)
    /* 2EBE8 8003E3E8 32004594 */  lhu        $a1, 0x32($v0)
    /* 2EBEC 8003E3EC 36004294 */  lhu        $v0, 0x36($v0)
    /* 2EBF0 8003E3F0 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2EBF4 8003E3F4 44F530AE */  sw         $s0, %lo(D_800BF544)($s1)
    /* 2EBF8 8003E3F8 1800A3A7 */  sh         $v1, 0x18($sp)
    /* 2EBFC 8003E3FC 1A00A5A7 */  sh         $a1, 0x1A($sp)
    /* 2EC00 8003E400 78CA000C */  jal        func_800329E0
    /* 2EC04 8003E404 1C00A2A7 */   sh        $v0, 0x1C($sp)
    /* 2EC08 8003E408 1800A227 */  addiu      $v0, $sp, 0x18
    /* 2EC0C 8003E40C 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2EC10 8003E410 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2EC14 8003E414 F3C5000C */  jal        func_800317CC
    /* 2EC18 8003E418 21200000 */   addu      $a0, $zero, $zero
    /* 2EC1C 8003E41C 4000BF8F */  lw         $ra, 0x40($sp)
    /* 2EC20 8003E420 3C00B78F */  lw         $s7, 0x3C($sp)
    /* 2EC24 8003E424 3800B68F */  lw         $s6, 0x38($sp)
    /* 2EC28 8003E428 3400B58F */  lw         $s5, 0x34($sp)
    /* 2EC2C 8003E42C 3000B48F */  lw         $s4, 0x30($sp)
    /* 2EC30 8003E430 2C00B38F */  lw         $s3, 0x2C($sp)
    /* 2EC34 8003E434 2800B28F */  lw         $s2, 0x28($sp)
    /* 2EC38 8003E438 2400B18F */  lw         $s1, 0x24($sp)
    /* 2EC3C 8003E43C 2000B08F */  lw         $s0, 0x20($sp)
    /* 2EC40 8003E440 0800E003 */  jr         $ra
    /* 2EC44 8003E444 4800BD27 */   addiu     $sp, $sp, 0x48
endlabel func_8003E264

nonmatching func_8003E448, 0x44C

glabel func_8003E448
    /* 2EC48 8003E448 A8FFBD27 */  addiu      $sp, $sp, -0x58
    /* 2EC4C 8003E44C 0C800B3C */  lui        $t3, %hi(D_800BF544)
    /* 2EC50 8003E450 801F023C */  lui        $v0, (0x1F800135 >> 16)
    /* 2EC54 8003E454 3000B0AF */  sw         $s0, 0x30($sp)
    /* 2EC58 8003E458 44F5708D */  lw         $s0, %lo(D_800BF544)($t3)
    /* 2EC5C 8003E45C 35014290 */  lbu        $v0, (0x1F800135 & 0xFFFF)($v0)
    /* 2EC60 8003E460 3400B1AF */  sw         $s1, 0x34($sp)
    /* 2EC64 8003E464 21888000 */  addu       $s1, $a0, $zero
    /* 2EC68 8003E468 3800B2AF */  sw         $s2, 0x38($sp)
    /* 2EC6C 8003E46C 2190A000 */  addu       $s2, $a1, $zero
    /* 2EC70 8003E470 5400BFAF */  sw         $ra, 0x54($sp)
    /* 2EC74 8003E474 5000BEAF */  sw         $fp, 0x50($sp)
    /* 2EC78 8003E478 4C00B7AF */  sw         $s7, 0x4C($sp)
    /* 2EC7C 8003E47C 4800B6AF */  sw         $s6, 0x48($sp)
    /* 2EC80 8003E480 4400B5AF */  sw         $s5, 0x44($sp)
    /* 2EC84 8003E484 4000B4AF */  sw         $s4, 0x40($sp)
    /* 2EC88 8003E488 3C00B3AF */  sw         $s3, 0x3C($sp)
    /* 2EC8C 8003E48C 21200002 */  addu       $a0, $s0, $zero
    /* 2EC90 8003E490 0100432C */  sltiu      $v1, $v0, 0x1
    /* 2EC94 8003E494 280F020C */  jal        func_80083CA0
    /* 2EC98 8003E498 00F20300 */   sll       $fp, $v1, 8
    /* 2EC9C 8003E49C 21200002 */  addu       $a0, $s0, $zero
    /* 2ECA0 8003E4A0 1C0F020C */  jal        func_80083C70
    /* 2ECA4 8003E4A4 01000524 */   addiu     $a1, $zero, 0x1
    /* 2ECA8 8003E4A8 801F143C */  lui        $s4, (0x1F80008C >> 16)
    /* 2ECAC 8003E4AC 00002286 */  lh         $v0, 0x0($s1)
    /* 2ECB0 8003E4B0 02002386 */  lh         $v1, 0x2($s1)
    /* 2ECB4 8003E4B4 8C009586 */  lh         $s5, (0x1F80008C & 0xFFFF)($s4)
    /* 2ECB8 8003E4B8 8C009726 */  addiu      $s7, $s4, %lo(D_1F80008C)
    /* 2ECBC 8003E4BC 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2ECC0 8003E4C0 1400A3AF */  sw         $v1, 0x14($sp)
    /* 2ECC4 8003E4C4 00002286 */  lh         $v0, 0x0($s1)
    /* 2ECC8 8003E4C8 04002586 */  lh         $a1, 0x4($s1)
    /* 2ECCC 8003E4CC 02002786 */  lh         $a3, 0x2($s1)
    /* 2ECD0 8003E4D0 06002686 */  lh         $a2, 0x6($s1)
    /* 2ECD4 8003E4D4 21404000 */  addu       $t0, $v0, $zero
    /* 2ECD8 8003E4D8 2118E000 */  addu       $v1, $a3, $zero
    /* 2ECDC 8003E4DC 21104500 */  addu       $v0, $v0, $a1
    /* 2ECE0 8003E4E0 21186600 */  addu       $v1, $v1, $a2
    /* 2ECE4 8003E4E4 1800A2AF */  sw         $v0, 0x18($sp)
    /* 2ECE8 8003E4E8 1C00A7AF */  sw         $a3, 0x1C($sp)
    /* 2ECEC 8003E4EC 2000A8AF */  sw         $t0, 0x20($sp)
    /* 2ECF0 8003E4F0 2400A3AF */  sw         $v1, 0x24($sp)
    /* 2ECF4 8003E4F4 00002286 */  lh         $v0, 0x0($s1)
    /* 2ECF8 8003E4F8 04002586 */  lh         $a1, 0x4($s1)
    /* 2ECFC 8003E4FC 02002386 */  lh         $v1, 0x2($s1)
    /* 2ED00 8003E500 06002686 */  lh         $a2, 0x6($s1)
    /* 2ED04 8003E504 21104500 */  addu       $v0, $v0, $a1
    /* 2ED08 8003E508 21186600 */  addu       $v1, $v1, $a2
    /* 2ED0C 8003E50C 2800A2AF */  sw         $v0, 0x28($sp)
    /* 2ED10 8003E510 2C00A3AF */  sw         $v1, 0x2C($sp)
    /* 2ED14 8003E514 0200F686 */  lh         $s6, 0x2($s7)
    /* 2ED18 8003E518 D40F020C */  jal        func_80083F50
    /* 2ED1C 8003E51C 21204002 */   addu      $a0, $s2, $zero
    /* 2ED20 8003E520 21204002 */  addu       $a0, $s2, $zero
    /* 2ED24 8003E524 A00F020C */  jal        func_80083E80
    /* 2ED28 8003E528 21984000 */   addu      $s3, $v0, $zero
    /* 2ED2C 8003E52C 1000A48F */  lw         $a0, 0x10($sp)
    /* 2ED30 8003E530 00000000 */  nop
    /* 2ED34 8003E534 23209500 */  subu       $a0, $a0, $s5
    /* 2ED38 8003E538 C3190400 */  sra        $v1, $a0, 7
    /* 2ED3C 8003E53C 21208300 */  addu       $a0, $a0, $v1
    /* 2ED40 8003E540 18009300 */  mult       $a0, $s3
    /* 2ED44 8003E544 1400A38F */  lw         $v1, 0x14($sp)
    /* 2ED48 8003E548 00000000 */  nop
    /* 2ED4C 8003E54C 23187600 */  subu       $v1, $v1, $s6
    /* 2ED50 8003E550 12380000 */  mflo       $a3
    /* 2ED54 8003E554 C3290300 */  sra        $a1, $v1, 7
    /* 2ED58 8003E558 21186500 */  addu       $v1, $v1, $a1
    /* 2ED5C 8003E55C 18006200 */  mult       $v1, $v0
    /* 2ED60 8003E560 12280000 */  mflo       $a1
    /* 2ED64 8003E564 00000000 */  nop
    /* 2ED68 8003E568 00000000 */  nop
    /* 2ED6C 8003E56C 18008200 */  mult       $a0, $v0
    /* 2ED70 8003E570 12300000 */  mflo       $a2
    /* 2ED74 8003E574 00000000 */  nop
    /* 2ED78 8003E578 00000000 */  nop
    /* 2ED7C 8003E57C 18007300 */  mult       $v1, $s3
    /* 2ED80 8003E580 2110E500 */  addu       $v0, $a3, $a1
    /* 2ED84 8003E584 03130200 */  sra        $v0, $v0, 12
    /* 2ED88 8003E588 21105500 */  addu       $v0, $v0, $s5
    /* 2ED8C 8003E58C 8C009586 */  lh         $s5, (0x1F80008C & 0xFFFF)($s4)
    /* 2ED90 8003E590 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2ED94 8003E594 12180000 */  mflo       $v1
    /* 2ED98 8003E598 23186600 */  subu       $v1, $v1, $a2
    /* 2ED9C 8003E59C 031B0300 */  sra        $v1, $v1, 12
    /* 2EDA0 8003E5A0 21187600 */  addu       $v1, $v1, $s6
    /* 2EDA4 8003E5A4 1400A3AF */  sw         $v1, 0x14($sp)
    /* 2EDA8 8003E5A8 0200F686 */  lh         $s6, 0x2($s7)
    /* 2EDAC 8003E5AC D40F020C */  jal        func_80083F50
    /* 2EDB0 8003E5B0 21204002 */   addu      $a0, $s2, $zero
    /* 2EDB4 8003E5B4 21204002 */  addu       $a0, $s2, $zero
    /* 2EDB8 8003E5B8 A00F020C */  jal        func_80083E80
    /* 2EDBC 8003E5BC 21984000 */   addu      $s3, $v0, $zero
    /* 2EDC0 8003E5C0 1800A48F */  lw         $a0, 0x18($sp)
    /* 2EDC4 8003E5C4 00000000 */  nop
    /* 2EDC8 8003E5C8 23209500 */  subu       $a0, $a0, $s5
    /* 2EDCC 8003E5CC C3190400 */  sra        $v1, $a0, 7
    /* 2EDD0 8003E5D0 21208300 */  addu       $a0, $a0, $v1
    /* 2EDD4 8003E5D4 18009300 */  mult       $a0, $s3
    /* 2EDD8 8003E5D8 1C00A38F */  lw         $v1, 0x1C($sp)
    /* 2EDDC 8003E5DC 00000000 */  nop
    /* 2EDE0 8003E5E0 23187600 */  subu       $v1, $v1, $s6
    /* 2EDE4 8003E5E4 12380000 */  mflo       $a3
    /* 2EDE8 8003E5E8 C3290300 */  sra        $a1, $v1, 7
    /* 2EDEC 8003E5EC 21186500 */  addu       $v1, $v1, $a1
    /* 2EDF0 8003E5F0 18006200 */  mult       $v1, $v0
    /* 2EDF4 8003E5F4 12280000 */  mflo       $a1
    /* 2EDF8 8003E5F8 00000000 */  nop
    /* 2EDFC 8003E5FC 00000000 */  nop
    /* 2EE00 8003E600 18008200 */  mult       $a0, $v0
    /* 2EE04 8003E604 12300000 */  mflo       $a2
    /* 2EE08 8003E608 00000000 */  nop
    /* 2EE0C 8003E60C 00000000 */  nop
    /* 2EE10 8003E610 18007300 */  mult       $v1, $s3
    /* 2EE14 8003E614 2110E500 */  addu       $v0, $a3, $a1
    /* 2EE18 8003E618 03130200 */  sra        $v0, $v0, 12
    /* 2EE1C 8003E61C 21105500 */  addu       $v0, $v0, $s5
    /* 2EE20 8003E620 8C009586 */  lh         $s5, (0x1F80008C & 0xFFFF)($s4)
    /* 2EE24 8003E624 1800A2AF */  sw         $v0, 0x18($sp)
    /* 2EE28 8003E628 12180000 */  mflo       $v1
    /* 2EE2C 8003E62C 23186600 */  subu       $v1, $v1, $a2
    /* 2EE30 8003E630 031B0300 */  sra        $v1, $v1, 12
    /* 2EE34 8003E634 21187600 */  addu       $v1, $v1, $s6
    /* 2EE38 8003E638 1C00A3AF */  sw         $v1, 0x1C($sp)
    /* 2EE3C 8003E63C 0200F686 */  lh         $s6, 0x2($s7)
    /* 2EE40 8003E640 D40F020C */  jal        func_80083F50
    /* 2EE44 8003E644 21204002 */   addu      $a0, $s2, $zero
    /* 2EE48 8003E648 21204002 */  addu       $a0, $s2, $zero
    /* 2EE4C 8003E64C A00F020C */  jal        func_80083E80
    /* 2EE50 8003E650 21984000 */   addu      $s3, $v0, $zero
    /* 2EE54 8003E654 2000A48F */  lw         $a0, 0x20($sp)
    /* 2EE58 8003E658 00000000 */  nop
    /* 2EE5C 8003E65C 23209500 */  subu       $a0, $a0, $s5
    /* 2EE60 8003E660 C3190400 */  sra        $v1, $a0, 7
    /* 2EE64 8003E664 21208300 */  addu       $a0, $a0, $v1
    /* 2EE68 8003E668 18009300 */  mult       $a0, $s3
    /* 2EE6C 8003E66C 2400A38F */  lw         $v1, 0x24($sp)
    /* 2EE70 8003E670 00000000 */  nop
    /* 2EE74 8003E674 23187600 */  subu       $v1, $v1, $s6
    /* 2EE78 8003E678 12380000 */  mflo       $a3
    /* 2EE7C 8003E67C C3290300 */  sra        $a1, $v1, 7
    /* 2EE80 8003E680 21186500 */  addu       $v1, $v1, $a1
    /* 2EE84 8003E684 18006200 */  mult       $v1, $v0
    /* 2EE88 8003E688 12280000 */  mflo       $a1
    /* 2EE8C 8003E68C 00000000 */  nop
    /* 2EE90 8003E690 00000000 */  nop
    /* 2EE94 8003E694 18008200 */  mult       $a0, $v0
    /* 2EE98 8003E698 12300000 */  mflo       $a2
    /* 2EE9C 8003E69C 00000000 */  nop
    /* 2EEA0 8003E6A0 00000000 */  nop
    /* 2EEA4 8003E6A4 18007300 */  mult       $v1, $s3
    /* 2EEA8 8003E6A8 2110E500 */  addu       $v0, $a3, $a1
    /* 2EEAC 8003E6AC 03130200 */  sra        $v0, $v0, 12
    /* 2EEB0 8003E6B0 21105500 */  addu       $v0, $v0, $s5
    /* 2EEB4 8003E6B4 2000A2AF */  sw         $v0, 0x20($sp)
    /* 2EEB8 8003E6B8 8C009386 */  lh         $s3, (0x1F80008C & 0xFFFF)($s4)
    /* 2EEBC 8003E6BC 12180000 */  mflo       $v1
    /* 2EEC0 8003E6C0 23186600 */  subu       $v1, $v1, $a2
    /* 2EEC4 8003E6C4 031B0300 */  sra        $v1, $v1, 12
    /* 2EEC8 8003E6C8 21187600 */  addu       $v1, $v1, $s6
    /* 2EECC 8003E6CC 2400A3AF */  sw         $v1, 0x24($sp)
    /* 2EED0 8003E6D0 0200F486 */  lh         $s4, 0x2($s7)
    /* 2EED4 8003E6D4 D40F020C */  jal        func_80083F50
    /* 2EED8 8003E6D8 21204002 */   addu      $a0, $s2, $zero
    /* 2EEDC 8003E6DC 21204002 */  addu       $a0, $s2, $zero
    /* 2EEE0 8003E6E0 A00F020C */  jal        func_80083E80
    /* 2EEE4 8003E6E4 21904000 */   addu      $s2, $v0, $zero
    /* 2EEE8 8003E6E8 2800A48F */  lw         $a0, 0x28($sp)
    /* 2EEEC 8003E6EC 00000000 */  nop
    /* 2EEF0 8003E6F0 23209300 */  subu       $a0, $a0, $s3
    /* 2EEF4 8003E6F4 C3190400 */  sra        $v1, $a0, 7
    /* 2EEF8 8003E6F8 21208300 */  addu       $a0, $a0, $v1
    /* 2EEFC 8003E6FC 18009200 */  mult       $a0, $s2
    /* 2EF00 8003E700 2C00A38F */  lw         $v1, 0x2C($sp)
    /* 2EF04 8003E704 00000000 */  nop
    /* 2EF08 8003E708 23187400 */  subu       $v1, $v1, $s4
    /* 2EF0C 8003E70C 12300000 */  mflo       $a2
    /* 2EF10 8003E710 C3290300 */  sra        $a1, $v1, 7
    /* 2EF14 8003E714 21186500 */  addu       $v1, $v1, $a1
    /* 2EF18 8003E718 18006200 */  mult       $v1, $v0
    /* 2EF1C 8003E71C 12280000 */  mflo       $a1
    /* 2EF20 8003E720 00000000 */  nop
    /* 2EF24 8003E724 00000000 */  nop
    /* 2EF28 8003E728 18008200 */  mult       $a0, $v0
    /* 2EF2C 8003E72C 12200000 */  mflo       $a0
    /* 2EF30 8003E730 00000000 */  nop
    /* 2EF34 8003E734 00000000 */  nop
    /* 2EF38 8003E738 18007200 */  mult       $v1, $s2
    /* 2EF3C 8003E73C FF00083C */  lui        $t0, (0xFFFFFF >> 16)
    /* 2EF40 8003E740 FFFF0835 */  ori        $t0, $t0, (0xFFFFFF & 0xFFFF)
    /* 2EF44 8003E744 2400A797 */  lhu        $a3, 0x24($sp)
    /* 2EF48 8003E748 2110C500 */  addu       $v0, $a2, $a1
    /* 2EF4C 8003E74C 03130200 */  sra        $v0, $v0, 12
    /* 2EF50 8003E750 21105300 */  addu       $v0, $v0, $s3
    /* 2EF54 8003E754 2800A2AF */  sw         $v0, 0x28($sp)
    /* 2EF58 8003E758 1000A297 */  lhu        $v0, 0x10($sp)
    /* 2EF5C 8003E75C 1C00A597 */  lhu        $a1, 0x1C($sp)
    /* 2EF60 8003E760 2000A697 */  lhu        $a2, 0x20($sp)
    /* 2EF64 8003E764 2800A997 */  lhu        $t1, 0x28($sp)
    /* 2EF68 8003E768 12180000 */  mflo       $v1
    /* 2EF6C 8003E76C 23186400 */  subu       $v1, $v1, $a0
    /* 2EF70 8003E770 031B0300 */  sra        $v1, $v1, 12
    /* 2EF74 8003E774 21187400 */  addu       $v1, $v1, $s4
    /* 2EF78 8003E778 2C00A3AF */  sw         $v1, 0x2C($sp)
    /* 2EF7C 8003E77C 1400A397 */  lhu        $v1, 0x14($sp)
    /* 2EF80 8003E780 1800A497 */  lhu        $a0, 0x18($sp)
    /* 2EF84 8003E784 2C00AA97 */  lhu        $t2, 0x2C($sp)
    /* 2EF88 8003E788 0C800B3C */  lui        $t3, %hi(D_800BF544)
    /* 2EF8C 8003E78C 080002A6 */  sh         $v0, 0x8($s0)
    /* 2EF90 8003E790 3F000224 */  addiu      $v0, $zero, 0x3F
    /* 2EF94 8003E794 240002A2 */  sb         $v0, 0x24($s0)
    /* 2EF98 8003E798 140002A2 */  sb         $v0, 0x14($s0)
    /* 2EF9C 8003E79C FF000224 */  addiu      $v0, $zero, 0xFF
    /* 2EFA0 8003E7A0 120005A6 */  sh         $a1, 0x12($s0)
    /* 2EFA4 8003E7A4 180006A6 */  sh         $a2, 0x18($s0)
    /* 2EFA8 8003E7A8 1A0007A6 */  sh         $a3, 0x1A($s0)
    /* 2EFAC 8003E7AC 1C0000A2 */  sb         $zero, 0x1C($s0)
    /* 2EFB0 8003E7B0 0C0000A2 */  sb         $zero, 0xC($s0)
    /* 2EFB4 8003E7B4 150000A2 */  sb         $zero, 0x15($s0)
    /* 2EFB8 8003E7B8 0D0000A2 */  sb         $zero, 0xD($s0)
    /* 2EFBC 8003E7BC 250002A2 */  sb         $v0, 0x25($s0)
    /* 2EFC0 8003E7C0 1D0002A2 */  sb         $v0, 0x1D($s0)
    /* 2EFC4 8003E7C4 200009A6 */  sh         $t1, 0x20($s0)
    /* 2EFC8 8003E7C8 0A0003A6 */  sh         $v1, 0xA($s0)
    /* 2EFCC 8003E7CC 100004A6 */  sh         $a0, 0x10($s0)
    /* 2EFD0 8003E7D0 22000AA6 */  sh         $t2, 0x22($s0)
    /* 2EFD4 8003E7D4 02002496 */  lhu        $a0, 0x2($s1)
    /* 2EFD8 8003E7D8 02002386 */  lh         $v1, 0x2($s1)
    /* 2EFDC 8003E7DC 00002296 */  lhu        $v0, 0x0($s1)
    /* 2EFE0 8003E7E0 80000524 */  addiu      $a1, $zero, 0x80
    /* 2EFE4 8003E7E4 040005A2 */  sb         $a1, 0x4($s0)
    /* 2EFE8 8003E7E8 2118C303 */  addu       $v1, $fp, $v1
    /* 2EFEC 8003E7EC 00016330 */  andi       $v1, $v1, 0x100
    /* 2EFF0 8003E7F0 03190300 */  sra        $v1, $v1, 4
    /* 2EFF4 8003E7F4 FF034230 */  andi       $v0, $v0, 0x3FF
    /* 2EFF8 8003E7F8 82110200 */  srl        $v0, $v0, 6
    /* 2EFFC 8003E7FC 00014234 */  ori        $v0, $v0, 0x100
    /* 2F000 8003E800 25186200 */  or         $v1, $v1, $v0
    /* 2F004 8003E804 21209E00 */  addu       $a0, $a0, $fp
    /* 2F008 8003E808 00028430 */  andi       $a0, $a0, 0x200
    /* 2F00C 8003E80C 80200400 */  sll        $a0, $a0, 2
    /* 2F010 8003E810 25186400 */  or         $v1, $v1, $a0
    /* 2F014 8003E814 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2F018 8003E818 160003A6 */  sh         $v1, 0x16($s0)
    /* 2F01C 8003E81C 050005A2 */  sb         $a1, 0x5($s0)
    /* 2F020 8003E820 060005A2 */  sb         $a1, 0x6($s0)
    /* 2F024 8003E824 C8D8448C */  lw         $a0, %lo(D_800ED8C8)($v0)
    /* 2F028 8003E828 0000038E */  lw         $v1, 0x0($s0)
    /* 2F02C 8003E82C 00FF053C */  lui        $a1, (0xFF000000 >> 16)
    /* 2F030 8003E830 0E0000A6 */  sh         $zero, 0xE($s0)
    /* 2F034 8003E834 0000828C */  lw         $v0, 0x0($a0)
    /* 2F038 8003E838 24186500 */  and        $v1, $v1, $a1
    /* 2F03C 8003E83C 24104800 */  and        $v0, $v0, $t0
    /* 2F040 8003E840 25186200 */  or         $v1, $v1, $v0
    /* 2F044 8003E844 24400802 */  and        $t0, $s0, $t0
    /* 2F048 8003E848 000003AE */  sw         $v1, 0x0($s0)
    /* 2F04C 8003E84C 0000828C */  lw         $v0, 0x0($a0)
    /* 2F050 8003E850 28001026 */  addiu      $s0, $s0, 0x28
    /* 2F054 8003E854 44F570AD */  sw         $s0, %lo(D_800BF544)($t3)
    /* 2F058 8003E858 24104500 */  and        $v0, $v0, $a1
    /* 2F05C 8003E85C 25104800 */  or         $v0, $v0, $t0
    /* 2F060 8003E860 000082AC */  sw         $v0, 0x0($a0)
    /* 2F064 8003E864 5400BF8F */  lw         $ra, 0x54($sp)
    /* 2F068 8003E868 5000BE8F */  lw         $fp, 0x50($sp)
    /* 2F06C 8003E86C 4C00B78F */  lw         $s7, 0x4C($sp)
    /* 2F070 8003E870 4800B68F */  lw         $s6, 0x48($sp)
    /* 2F074 8003E874 4400B58F */  lw         $s5, 0x44($sp)
    /* 2F078 8003E878 4000B48F */  lw         $s4, 0x40($sp)
    /* 2F07C 8003E87C 3C00B38F */  lw         $s3, 0x3C($sp)
    /* 2F080 8003E880 3800B28F */  lw         $s2, 0x38($sp)
    /* 2F084 8003E884 3400B18F */  lw         $s1, 0x34($sp)
    /* 2F088 8003E888 3000B08F */  lw         $s0, 0x30($sp)
    /* 2F08C 8003E88C 0800E003 */  jr         $ra
    /* 2F090 8003E890 5800BD27 */   addiu     $sp, $sp, 0x58
endlabel func_8003E448

nonmatching func_8003E894, 0x1F4

glabel func_8003E894
    /* 2F094 8003E894 B8FFBD27 */  addiu      $sp, $sp, -0x48
    /* 2F098 8003E898 0E80023C */  lui        $v0, %hi(D_800E7E80)
    /* 2F09C 8003E89C 807E4224 */  addiu      $v0, $v0, %lo(D_800E7E80)
    /* 2F0A0 8003E8A0 4400BFAF */  sw         $ra, 0x44($sp)
    /* 2F0A4 8003E8A4 4000B6AF */  sw         $s6, 0x40($sp)
    /* 2F0A8 8003E8A8 3C00B5AF */  sw         $s5, 0x3C($sp)
    /* 2F0AC 8003E8AC 3800B4AF */  sw         $s4, 0x38($sp)
    /* 2F0B0 8003E8B0 3400B3AF */  sw         $s3, 0x34($sp)
    /* 2F0B4 8003E8B4 3000B2AF */  sw         $s2, 0x30($sp)
    /* 2F0B8 8003E8B8 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* 2F0BC 8003E8BC 2800B0AF */  sw         $s0, 0x28($sp)
    /* 2F0C0 8003E8C0 2E004394 */  lhu        $v1, 0x2E($v0)
    /* 2F0C4 8003E8C4 32004594 */  lhu        $a1, 0x32($v0)
    /* 2F0C8 8003E8C8 36004294 */  lhu        $v0, 0x36($v0)
    /* 2F0CC 8003E8CC 06000424 */  addiu      $a0, $zero, 0x6
    /* 2F0D0 8003E8D0 1800A3A7 */  sh         $v1, 0x18($sp)
    /* 2F0D4 8003E8D4 1A00A5A7 */  sh         $a1, 0x1A($sp)
    /* 2F0D8 8003E8D8 78CA000C */  jal        func_800329E0
    /* 2F0DC 8003E8DC 1C00A2A7 */   sh        $v0, 0x1C($sp)
    /* 2F0E0 8003E8E0 801F103C */  lui        $s0, (0x1F80008C >> 16)
    /* 2F0E4 8003E8E4 8C001226 */  addiu      $s2, $s0, %lo(D_1F80008C)
    /* 2F0E8 8003E8E8 1800A227 */  addiu      $v0, $sp, 0x18
    /* 2F0EC 8003E8EC 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2F0F0 8003E8F0 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2F0F4 8003E8F4 F3C5000C */  jal        func_800317CC
    /* 2F0F8 8003E8F8 21200000 */   addu      $a0, $zero, $zero
    /* 2F0FC 8003E8FC 21A00000 */  addu       $s4, $zero, $zero
    /* 2F100 8003E900 40001624 */  addiu      $s6, $zero, 0x40
    /* 2F104 8003E904 0A80113C */  lui        $s1, %hi(D_800A3B18)
    /* 2F108 8003E908 183B248E */  lw         $a0, %lo(D_800A3B18)($s1)
    /* 2F10C 8003E90C D40F020C */  jal        func_80083F50
    /* 2F110 8003E910 FF001524 */   addiu     $s5, $zero, 0xFF
    /* 2F114 8003E914 40110200 */  sll        $v0, $v0, 5
    /* 2F118 8003E918 03130200 */  sra        $v0, $v0, 12
    /* 2F11C 8003E91C 8C000396 */  lhu        $v1, (0x1F80008C & 0xFFFF)($s0)
    /* 2F120 8003E920 183B248E */  lw         $a0, %lo(D_800A3B18)($s1)
    /* 2F124 8003E924 21186200 */  addu       $v1, $v1, $v0
    /* 2F128 8003E928 A00F020C */  jal        func_80083E80
    /* 2F12C 8003E92C 8C0003A6 */   sh        $v1, (0x1F80008C & 0xFFFF)($s0)
    /* 2F130 8003E930 0C80133C */  lui        $s3, %hi(D_800BF544)
    /* 2F134 8003E934 21288002 */  addu       $a1, $s4, $zero
    /* 2F138 8003E938 40110200 */  sll        $v0, $v0, 5
    /* 2F13C 8003E93C 03130200 */  sra        $v0, $v0, 12
    /* 2F140 8003E940 44F5708E */  lw         $s0, %lo(D_800BF544)($s3)
    /* 2F144 8003E944 02004396 */  lhu        $v1, 0x2($s2)
    /* 2F148 8003E948 183B268E */  lw         $a2, %lo(D_800A3B18)($s1)
    /* 2F14C 8003E94C 21200002 */  addu       $a0, $s0, $zero
    /* 2F150 8003E950 21186200 */  addu       $v1, $v1, $v0
    /* 2F154 8003E954 4902C624 */  addiu      $a2, $a2, 0x249
    /* 2F158 8003E958 020043A6 */  sh         $v1, 0x2($s2)
    /* 2F15C 8003E95C 6C0F020C */  jal        func_80083DB0
    /* 2F160 8003E960 183B26AE */   sw        $a2, %lo(D_800A3B18)($s1)
    /* 2F164 8003E964 FF00043C */  lui        $a0, (0xFFFFFF >> 16)
    /* 2F168 8003E968 FFFF8434 */  ori        $a0, $a0, (0xFFFFFF & 0xFFFF)
    /* 2F16C 8003E96C 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2F170 8003E970 00FF063C */  lui        $a2, (0xFF000000 >> 16)
    /* 2F174 8003E974 C8D8458C */  lw         $a1, %lo(D_800ED8C8)($v0)
    /* 2F178 8003E978 0000038E */  lw         $v1, 0x0($s0)
    /* 2F17C 8003E97C 0000A28C */  lw         $v0, 0x0($a1)
    /* 2F180 8003E980 24186600 */  and        $v1, $v1, $a2
    /* 2F184 8003E984 24104400 */  and        $v0, $v0, $a0
    /* 2F188 8003E988 25186200 */  or         $v1, $v1, $v0
    /* 2F18C 8003E98C 24200402 */  and        $a0, $s0, $a0
    /* 2F190 8003E990 000003AE */  sw         $v1, 0x0($s0)
    /* 2F194 8003E994 0000A28C */  lw         $v0, 0x0($a1)
    /* 2F198 8003E998 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2F19C 8003E99C 44F570AE */  sw         $s0, %lo(D_800BF544)($s3)
    /* 2F1A0 8003E9A0 24104600 */  and        $v0, $v0, $a2
    /* 2F1A4 8003E9A4 25104400 */  or         $v0, $v0, $a0
    /* 2F1A8 8003E9A8 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2F1AC 8003E9AC 2000A427 */  addiu      $a0, $sp, 0x20
  .L8003E9B0:
    /* 2F1B0 8003E9B0 0C000524 */  addiu      $a1, $zero, 0xC
    /* 2F1B4 8003E9B4 2000B4A7 */  sh         $s4, 0x20($sp)
    /* 2F1B8 8003E9B8 2200A0A7 */  sh         $zero, 0x22($sp)
    /* 2F1BC 8003E9BC 2400B6A7 */  sh         $s6, 0x24($sp)
    /* 2F1C0 8003E9C0 12F9000C */  jal        func_8003E448
    /* 2F1C4 8003E9C4 2600B5A7 */   sh        $s5, 0x26($sp)
    /* 2F1C8 8003E9C8 40009426 */  addiu      $s4, $s4, 0x40
    /* 2F1CC 8003E9CC 4001822A */  slti       $v0, $s4, 0x140
    /* 2F1D0 8003E9D0 F7FF4014 */  bnez       $v0, .L8003E9B0
    /* 2F1D4 8003E9D4 2000A427 */   addiu     $a0, $sp, 0x20
    /* 2F1D8 8003E9D8 0C80123C */  lui        $s2, %hi(D_800BF544)
    /* 2F1DC 8003E9DC 21280000 */  addu       $a1, $zero, $zero
    /* 2F1E0 8003E9E0 2130A000 */  addu       $a2, $a1, $zero
    /* 2F1E4 8003E9E4 44F5508E */  lw         $s0, %lo(D_800BF544)($s2)
    /* 2F1E8 8003E9E8 2138A000 */  addu       $a3, $a1, $zero
    /* 2F1EC 8003E9EC 1000A0AF */  sw         $zero, 0x10($sp)
    /* 2F1F0 8003E9F0 780F020C */  jal        func_80083DE0
    /* 2F1F4 8003E9F4 21200002 */   addu      $a0, $s0, $zero
    /* 2F1F8 8003E9F8 21280002 */  addu       $a1, $s0, $zero
    /* 2F1FC 8003E9FC 0F80113C */  lui        $s1, %hi(D_800ED8C8)
    /* 2F200 8003EA00 C8D8248E */  lw         $a0, %lo(D_800ED8C8)($s1)
    /* 2F204 8003EA04 0C0F020C */  jal        func_80083C30
    /* 2F208 8003EA08 0C001026 */   addiu     $s0, $s0, 0xC
    /* 2F20C 8003EA0C 44F550AE */  sw         $s0, %lo(D_800BF544)($s2)
    /* 2F210 8003EA10 21200002 */  addu       $a0, $s0, $zero
    /* 2F214 8003EA14 6C0F020C */  jal        func_80083DB0
    /* 2F218 8003EA18 01000524 */   addiu     $a1, $zero, 0x1
    /* 2F21C 8003EA1C FF00053C */  lui        $a1, (0xFFFFFF >> 16)
    /* 2F220 8003EA20 FFFFA534 */  ori        $a1, $a1, (0xFFFFFF & 0xFFFF)
    /* 2F224 8003EA24 00FF063C */  lui        $a2, (0xFF000000 >> 16)
    /* 2F228 8003EA28 C8D8248E */  lw         $a0, %lo(D_800ED8C8)($s1)
    /* 2F22C 8003EA2C 0000038E */  lw         $v1, 0x0($s0)
    /* 2F230 8003EA30 FC1F828C */  lw         $v0, 0x1FFC($a0)
    /* 2F234 8003EA34 24186600 */  and        $v1, $v1, $a2
    /* 2F238 8003EA38 24104500 */  and        $v0, $v0, $a1
    /* 2F23C 8003EA3C 25186200 */  or         $v1, $v1, $v0
    /* 2F240 8003EA40 000003AE */  sw         $v1, 0x0($s0)
    /* 2F244 8003EA44 0C000326 */  addiu      $v1, $s0, 0xC
    /* 2F248 8003EA48 FC1F828C */  lw         $v0, 0x1FFC($a0)
    /* 2F24C 8003EA4C 24800502 */  and        $s0, $s0, $a1
    /* 2F250 8003EA50 44F543AE */  sw         $v1, %lo(D_800BF544)($s2)
    /* 2F254 8003EA54 24104600 */  and        $v0, $v0, $a2
    /* 2F258 8003EA58 25105000 */  or         $v0, $v0, $s0
    /* 2F25C 8003EA5C FC1F82AC */  sw         $v0, 0x1FFC($a0)
    /* 2F260 8003EA60 4400BF8F */  lw         $ra, 0x44($sp)
    /* 2F264 8003EA64 4000B68F */  lw         $s6, 0x40($sp)
    /* 2F268 8003EA68 3C00B58F */  lw         $s5, 0x3C($sp)
    /* 2F26C 8003EA6C 3800B48F */  lw         $s4, 0x38($sp)
    /* 2F270 8003EA70 3400B38F */  lw         $s3, 0x34($sp)
    /* 2F274 8003EA74 3000B28F */  lw         $s2, 0x30($sp)
    /* 2F278 8003EA78 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 2F27C 8003EA7C 2800B08F */  lw         $s0, 0x28($sp)
    /* 2F280 8003EA80 0800E003 */  jr         $ra
    /* 2F284 8003EA84 4800BD27 */   addiu     $sp, $sp, 0x48
endlabel func_8003E894

nonmatching func_8003EA88, 0x158

glabel func_8003EA88
    /* 2F288 8003EA88 0C80023C */  lui        $v0, %hi(D_800BF544)
    /* 2F28C 8003EA8C 44F5498C */  lw         $t1, %lo(D_800BF544)($v0)
    /* 2F290 8003EA90 21400000 */  addu       $t0, $zero, $zero
    /* 2F294 8003EA94 DCFE0B3C */  lui        $t3, (0xFEDCBA97 >> 16)
    /* 2F298 8003EA98 97BA6B35 */  ori        $t3, $t3, (0xFEDCBA97 & 0xFFFF)
    /* 2F29C 8003EA9C FF000A3C */  lui        $t2, (0xFFFFFF >> 16)
    /* 2F2A0 8003EAA0 FFFF4A35 */  ori        $t2, $t2, (0xFFFFFF & 0xFFFF)
    /* 2F2A4 8003EAA4 00FF0D3C */  lui        $t5, (0xFF000000 >> 16)
    /* 2F2A8 8003EAA8 17002625 */  addiu      $a2, $t1, 0x17
  .L8003EAAC:
    /* 2F2AC 8003EAAC 801F023C */  lui        $v0, (0x1F800198 >> 16)
    /* 2F2B0 8003EAB0 031C0B00 */  sra        $v1, $t3, 16
    /* 2F2B4 8003EAB4 98014294 */  lhu        $v0, (0x1F800198 & 0xFFFF)($v0)
    /* 2F2B8 8003EAB8 801F0C3C */  lui        $t4, (0x1F80008C >> 16)
    /* 2F2BC 8003EABC 00110200 */  sll        $v0, $v0, 4
    /* 2F2C0 8003EAC0 21186200 */  addu       $v1, $v1, $v0
    /* 2F2C4 8003EAC4 FF036530 */  andi       $a1, $v1, 0x3FF
    /* 2F2C8 8003EAC8 00110500 */  sll        $v0, $a1, 4
    /* 2F2CC 8003EACC 23104500 */  subu       $v0, $v0, $a1
    /* 2F2D0 8003EAD0 80110200 */  sll        $v0, $v0, 6
    /* 2F2D4 8003EAD4 832A0200 */  sra        $a1, $v0, 10
    /* 2F2D8 8003EAD8 8C00828D */  lw         $v0, (0x1F80008C & 0xFFFF)($t4)
    /* 2F2DC 8003EADC 00000000 */  nop
    /* 2F2E0 8003EAE0 83100200 */  sra        $v0, $v0, 2
    /* 2F2E4 8003EAE4 40004724 */  addiu      $a3, $v0, 0x40
    /* 2F2E8 8003EAE8 78004324 */  addiu      $v1, $v0, 0x78
    /* 2F2EC 8003EAEC 0001E228 */  slti       $v0, $a3, 0x100
    /* 2F2F0 8003EAF0 02004014 */  bnez       $v0, .L8003EAFC
    /* 2F2F4 8003EAF4 C0FEA524 */   addiu     $a1, $a1, -0x140
    /* 2F2F8 8003EAF8 FF000724 */  addiu      $a3, $zero, 0xFF
  .L8003EAFC:
    /* 2F2FC 8003EAFC 00016228 */  slti       $v0, $v1, 0x100
    /* 2F300 8003EB00 02004014 */  bnez       $v0, .L8003EB0C
    /* 2F304 8003EB04 5555043C */   lui       $a0, (0x55555555 >> 16)
    /* 2F308 8003EB08 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003EB0C:
    /* 2F30C 8003EB0C 55558434 */  ori        $a0, $a0, (0x55555555 & 0xFFFF)
    /* 2F310 8003EB10 00120300 */  sll        $v0, $v1, 8
    /* 2F314 8003EB14 2510E200 */  or         $v0, $a3, $v0
    /* 2F318 8003EB18 FF00033C */  lui        $v1, (0xFF0000 >> 16)
    /* 2F31C 8003EB1C 25104300 */  or         $v0, $v0, $v1
    /* 2F320 8003EB20 F5FFC2AC */  sw         $v0, -0xB($a2)
    /* 2F324 8003EB24 C0FEA224 */  addiu      $v0, $a1, -0x140
    /* 2F328 8003EB28 F1FFC2A4 */  sh         $v0, -0xF($a2)
    /* 2F32C 8003EB2C 4001A224 */  addiu      $v0, $a1, 0x140
    /* 2F330 8003EB30 0100C2A4 */  sh         $v0, 0x1($a2)
    /* 2F334 8003EB34 07000224 */  addiu      $v0, $zero, 0x7
    /* 2F338 8003EB38 ECFFC2A0 */  sb         $v0, -0x14($a2)
    /* 2F33C 8003EB3C 58000224 */  addiu      $v0, $zero, 0x58
    /* 2F340 8003EB40 EDFFCAAC */  sw         $t2, -0x13($a2)
    /* 2F344 8003EB44 FDFFCAAC */  sw         $t2, -0x3($a2)
    /* 2F348 8003EB48 0300C8A4 */  sh         $t0, 0x3($a2)
    /* 2F34C 8003EB4C FBFFC8A4 */  sh         $t0, -0x5($a2)
    /* 2F350 8003EB50 F3FFC8A4 */  sh         $t0, -0xD($a2)
    /* 2F354 8003EB54 F9FFC5A4 */  sh         $a1, -0x7($a2)
    /* 2F358 8003EB58 F0FFC2A0 */  sb         $v0, -0x10($a2)
    /* 2F35C 8003EB5C 0500C4AC */  sw         $a0, 0x5($a2)
    /* 2F360 8003EB60 0000C0A0 */  sb         $zero, 0x0($a2)
    /* 2F364 8003EB64 2000C624 */  addiu      $a2, $a2, 0x20
    /* 2F368 8003EB68 83100B00 */  sra        $v0, $t3, 2
    /* 2F36C 8003EB6C 21586201 */  addu       $t3, $t3, $v0
    /* 2F370 8003EB70 01000825 */  addiu      $t0, $t0, 0x1
    /* 2F374 8003EB74 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2F378 8003EB78 C8D8448C */  lw         $a0, %lo(D_800ED8C8)($v0)
    /* 2F37C 8003EB7C 0000238D */  lw         $v1, 0x0($t1)
    /* 2F380 8003EB80 FC1F828C */  lw         $v0, 0x1FFC($a0)
    /* 2F384 8003EB84 24186D00 */  and        $v1, $v1, $t5
    /* 2F388 8003EB88 24104A00 */  and        $v0, $v0, $t2
    /* 2F38C 8003EB8C 25186200 */  or         $v1, $v1, $v0
    /* 2F390 8003EB90 000023AD */  sw         $v1, 0x0($t1)
    /* 2F394 8003EB94 24182A01 */  and        $v1, $t1, $t2
    /* 2F398 8003EB98 FC1F828C */  lw         $v0, 0x1FFC($a0)
    /* 2F39C 8003EB9C 00000000 */  nop
    /* 2F3A0 8003EBA0 24104D00 */  and        $v0, $v0, $t5
    /* 2F3A4 8003EBA4 25104300 */  or         $v0, $v0, $v1
    /* 2F3A8 8003EBA8 FC1F82AC */  sw         $v0, 0x1FFC($a0)
    /* 2F3AC 8003EBAC FF000229 */  slti       $v0, $t0, 0xFF
    /* 2F3B0 8003EBB0 BEFF4014 */  bnez       $v0, .L8003EAAC
    /* 2F3B4 8003EBB4 20002925 */   addiu     $t1, $t1, 0x20
    /* 2F3B8 8003EBB8 8C00838D */  lw         $v1, (0x1F80008C & 0xFFFF)($t4)
    /* 2F3BC 8003EBBC 0C80023C */  lui        $v0, %hi(D_800BF544)
    /* 2F3C0 8003EBC0 44F549AC */  sw         $t1, %lo(D_800BF544)($v0)
    /* 2F3C4 8003EBC4 40000224 */  addiu      $v0, $zero, 0x40
    /* 2F3C8 8003EBC8 23104300 */  subu       $v0, $v0, $v1
    /* 2F3CC 8003EBCC 43110200 */  sra        $v0, $v0, 5
    /* 2F3D0 8003EBD0 21186200 */  addu       $v1, $v1, $v0
    /* 2F3D4 8003EBD4 FF006330 */  andi       $v1, $v1, 0xFF
    /* 2F3D8 8003EBD8 0800E003 */  jr         $ra
    /* 2F3DC 8003EBDC 8C0083AD */   sw        $v1, (0x1F80008C & 0xFFFF)($t4)
endlabel func_8003EA88

nonmatching func_8003EBE0, 0x2E0

glabel func_8003EBE0
    /* 2F3E0 8003EBE0 B8FFBD27 */  addiu      $sp, $sp, -0x48
    /* 2F3E4 8003EBE4 4400BFAF */  sw         $ra, 0x44($sp)
    /* 2F3E8 8003EBE8 4000BEAF */  sw         $fp, 0x40($sp)
    /* 2F3EC 8003EBEC 3C00B7AF */  sw         $s7, 0x3C($sp)
    /* 2F3F0 8003EBF0 3800B6AF */  sw         $s6, 0x38($sp)
    /* 2F3F4 8003EBF4 3400B5AF */  sw         $s5, 0x34($sp)
    /* 2F3F8 8003EBF8 3000B4AF */  sw         $s4, 0x30($sp)
    /* 2F3FC 8003EBFC 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* 2F400 8003EC00 2800B2AF */  sw         $s2, 0x28($sp)
    /* 2F404 8003EC04 2400B1AF */  sw         $s1, 0x24($sp)
    /* 2F408 8003EC08 0CF8000C */  jal        func_8003E030
    /* 2F40C 8003EC0C 2000B0AF */   sw        $s0, 0x20($sp)
    /* 2F410 8003EC10 801F043C */  lui        $a0, (0x1F800098 >> 16)
    /* 2F414 8003EC14 9800828C */  lw         $v0, (0x1F800098 & 0xFFFF)($a0)
    /* 2F418 8003EC18 00000000 */  nop
    /* 2F41C 8003EC1C 0B004014 */  bnez       $v0, .L8003EC4C
    /* 2F420 8003EC20 801F033C */   lui       $v1, (0x1F800094 >> 16)
    /* 2F424 8003EC24 9400628C */  lw         $v0, (0x1F800094 & 0xFFFF)($v1)
    /* 2F428 8003EC28 00000000 */  nop
    /* 2F42C 8003EC2C 02004224 */  addiu      $v0, $v0, 0x2
    /* 2F430 8003EC30 940062AC */  sw         $v0, (0x1F800094 & 0xFFFF)($v1)
    /* 2F434 8003EC34 00014228 */  slti       $v0, $v0, 0x100
    /* 2F438 8003EC38 0A004014 */  bnez       $v0, .L8003EC64
    /* 2F43C 8003EC3C 801F023C */   lui       $v0, (0x1F800090 >> 16)
    /* 2F440 8003EC40 01000224 */  addiu      $v0, $zero, 0x1
    /* 2F444 8003EC44 18FB0008 */  j          .L8003EC60
    /* 2F448 8003EC48 980082AC */   sw        $v0, (0x1F800098 & 0xFFFF)($a0)
  .L8003EC4C:
    /* 2F44C 8003EC4C 9400628C */  lw         $v0, (0x1F800094 & 0xFFFF)($v1)
    /* 2F450 8003EC50 00000000 */  nop
    /* 2F454 8003EC54 02004018 */  blez       $v0, .L8003EC60
    /* 2F458 8003EC58 FEFF4224 */   addiu     $v0, $v0, -0x2
    /* 2F45C 8003EC5C 940062AC */  sw         $v0, (0x1F800094 & 0xFFFF)($v1)
  .L8003EC60:
    /* 2F460 8003EC60 801F023C */  lui        $v0, (0x1F800090 >> 16)
  .L8003EC64:
    /* 2F464 8003EC64 9000428C */  lw         $v0, (0x1F800090 & 0xFFFF)($v0)
    /* 2F468 8003EC68 801F043C */  lui        $a0, (0x1F80008C >> 16)
    /* 2F46C 8003EC6C E2FF4324 */  addiu      $v1, $v0, -0x1E
    /* 2F470 8003EC70 00016228 */  slti       $v0, $v1, 0x100
    /* 2F474 8003EC74 04004014 */  bnez       $v0, .L8003EC88
    /* 2F478 8003EC78 8C0083AC */   sw        $v1, (0x1F80008C & 0xFFFF)($a0)
    /* 2F47C 8003EC7C FF000224 */  addiu      $v0, $zero, 0xFF
    /* 2F480 8003EC80 25FB0008 */  j          .L8003EC94
    /* 2F484 8003EC84 8C0082AC */   sw        $v0, (0x1F80008C & 0xFFFF)($a0)
  .L8003EC88:
    /* 2F488 8003EC88 03006104 */  bgez       $v1, .L8003EC98
    /* 2F48C 8003EC8C 801F023C */   lui       $v0, (0x1F800090 >> 16)
    /* 2F490 8003EC90 8C0080AC */  sw         $zero, (0x1F80008C & 0xFFFF)($a0)
  .L8003EC94:
    /* 2F494 8003EC94 801F023C */  lui        $v0, (0x1F800090 >> 16)
  .L8003EC98:
    /* 2F498 8003EC98 9000438C */  lw         $v1, (0x1F800090 & 0xFFFF)($v0)
    /* 2F49C 8003EC9C 00000000 */  nop
    /* 2F4A0 8003ECA0 21206000 */  addu       $a0, $v1, $zero
    /* 2F4A4 8003ECA4 01006324 */  addiu      $v1, $v1, 0x1
    /* 2F4A8 8003ECA8 A4018428 */  slti       $a0, $a0, 0x1A4
    /* 2F4AC 8003ECAC 06008014 */  bnez       $a0, .L8003ECC8
    /* 2F4B0 8003ECB0 900043AC */   sw        $v1, (0x1F800090 & 0xFFFF)($v0)
    /* 2F4B4 8003ECB4 01000824 */  addiu      $t0, $zero, 0x1
    /* 2F4B8 8003ECB8 0A80023C */  lui        $v0, %hi(D_800A3B0C)
    /* 2F4BC 8003ECBC 1800A8AF */  sw         $t0, 0x18($sp)
    /* 2F4C0 8003ECC0 33FB0008 */  j          .L8003ECCC
    /* 2F4C4 8003ECC4 0C3B40A0 */   sb        $zero, %lo(D_800A3B0C)($v0)
  .L8003ECC8:
    /* 2F4C8 8003ECC8 1800A0AF */  sw         $zero, 0x18($sp)
  .L8003ECCC:
    /* 2F4CC 8003ECCC 21880000 */  addu       $s1, $zero, $zero
    /* 2F4D0 8003ECD0 801F1E3C */  lui        $fp, (0x1F80008C >> 16)
    /* 2F4D4 8003ECD4 0C80153C */  lui        $s5, %hi(D_800BF544)
    /* 2F4D8 8003ECD8 0F80173C */  lui        $s7, %hi(D_800ED8C8)
  .L8003ECDC:
    /* 2F4DC 8003ECDC 04002016 */  bnez       $s1, .L8003ECF0
    /* 2F4E0 8003ECE0 00010224 */   addiu     $v0, $zero, 0x100
    /* 2F4E4 8003ECE4 8C00C28F */  lw         $v0, (0x1F80008C & 0xFFFF)($fp)
    /* 2F4E8 8003ECE8 40FB0008 */  j          .L8003ED00
    /* 2F4EC 8003ECEC 43200200 */   sra       $a0, $v0, 1
  .L8003ECF0:
    /* 2F4F0 8003ECF0 8C00C38F */  lw         $v1, (0x1F80008C & 0xFFFF)($fp)
    /* 2F4F4 8003ECF4 00000000 */  nop
    /* 2F4F8 8003ECF8 23104300 */  subu       $v0, $v0, $v1
    /* 2F4FC 8003ECFC 43200200 */  sra        $a0, $v0, 1
  .L8003ED00:
    /* 2F500 8003ED00 00140400 */  sll        $v0, $a0, 16
    /* 2F504 8003ED04 001A0400 */  sll        $v1, $a0, 8
    /* 2F508 8003ED08 25104300 */  or         $v0, $v0, $v1
    /* 2F50C 8003ED0C 25B04400 */  or         $s6, $v0, $a0
    /* 2F510 8003ED10 21A00000 */  addu       $s4, $zero, $zero
    /* 2F514 8003ED14 21988002 */  addu       $s3, $s4, $zero
    /* 2F518 8003ED18 21908002 */  addu       $s2, $s4, $zero
  .L8003ED1C:
    /* 2F51C 8003ED1C 0001023C */  lui        $v0, (0x1000080 >> 16)
    /* 2F520 8003ED20 44F5B08E */  lw         $s0, %lo(D_800BF544)($s5)
    /* 2F524 8003ED24 80004234 */  ori        $v0, $v0, (0x1000080 & 0xFFFF)
    /* 2F528 8003ED28 040016AE */  sw         $s6, 0x4($s0)
    /* 2F52C 8003ED2C 100002AE */  sw         $v0, 0x10($s0)
    /* 2F530 8003ED30 0D002016 */  bnez       $s1, .L8003ED68
    /* 2F534 8003ED34 0A0000A6 */   sh        $zero, 0xA($s0)
    /* 2F538 8003ED38 E87F023C */  lui        $v0, (0x7FE80000 >> 16)
    /* 2F53C 8003ED3C 07008016 */  bnez       $s4, .L8003ED5C
    /* 2F540 8003ED40 0C0002AE */   sw        $v0, 0xC($s0)
    /* 2F544 8003ED44 40000224 */  addiu      $v0, $zero, 0x40
    /* 2F548 8003ED48 0C0002A2 */  sb         $v0, 0xC($s0)
    /* 2F54C 8003ED4C 40000224 */  addiu      $v0, $zero, 0x40
    /* 2F550 8003ED50 100002A6 */  sh         $v0, 0x10($s0)
    /* 2F554 8003ED54 5DFB0008 */  j          .L8003ED74
    /* 2F558 8003ED58 080000A6 */   sh        $zero, 0x8($s0)
  .L8003ED5C:
    /* 2F55C 8003ED5C C0FF4226 */  addiu      $v0, $s2, -0x40
    /* 2F560 8003ED60 5DFB0008 */  j          .L8003ED74
    /* 2F564 8003ED64 080002A6 */   sh        $v0, 0x8($s0)
  .L8003ED68:
    /* 2F568 8003ED68 A87F023C */  lui        $v0, (0x7FA80000 >> 16)
    /* 2F56C 8003ED6C 0C0002AE */  sw         $v0, 0xC($s0)
    /* 2F570 8003ED70 080012A6 */  sh         $s2, 0x8($s0)
  .L8003ED74:
    /* 2F574 8003ED74 300F020C */  jal        func_80083CC0
    /* 2F578 8003ED78 21200002 */   addu      $a0, $s0, $zero
    /* 2F57C 8003ED7C 03002016 */  bnez       $s1, .L8003ED8C
    /* 2F580 8003ED80 21200002 */   addu      $a0, $s0, $zero
    /* 2F584 8003ED84 64FB0008 */  j          .L8003ED90
    /* 2F588 8003ED88 01000524 */   addiu     $a1, $zero, 0x1
  .L8003ED8C:
    /* 2F58C 8003ED8C 21280000 */  addu       $a1, $zero, $zero
  .L8003ED90:
    /* 2F590 8003ED90 1C0F020C */  jal        func_80083C70
    /* 2F594 8003ED94 00000000 */   nop
    /* 2F598 8003ED98 21280002 */  addu       $a1, $s0, $zero
    /* 2F59C 8003ED9C C8D8E48E */  lw         $a0, %lo(D_800ED8C8)($s7)
    /* 2F5A0 8003EDA0 0C0F020C */  jal        func_80083C30
    /* 2F5A4 8003EDA4 14001026 */   addiu     $s0, $s0, 0x14
    /* 2F5A8 8003EDA8 03002016 */  bnez       $s1, .L8003EDB8
    /* 2F5AC 8003EDAC 44F5B0AE */   sw        $s0, %lo(D_800BF544)($s5)
    /* 2F5B0 8003EDB0 6FFB0008 */  j          .L8003EDBC
    /* 2F5B4 8003EDB4 C0026726 */   addiu     $a3, $s3, 0x2C0
  .L8003EDB8:
    /* 2F5B8 8003EDB8 40026726 */  addiu      $a3, $s3, 0x240
  .L8003EDBC:
    /* 2F5BC 8003EDBC 01000524 */  addiu      $a1, $zero, 0x1
    /* 2F5C0 8003EDC0 FF03E730 */  andi       $a3, $a3, 0x3FF
    /* 2F5C4 8003EDC4 83390700 */  sra        $a3, $a3, 6
    /* 2F5C8 8003EDC8 2130A000 */  addu       $a2, $a1, $zero
    /* 2F5CC 8003EDCC 44F5B08E */  lw         $s0, %lo(D_800BF544)($s5)
    /* 2F5D0 8003EDD0 B000E734 */  ori        $a3, $a3, 0xB0
    /* 2F5D4 8003EDD4 1000A0AF */  sw         $zero, 0x10($sp)
    /* 2F5D8 8003EDD8 780F020C */  jal        func_80083DE0
    /* 2F5DC 8003EDDC 21200002 */   addu      $a0, $s0, $zero
    /* 2F5E0 8003EDE0 21280002 */  addu       $a1, $s0, $zero
    /* 2F5E4 8003EDE4 C8D8E48E */  lw         $a0, %lo(D_800ED8C8)($s7)
    /* 2F5E8 8003EDE8 0C0F020C */  jal        func_80083C30
    /* 2F5EC 8003EDEC 0C001026 */   addiu     $s0, $s0, 0xC
    /* 2F5F0 8003EDF0 44F5B0AE */  sw         $s0, %lo(D_800BF544)($s5)
    /* 2F5F4 8003EDF4 40007326 */  addiu      $s3, $s3, 0x40
    /* 2F5F8 8003EDF8 01009426 */  addiu      $s4, $s4, 0x1
    /* 2F5FC 8003EDFC 0300822A */  slti       $v0, $s4, 0x3
    /* 2F600 8003EE00 C6FF4014 */  bnez       $v0, .L8003ED1C
    /* 2F604 8003EE04 80005226 */   addiu     $s2, $s2, 0x80
    /* 2F608 8003EE08 01003126 */  addiu      $s1, $s1, 0x1
    /* 2F60C 8003EE0C 0200222A */  slti       $v0, $s1, 0x2
    /* 2F610 8003EE10 B2FF4014 */  bnez       $v0, .L8003ECDC
    /* 2F614 8003EE14 0A80023C */   lui       $v0, %hi(D_800A3B0C)
    /* 2F618 8003EE18 0C3B4390 */  lbu        $v1, %lo(D_800A3B0C)($v0)
    /* 2F61C 8003EE1C 00000000 */  nop
    /* 2F620 8003EE20 03006228 */  slti       $v0, $v1, 0x3
    /* 2F624 8003EE24 19004010 */  beqz       $v0, .L8003EE8C
    /* 2F628 8003EE28 00000000 */   nop
    /* 2F62C 8003EE2C 17006010 */  beqz       $v1, .L8003EE8C
    /* 2F630 8003EE30 0C80113C */   lui       $s1, %hi(D_800BF544)
    /* 2F634 8003EE34 44F5308E */  lw         $s0, %lo(D_800BF544)($s1)
    /* 2F638 8003EE38 01000524 */  addiu      $a1, $zero, 0x1
    /* 2F63C 8003EE3C 6C0F020C */  jal        func_80083DB0
    /* 2F640 8003EE40 21200002 */   addu      $a0, $s0, $zero
    /* 2F644 8003EE44 FF00043C */  lui        $a0, (0xFFFFFF >> 16)
    /* 2F648 8003EE48 FFFF8434 */  ori        $a0, $a0, (0xFFFFFF & 0xFFFF)
    /* 2F64C 8003EE4C 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2F650 8003EE50 00FF063C */  lui        $a2, (0xFF000000 >> 16)
    /* 2F654 8003EE54 C8D8458C */  lw         $a1, %lo(D_800ED8C8)($v0)
    /* 2F658 8003EE58 0000038E */  lw         $v1, 0x0($s0)
    /* 2F65C 8003EE5C FC1FA28C */  lw         $v0, 0x1FFC($a1)
    /* 2F660 8003EE60 24186600 */  and        $v1, $v1, $a2
    /* 2F664 8003EE64 24104400 */  and        $v0, $v0, $a0
    /* 2F668 8003EE68 25186200 */  or         $v1, $v1, $v0
    /* 2F66C 8003EE6C 24200402 */  and        $a0, $s0, $a0
    /* 2F670 8003EE70 000003AE */  sw         $v1, 0x0($s0)
    /* 2F674 8003EE74 FC1FA28C */  lw         $v0, 0x1FFC($a1)
    /* 2F678 8003EE78 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2F67C 8003EE7C 44F530AE */  sw         $s0, %lo(D_800BF544)($s1)
    /* 2F680 8003EE80 24104600 */  and        $v0, $v0, $a2
    /* 2F684 8003EE84 25104400 */  or         $v0, $v0, $a0
    /* 2F688 8003EE88 FC1FA2AC */  sw         $v0, 0x1FFC($a1)
  .L8003EE8C:
    /* 2F68C 8003EE8C 1800A28F */  lw         $v0, 0x18($sp)
    /* 2F690 8003EE90 4400BF8F */  lw         $ra, 0x44($sp)
    /* 2F694 8003EE94 4000BE8F */  lw         $fp, 0x40($sp)
    /* 2F698 8003EE98 3C00B78F */  lw         $s7, 0x3C($sp)
    /* 2F69C 8003EE9C 3800B68F */  lw         $s6, 0x38($sp)
    /* 2F6A0 8003EEA0 3400B58F */  lw         $s5, 0x34($sp)
    /* 2F6A4 8003EEA4 3000B48F */  lw         $s4, 0x30($sp)
    /* 2F6A8 8003EEA8 2C00B38F */  lw         $s3, 0x2C($sp)
    /* 2F6AC 8003EEAC 2800B28F */  lw         $s2, 0x28($sp)
    /* 2F6B0 8003EEB0 2400B18F */  lw         $s1, 0x24($sp)
    /* 2F6B4 8003EEB4 2000B08F */  lw         $s0, 0x20($sp)
    /* 2F6B8 8003EEB8 0800E003 */  jr         $ra
    /* 2F6BC 8003EEBC 4800BD27 */   addiu     $sp, $sp, 0x48
endlabel func_8003EBE0
