.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8003B704, 0x44C

glabel func_8003B704
    /* 2BF04 8003B704 68FFBD27 */  addiu      $sp, $sp, -0x98
    /* 2BF08 8003B708 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 2BF0C 8003B70C 1700A2A3 */  sb         $v0, 0x17($sp)
    /* 2BF10 8003B710 05000224 */  addiu      $v0, $zero, 0x5
    /* 2BF14 8003B714 2600A2A7 */  sh         $v0, 0x26($sp)
    /* 2BF18 8003B718 9F3E0224 */  addiu      $v0, $zero, 0x3E9F
    /* 2BF1C 8003B71C 1E00A2A7 */  sh         $v0, 0x1E($sp)
    /* 2BF20 8003B720 E0000224 */  addiu      $v0, $zero, 0xE0
    /* 2BF24 8003B724 2C00A2A3 */  sb         $v0, 0x2C($sp)
    /* 2BF28 8003B728 1C00A2A3 */  sb         $v0, 0x1C($sp)
    /* 2BF2C 8003B72C F7000224 */  addiu      $v0, $zero, 0xF7
    /* 2BF30 8003B730 0A80033C */  lui        $v1, %hi(D_800A3B04)
    /* 2BF34 8003B734 21C88000 */  addu       $t9, $a0, $zero
    /* 2BF38 8003B738 9400BFAF */  sw         $ra, 0x94($sp)
    /* 2BF3C 8003B73C 9000BEAF */  sw         $fp, 0x90($sp)
    /* 2BF40 8003B740 8C00B7AF */  sw         $s7, 0x8C($sp)
    /* 2BF44 8003B744 8800B6AF */  sw         $s6, 0x88($sp)
    /* 2BF48 8003B748 8400B5AF */  sw         $s5, 0x84($sp)
    /* 2BF4C 8003B74C 8000B4AF */  sw         $s4, 0x80($sp)
    /* 2BF50 8003B750 7C00B3AF */  sw         $s3, 0x7C($sp)
    /* 2BF54 8003B754 7800B2AF */  sw         $s2, 0x78($sp)
    /* 2BF58 8003B758 7400B1AF */  sw         $s1, 0x74($sp)
    /* 2BF5C 8003B75C 7000B0AF */  sw         $s0, 0x70($sp)
    /* 2BF60 8003B760 9800A4AF */  sw         $a0, 0x98($sp)
    /* 2BF64 8003B764 3400A2A3 */  sb         $v0, 0x34($sp)
    /* 2BF68 8003B768 2400A2A3 */  sb         $v0, 0x24($sp)
    /* 2BF6C 8003B76C 66002287 */  lh         $v0, 0x66($t9)
    /* 2BF70 8003B770 043B6324 */  addiu      $v1, $v1, %lo(D_800A3B04)
    /* 2BF74 8003B774 40100200 */  sll        $v0, $v0, 1
    /* 2BF78 8003B778 21104300 */  addu       $v0, $v0, $v1
    /* 2BF7C 8003B77C 00004290 */  lbu        $v0, 0x0($v0)
    /* 2BF80 8003B780 00000000 */  nop
    /* 2BF84 8003B784 2500A2A3 */  sb         $v0, 0x25($sp)
    /* 2BF88 8003B788 1D00A2A3 */  sb         $v0, 0x1D($sp)
    /* 2BF8C 8003B78C 66002287 */  lh         $v0, 0x66($t9)
    /* 2BF90 8003B790 60003027 */  addiu      $s0, $t9, 0x60
    /* 2BF94 8003B794 40100200 */  sll        $v0, $v0, 1
    /* 2BF98 8003B798 21104300 */  addu       $v0, $v0, $v1
    /* 2BF9C 8003B79C 01004290 */  lbu        $v0, 0x1($v0)
    /* 2BFA0 8003B7A0 00000000 */  nop
    /* 2BFA4 8003B7A4 3500A2A3 */  sb         $v0, 0x35($sp)
    /* 2BFA8 8003B7A8 2D00A2A3 */  sb         $v0, 0x2D($sp)
    /* 2BFAC 8003B7AC 0E80023C */  lui        $v0, %hi(D_800E7E80)
    /* 2BFB0 8003B7B0 807E4224 */  addiu      $v0, $v0, %lo(D_800E7E80)
    /* 2BFB4 8003B7B4 46014390 */  lbu        $v1, 0x146($v0)
    /* 2BFB8 8003B7B8 DC00538C */  lw         $s3, 0xDC($v0)
    /* 2BFBC 8003B7BC 0400632C */  sltiu      $v1, $v1, 0x4
    /* 2BFC0 8003B7C0 09006014 */  bnez       $v1, .L8003B7E8
    /* 2BFC4 8003B7C4 14001224 */   addiu     $s2, $zero, 0x14
    /* 2BFC8 8003B7C8 0A000486 */  lh         $a0, 0xA($s0)
    /* 2BFCC 8003B7CC D40F020C */  jal        func_80083F50
    /* 2BFD0 8003B7D0 00000000 */   nop
    /* 2BFD4 8003B7D4 18005200 */  mult       $v0, $s2
    /* 2BFD8 8003B7D8 0A000486 */  lh         $a0, 0xA($s0)
    /* 2BFDC 8003B7DC 12880000 */  mflo       $s1
    /* 2BFE0 8003B7E0 01EE0008 */  j          .L8003B804
    /* 2BFE4 8003B7E4 00000000 */   nop
  .L8003B7E8:
    /* 2BFE8 8003B7E8 0A000486 */  lh         $a0, 0xA($s0)
    /* 2BFEC 8003B7EC D40F020C */  jal        func_80083F50
    /* 2BFF0 8003B7F0 00048424 */   addiu     $a0, $a0, 0x400
    /* 2BFF4 8003B7F4 18005200 */  mult       $v0, $s2
    /* 2BFF8 8003B7F8 0A000486 */  lh         $a0, 0xA($s0)
    /* 2BFFC 8003B7FC 12880000 */  mflo       $s1
    /* 2C000 8003B800 00048424 */  addiu      $a0, $a0, 0x400
  .L8003B804:
    /* 2C004 8003B804 A00F020C */  jal        func_80083E80
    /* 2C008 8003B808 00000000 */   nop
    /* 2C00C 8003B80C 18005200 */  mult       $v0, $s2
    /* 2C010 8003B810 12F00000 */  mflo       $fp
    /* 2C014 8003B814 08000486 */  lh         $a0, 0x8($s0)
    /* 2C018 8003B818 D40F020C */  jal        func_80083F50
    /* 2C01C 8003B81C 03F31E00 */   sra       $fp, $fp, 12
    /* 2C020 8003B820 18005100 */  mult       $v0, $s1
    /* 2C024 8003B824 08000486 */  lh         $a0, 0x8($s0)
    /* 2C028 8003B828 12900000 */  mflo       $s2
    /* 2C02C 8003B82C A00F020C */  jal        func_80083E80
    /* 2C030 8003B830 801F103C */   lui       $s0, %hi(D_1F8000F8)
    /* 2C034 8003B834 23100200 */  negu       $v0, $v0
    /* 2C038 8003B838 18005100 */  mult       $v0, $s1
    /* 2C03C 8003B83C F8001026 */  addiu      $s0, $s0, %lo(D_1F8000F8)
    /* 2C040 8003B840 21200002 */  addu       $a0, $s0, $zero
    /* 2C044 8003B844 12180000 */  mflo       $v1
    /* 2C048 8003B848 031E0300 */  sra        $v1, $v1, 24
    /* 2C04C 8003B84C 9811020C */  jal        func_80084660
    /* 2C050 8003B850 5800A3AF */   sw        $v1, 0x58($sp)
    /* 2C054 8003B854 A411020C */  jal        func_80084690
    /* 2C058 8003B858 21200002 */   addu      $a0, $s0, $zero
    /* 2C05C 8003B85C 9800B98F */  lw         $t9, 0x98($sp)
    /* 2C060 8003B860 00000000 */  nop
    /* 2C064 8003B864 60002387 */  lh         $v1, 0x60($t9)
    /* 2C068 8003B868 03000224 */  addiu      $v0, $zero, 0x3
    /* 2C06C 8003B86C 75006214 */  bne        $v1, $v0, .L8003BA44
    /* 2C070 8003B870 03C61200 */   sra       $t8, $s2, 24
    /* 2C074 8003B874 2E002287 */  lh         $v0, 0x2E($t9)
    /* 2C078 8003B878 32002387 */  lh         $v1, 0x32($t9)
    /* 2C07C 8003B87C 36002487 */  lh         $a0, 0x36($t9)
    /* 2C080 8003B880 3800B927 */  addiu      $t9, $sp, 0x38
    /* 2C084 8003B884 21282003 */  addu       $a1, $t9, $zero
    /* 2C088 8003B888 21300000 */  addu       $a2, $zero, $zero
    /* 2C08C 8003B88C 2C006A96 */  lhu        $t2, 0x2C($s3)
    /* 2C090 8003B890 2C00728E */  lw         $s2, 0x2C($s3)
    /* 2C094 8003B894 3000718E */  lw         $s1, 0x30($s3)
    /* 2C098 8003B898 3400708E */  lw         $s0, 0x34($s3)
    /* 2C09C 8003B89C 21904202 */  addu       $s2, $s2, $v0
    /* 2C0A0 8003B8A0 C2171200 */  srl        $v0, $s2, 31
    /* 2C0A4 8003B8A4 21904202 */  addu       $s2, $s2, $v0
    /* 2C0A8 8003B8A8 43901200 */  sra        $s2, $s2, 1
    /* 2C0AC 8003B8AC 21882302 */  addu       $s1, $s1, $v1
    /* 2C0B0 8003B8B0 C2171100 */  srl        $v0, $s1, 31
    /* 2C0B4 8003B8B4 21882202 */  addu       $s1, $s1, $v0
    /* 2C0B8 8003B8B8 43881100 */  sra        $s1, $s1, 1
    /* 2C0BC 8003B8BC 21800402 */  addu       $s0, $s0, $a0
    /* 2C0C0 8003B8C0 C2171000 */  srl        $v0, $s0, 31
    /* 2C0C4 8003B8C4 21800202 */  addu       $s0, $s0, $v0
    /* 2C0C8 8003B8C8 43801000 */  sra        $s0, $s0, 1
    /* 2C0CC 8003B8CC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 2C0D0 8003B8D0 3800AAA7 */  sh         $t2, 0x38($sp)
    /* 2C0D4 8003B8D4 23505801 */  subu       $t2, $t2, $t8
    /* 2C0D8 8003B8D8 30006996 */  lhu        $t1, 0x30($s3)
    /* 2C0DC 8003B8DC 23B83E02 */  subu       $s7, $s1, $fp
    /* 2C0E0 8003B8E0 3A00A9A7 */  sh         $t1, 0x3A($sp)
    /* 2C0E4 8003B8E4 34006896 */  lhu        $t0, 0x34($s3)
    /* 2C0E8 8003B8E8 21A85802 */  addu       $s5, $s2, $t8
    /* 2C0EC 8003B8EC 4000B2A7 */  sh         $s2, 0x40($sp)
    /* 2C0F0 8003B8F0 4200B1A7 */  sh         $s1, 0x42($sp)
    /* 2C0F4 8003B8F4 4400B0A7 */  sh         $s0, 0x44($sp)
    /* 2C0F8 8003B8F8 3C00A8A7 */  sh         $t0, 0x3C($sp)
    /* 2C0FC 8003B8FC 2C006796 */  lhu        $a3, 0x2C($s3)
    /* 2C100 8003B900 21A03E02 */  addu       $s4, $s1, $fp
    /* 2C104 8003B904 6000B9AF */  sw         $t9, 0x60($sp)
    /* 2C108 8003B908 5800B98F */  lw         $t9, 0x58($sp)
    /* 2C10C 8003B90C 23483E01 */  subu       $t1, $t1, $fp
    /* 2C110 8003B910 23401901 */  subu       $t0, $t0, $t9
    /* 2C114 8003B914 4800A7A7 */  sh         $a3, 0x48($sp)
    /* 2C118 8003B918 30006296 */  lhu        $v0, 0x30($s3)
    /* 2C11C 8003B91C 23C85802 */  subu       $t9, $s2, $t8
    /* 2C120 8003B920 4A00A2A7 */  sh         $v0, 0x4A($sp)
    /* 2C124 8003B924 34006396 */  lhu        $v1, 0x34($s3)
    /* 2C128 8003B928 2138F800 */  addu       $a3, $a3, $t8
    /* 2C12C 8003B92C 5C00B9AF */  sw         $t9, 0x5C($sp)
    /* 2C130 8003B930 5C00B997 */  lhu        $t9, 0x5C($sp)
    /* 2C134 8003B934 00000000 */  nop
    /* 2C138 8003B938 4000B9A7 */  sh         $t9, 0x40($sp)
    /* 2C13C 8003B93C 5800B98F */  lw         $t9, 0x58($sp)
    /* 2C140 8003B940 21105E00 */  addu       $v0, $v0, $fp
    /* 2C144 8003B944 5000B2A7 */  sh         $s2, 0x50($sp)
    /* 2C148 8003B948 5200B1A7 */  sh         $s1, 0x52($sp)
    /* 2C14C 8003B94C 5400B0A7 */  sh         $s0, 0x54($sp)
    /* 2C150 8003B950 3800AAA7 */  sh         $t2, 0x38($sp)
    /* 2C154 8003B954 3A00A9A7 */  sh         $t1, 0x3A($sp)
    /* 2C158 8003B958 3C00A8A7 */  sh         $t0, 0x3C($sp)
    /* 2C15C 8003B95C 4200B7A7 */  sh         $s7, 0x42($sp)
    /* 2C160 8003B960 23B01902 */  subu       $s6, $s0, $t9
    /* 2C164 8003B964 4400B6A7 */  sh         $s6, 0x44($sp)
    /* 2C168 8003B968 4C00A3A7 */  sh         $v1, 0x4C($sp)
    /* 2C16C 8003B96C 21187900 */  addu       $v1, $v1, $t9
    /* 2C170 8003B970 21981902 */  addu       $s3, $s0, $t9
    /* 2C174 8003B974 4800A7A7 */  sh         $a3, 0x48($sp)
    /* 2C178 8003B978 4A00A2A7 */  sh         $v0, 0x4A($sp)
    /* 2C17C 8003B97C 4C00A3A7 */  sh         $v1, 0x4C($sp)
    /* 2C180 8003B980 5000B5A7 */  sh         $s5, 0x50($sp)
    /* 2C184 8003B984 5200B4A7 */  sh         $s4, 0x52($sp)
    /* 2C188 8003B988 5400B3A7 */  sh         $s3, 0x54($sp)
    /* 2C18C 8003B98C C8EC000C */  jal        func_8003B320
    /* 2C190 8003B990 6800B8AF */   sw        $t8, 0x68($sp)
    /* 2C194 8003B994 9800B98F */  lw         $t9, 0x98($sp)
    /* 2C198 8003B998 6000A58F */  lw         $a1, 0x60($sp)
    /* 2C19C 8003B99C 6800B88F */  lw         $t8, 0x68($sp)
    /* 2C1A0 8003B9A0 3800B2A7 */  sh         $s2, 0x38($sp)
    /* 2C1A4 8003B9A4 3A00B1A7 */  sh         $s1, 0x3A($sp)
    /* 2C1A8 8003B9A8 3C00B0A7 */  sh         $s0, 0x3C($sp)
    /* 2C1AC 8003B9AC 2E002797 */  lhu        $a3, 0x2E($t9)
    /* 2C1B0 8003B9B0 1000A427 */  addiu      $a0, $sp, 0x10
    /* 2C1B4 8003B9B4 4000A7A7 */  sh         $a3, 0x40($sp)
    /* 2C1B8 8003B9B8 32002897 */  lhu        $t0, 0x32($t9)
    /* 2C1BC 8003B9BC 21300000 */  addu       $a2, $zero, $zero
    /* 2C1C0 8003B9C0 4200A8A7 */  sh         $t0, 0x42($sp)
    /* 2C1C4 8003B9C4 36002997 */  lhu        $t1, 0x36($t9)
    /* 2C1C8 8003B9C8 4800B2A7 */  sh         $s2, 0x48($sp)
    /* 2C1CC 8003B9CC 4A00B1A7 */  sh         $s1, 0x4A($sp)
    /* 2C1D0 8003B9D0 4C00B0A7 */  sh         $s0, 0x4C($sp)
    /* 2C1D4 8003B9D4 4400A9A7 */  sh         $t1, 0x44($sp)
    /* 2C1D8 8003B9D8 2E002A97 */  lhu        $t2, 0x2E($t9)
    /* 2C1DC 8003B9DC 2338F800 */  subu       $a3, $a3, $t8
    /* 2C1E0 8003B9E0 5000AAA7 */  sh         $t2, 0x50($sp)
    /* 2C1E4 8003B9E4 32002297 */  lhu        $v0, 0x32($t9)
    /* 2C1E8 8003B9E8 23401E01 */  subu       $t0, $t0, $fp
    /* 2C1EC 8003B9EC 5200A2A7 */  sh         $v0, 0x52($sp)
    /* 2C1F0 8003B9F0 36002397 */  lhu        $v1, 0x36($t9)
    /* 2C1F4 8003B9F4 5C00B997 */  lhu        $t9, 0x5C($sp)
    /* 2C1F8 8003B9F8 21505801 */  addu       $t2, $t2, $t8
    /* 2C1FC 8003B9FC 3800B9A7 */  sh         $t9, 0x38($sp)
    /* 2C200 8003BA00 5800B98F */  lw         $t9, 0x58($sp)
    /* 2C204 8003BA04 21105E00 */  addu       $v0, $v0, $fp
    /* 2C208 8003BA08 3A00B7A7 */  sh         $s7, 0x3A($sp)
    /* 2C20C 8003BA0C 3C00B6A7 */  sh         $s6, 0x3C($sp)
    /* 2C210 8003BA10 4000A7A7 */  sh         $a3, 0x40($sp)
    /* 2C214 8003BA14 4200A8A7 */  sh         $t0, 0x42($sp)
    /* 2C218 8003BA18 4800B5A7 */  sh         $s5, 0x48($sp)
    /* 2C21C 8003BA1C 23483901 */  subu       $t1, $t1, $t9
    /* 2C220 8003BA20 4400A9A7 */  sh         $t1, 0x44($sp)
    /* 2C224 8003BA24 4A00B4A7 */  sh         $s4, 0x4A($sp)
    /* 2C228 8003BA28 5400A3A7 */  sh         $v1, 0x54($sp)
    /* 2C22C 8003BA2C 21187900 */  addu       $v1, $v1, $t9
    /* 2C230 8003BA30 4C00B3A7 */  sh         $s3, 0x4C($sp)
    /* 2C234 8003BA34 5000AAA7 */  sh         $t2, 0x50($sp)
    /* 2C238 8003BA38 5200A2A7 */  sh         $v0, 0x52($sp)
    /* 2C23C 8003BA3C C6EE0008 */  j          .L8003BB18
    /* 2C240 8003BA40 5400A3A7 */   sh        $v1, 0x54($sp)
  .L8003BA44:
    /* 2C244 8003BA44 2C006796 */  lhu        $a3, 0x2C($s3)
    /* 2C248 8003BA48 9800B98F */  lw         $t9, 0x98($sp)
    /* 2C24C 8003BA4C 3800A7A7 */  sh         $a3, 0x38($sp)
    /* 2C250 8003BA50 30006896 */  lhu        $t0, 0x30($s3)
    /* 2C254 8003BA54 1000A427 */  addiu      $a0, $sp, 0x10
    /* 2C258 8003BA58 3A00A8A7 */  sh         $t0, 0x3A($sp)
    /* 2C25C 8003BA5C 34006996 */  lhu        $t1, 0x34($s3)
    /* 2C260 8003BA60 3800A527 */  addiu      $a1, $sp, 0x38
    /* 2C264 8003BA64 3C00A9A7 */  sh         $t1, 0x3C($sp)
    /* 2C268 8003BA68 2E002A97 */  lhu        $t2, 0x2E($t9)
    /* 2C26C 8003BA6C 21300000 */  addu       $a2, $zero, $zero
    /* 2C270 8003BA70 4000AAA7 */  sh         $t2, 0x40($sp)
    /* 2C274 8003BA74 32002B97 */  lhu        $t3, 0x32($t9)
    /* 2C278 8003BA78 2338F800 */  subu       $a3, $a3, $t8
    /* 2C27C 8003BA7C 4200ABA7 */  sh         $t3, 0x42($sp)
    /* 2C280 8003BA80 36002C97 */  lhu        $t4, 0x36($t9)
    /* 2C284 8003BA84 23401E01 */  subu       $t0, $t0, $fp
    /* 2C288 8003BA88 4400ACA7 */  sh         $t4, 0x44($sp)
    /* 2C28C 8003BA8C 2C006D96 */  lhu        $t5, 0x2C($s3)
    /* 2C290 8003BA90 23505801 */  subu       $t2, $t2, $t8
    /* 2C294 8003BA94 4800ADA7 */  sh         $t5, 0x48($sp)
    /* 2C298 8003BA98 30006E96 */  lhu        $t6, 0x30($s3)
    /* 2C29C 8003BA9C 23587E01 */  subu       $t3, $t3, $fp
    /* 2C2A0 8003BAA0 4A00AEA7 */  sh         $t6, 0x4A($sp)
    /* 2C2A4 8003BAA4 34006F96 */  lhu        $t7, 0x34($s3)
    /* 2C2A8 8003BAA8 2168B801 */  addu       $t5, $t5, $t8
    /* 2C2AC 8003BAAC 4C00AFA7 */  sh         $t7, 0x4C($sp)
    /* 2C2B0 8003BAB0 2E003097 */  lhu        $s0, 0x2E($t9)
    /* 2C2B4 8003BAB4 2170DE01 */  addu       $t6, $t6, $fp
    /* 2C2B8 8003BAB8 5000B0A7 */  sh         $s0, 0x50($sp)
    /* 2C2BC 8003BABC 32002397 */  lhu        $v1, 0x32($t9)
    /* 2C2C0 8003BAC0 21801802 */  addu       $s0, $s0, $t8
    /* 2C2C4 8003BAC4 5200A3A7 */  sh         $v1, 0x52($sp)
    /* 2C2C8 8003BAC8 36002297 */  lhu        $v0, 0x36($t9)
    /* 2C2CC 8003BACC 5800B98F */  lw         $t9, 0x58($sp)
    /* 2C2D0 8003BAD0 21187E00 */  addu       $v1, $v1, $fp
    /* 2C2D4 8003BAD4 3800A7A7 */  sh         $a3, 0x38($sp)
    /* 2C2D8 8003BAD8 3A00A8A7 */  sh         $t0, 0x3A($sp)
    /* 2C2DC 8003BADC 4000AAA7 */  sh         $t2, 0x40($sp)
    /* 2C2E0 8003BAE0 4200ABA7 */  sh         $t3, 0x42($sp)
    /* 2C2E4 8003BAE4 4800ADA7 */  sh         $t5, 0x48($sp)
    /* 2C2E8 8003BAE8 23483901 */  subu       $t1, $t1, $t9
    /* 2C2EC 8003BAEC 23609901 */  subu       $t4, $t4, $t9
    /* 2C2F0 8003BAF0 2178F901 */  addu       $t7, $t7, $t9
    /* 2C2F4 8003BAF4 3C00A9A7 */  sh         $t1, 0x3C($sp)
    /* 2C2F8 8003BAF8 4400ACA7 */  sh         $t4, 0x44($sp)
    /* 2C2FC 8003BAFC 4A00AEA7 */  sh         $t6, 0x4A($sp)
    /* 2C300 8003BB00 5400A2A7 */  sh         $v0, 0x54($sp)
    /* 2C304 8003BB04 21105900 */  addu       $v0, $v0, $t9
    /* 2C308 8003BB08 4C00AFA7 */  sh         $t7, 0x4C($sp)
    /* 2C30C 8003BB0C 5000B0A7 */  sh         $s0, 0x50($sp)
    /* 2C310 8003BB10 5200A3A7 */  sh         $v1, 0x52($sp)
    /* 2C314 8003BB14 5400A2A7 */  sh         $v0, 0x54($sp)
  .L8003BB18:
    /* 2C318 8003BB18 C8EC000C */  jal        func_8003B320
    /* 2C31C 8003BB1C 00000000 */   nop
    /* 2C320 8003BB20 9400BF8F */  lw         $ra, 0x94($sp)
    /* 2C324 8003BB24 9000BE8F */  lw         $fp, 0x90($sp)
    /* 2C328 8003BB28 8C00B78F */  lw         $s7, 0x8C($sp)
    /* 2C32C 8003BB2C 8800B68F */  lw         $s6, 0x88($sp)
    /* 2C330 8003BB30 8400B58F */  lw         $s5, 0x84($sp)
    /* 2C334 8003BB34 8000B48F */  lw         $s4, 0x80($sp)
    /* 2C338 8003BB38 7C00B38F */  lw         $s3, 0x7C($sp)
    /* 2C33C 8003BB3C 7800B28F */  lw         $s2, 0x78($sp)
    /* 2C340 8003BB40 7400B18F */  lw         $s1, 0x74($sp)
    /* 2C344 8003BB44 7000B08F */  lw         $s0, 0x70($sp)
    /* 2C348 8003BB48 0800E003 */  jr         $ra
    /* 2C34C 8003BB4C 9800BD27 */   addiu     $sp, $sp, 0x98
endlabel func_8003B704
