.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8003EF9C, 0x88

glabel func_8003EF9C
    /* 2F79C 8003EF9C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2F7A0 8003EFA0 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2F7A4 8003EFA4 21908000 */  addu       $s2, $a0, $zero
    /* 2F7A8 8003EFA8 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 2F7AC 8003EFAC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2F7B0 8003EFB0 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2F7B4 8003EFB4 0B004292 */  lbu        $v0, 0xB($s2)
    /* 2F7B8 8003EFB8 0D004392 */  lbu        $v1, 0xD($s2)
    /* 2F7BC 8003EFBC 0F004238 */  xori       $v0, $v0, 0xF
    /* 2F7C0 8003EFC0 0F006330 */  andi       $v1, $v1, 0xF
    /* 2F7C4 8003EFC4 06006010 */  beqz       $v1, .L8003EFE0
    /* 2F7C8 8003EFC8 0100452C */   sltiu     $a1, $v0, 0x1
    /* 2F7CC 8003EFCC 02000224 */  addiu      $v0, $zero, 0x2
    /* 2F7D0 8003EFD0 07006210 */  beq        $v1, $v0, .L8003EFF0
    /* 2F7D4 8003EFD4 0C80103C */   lui       $s0, %hi(D_800BF544)
    /* 2F7D8 8003EFD8 03FC0008 */  j          .L8003F00C
    /* 2F7DC 8003EFDC 00000000 */   nop
  .L8003EFE0:
    /* 2F7E0 8003EFE0 1FFC000C */  jal        func_8003F07C
    /* 2F7E4 8003EFE4 21204002 */   addu      $a0, $s2, $zero
    /* 2F7E8 8003EFE8 03FC0008 */  j          .L8003F00C
    /* 2F7EC 8003EFEC 00000000 */   nop
  .L8003EFF0:
    /* 2F7F0 8003EFF0 44F5118E */  lw         $s1, %lo(D_800BF544)($s0)
    /* 2F7F4 8003EFF4 1FFC000C */  jal        func_8003F07C
    /* 2F7F8 8003EFF8 21204002 */   addu      $a0, $s2, $zero
    /* 2F7FC 8003EFFC 21204002 */  addu       $a0, $s2, $zero
    /* 2F800 8003F000 44F5068E */  lw         $a2, %lo(D_800BF544)($s0)
    /* 2F804 8003F004 61F5000C */  jal        func_8003D584
    /* 2F808 8003F008 21282002 */   addu      $a1, $s1, $zero
  .L8003F00C:
    /* 2F80C 8003F00C 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 2F810 8003F010 1800B28F */  lw         $s2, 0x18($sp)
    /* 2F814 8003F014 1400B18F */  lw         $s1, 0x14($sp)
    /* 2F818 8003F018 1000B08F */  lw         $s0, 0x10($sp)
    /* 2F81C 8003F01C 0800E003 */  jr         $ra
    /* 2F820 8003F020 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_8003EF9C

nonmatching func_8003F024, 0x58

glabel func_8003F024
    /* 2F824 8003F024 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2F828 8003F028 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2F82C 8003F02C 21880000 */  addu       $s1, $zero, $zero
    /* 2F830 8003F030 0F80023C */  lui        $v0, %hi(D_800EC188)
    /* 2F834 8003F034 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2F838 8003F038 88C15024 */  addiu      $s0, $v0, %lo(D_800EC188)
    /* 2F83C 8003F03C 1800BFAF */  sw         $ra, 0x18($sp)
  .L8003F040:
    /* 2F840 8003F040 00000292 */  lbu        $v0, 0x0($s0)
    /* 2F844 8003F044 00000000 */  nop
    /* 2F848 8003F048 03004010 */  beqz       $v0, .L8003F058
    /* 2F84C 8003F04C 00000000 */   nop
    /* 2F850 8003F050 8FF4000C */  jal        func_8003D23C
    /* 2F854 8003F054 21200002 */   addu      $a0, $s0, $zero
  .L8003F058:
    /* 2F858 8003F058 01003126 */  addiu      $s1, $s1, 0x1
    /* 2F85C 8003F05C 2800222A */  slti       $v0, $s1, 0x28
    /* 2F860 8003F060 F7FF4014 */  bnez       $v0, .L8003F040
    /* 2F864 8003F064 40001026 */   addiu     $s0, $s0, 0x40
    /* 2F868 8003F068 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2F86C 8003F06C 1400B18F */  lw         $s1, 0x14($sp)
    /* 2F870 8003F070 1000B08F */  lw         $s0, 0x10($sp)
    /* 2F874 8003F074 0800E003 */  jr         $ra
    /* 2F878 8003F078 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_8003F024

/* Handwritten function */
nonmatching func_8003F07C, 0xF8

glabel func_8003F07C
    /* 2F87C 8003F07C D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2F880 8003F080 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2F884 8003F084 21908000 */  addu       $s2, $a0, $zero
    /* 2F888 8003F088 2400BFAF */  sw         $ra, 0x24($sp)
    /* 2F88C 8003F08C 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2F890 8003F090 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2F894 8003F094 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2F898 8003F098 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2F89C 8003F09C 08004292 */  lbu        $v0, 0x8($s2)
    /* 2F8A0 8003F0A0 00000000 */  nop
    /* 2F8A4 8003F0A4 2B004010 */  beqz       $v0, .L8003F154
    /* 2F8A8 8003F0A8 21A0A000 */   addu      $s4, $a1, $zero
    /* 2F8AC 8003F0AC 801F033C */  lui        $v1, %hi(D_1F8000F8)
    /* 2F8B0 8003F0B0 F8006324 */  addiu      $v1, $v1, %lo(D_1F8000F8)
    /* 2F8B4 8003F0B4 00006C8C */  lw         $t4, 0x0($v1)
    /* 2F8B8 8003F0B8 04006D8C */  lw         $t5, 0x4($v1)
    /* 2F8BC 8003F0BC 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2F8C0 8003F0C0 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2F8C4 8003F0C4 08006C8C */  lw         $t4, 0x8($v1)
    /* 2F8C8 8003F0C8 0C006D8C */  lw         $t5, 0xC($v1)
    /* 2F8CC 8003F0CC 10006E8C */  lw         $t6, 0x10($v1)
    /* 2F8D0 8003F0D0 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2F8D4 8003F0D4 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2F8D8 8003F0D8 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2F8DC 8003F0DC 801F033C */  lui        $v1, %hi(D_1F8000F8)
    /* 2F8E0 8003F0E0 F8006324 */  addiu      $v1, $v1, %lo(D_1F8000F8)
    /* 2F8E4 8003F0E4 14006C8C */  lw         $t4, 0x14($v1)
    /* 2F8E8 8003F0E8 18006D8C */  lw         $t5, 0x18($v1)
    /* 2F8EC 8003F0EC 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2F8F0 8003F0F0 1C006E8C */  lw         $t6, 0x1C($v1)
    /* 2F8F4 8003F0F4 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2F8F8 8003F0F8 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2F8FC 8003F0FC 09004292 */  lbu        $v0, 0x9($s2)
    /* 2F900 8003F100 00000000 */  nop
    /* 2F904 8003F104 13004010 */  beqz       $v0, .L8003F154
    /* 2F908 8003F108 21800000 */   addu      $s0, $zero, $zero
    /* 2F90C 8003F10C 0F80133C */  lui        $s3, %hi(D_800ED8C8)
    /* 2F910 8003F110 21884002 */  addu       $s1, $s2, $zero
  .L8003F114:
    /* 2F914 8003F114 08004292 */  lbu        $v0, 0x8($s2)
    /* 2F918 8003F118 00000000 */  nop
    /* 2F91C 8003F11C 2A100202 */  slt        $v0, $s0, $v0
    /* 2F920 8003F120 0C004010 */  beqz       $v0, .L8003F154
    /* 2F924 8003F124 00000000 */   nop
    /* 2F928 8003F128 C000228E */  lw         $v0, 0xC0($s1)
    /* 2F92C 8003F12C 04003126 */  addiu      $s1, $s1, 0x4
    /* 2F930 8003F130 C8D8658E */  lw         $a1, %lo(D_800ED8C8)($s3)
    /* 2F934 8003F134 4000448C */  lw         $a0, 0x40($v0)
    /* 2F938 8003F138 A6FD000C */  jal        func_8003F698
    /* 2F93C 8003F13C 21308002 */   addu      $a2, $s4, $zero
    /* 2F940 8003F140 09004292 */  lbu        $v0, 0x9($s2)
    /* 2F944 8003F144 01001026 */  addiu      $s0, $s0, 0x1
    /* 2F948 8003F148 2A100202 */  slt        $v0, $s0, $v0
    /* 2F94C 8003F14C F1FF4014 */  bnez       $v0, .L8003F114
    /* 2F950 8003F150 00000000 */   nop
  .L8003F154:
    /* 2F954 8003F154 2400BF8F */  lw         $ra, 0x24($sp)
    /* 2F958 8003F158 2000B48F */  lw         $s4, 0x20($sp)
    /* 2F95C 8003F15C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2F960 8003F160 1800B28F */  lw         $s2, 0x18($sp)
    /* 2F964 8003F164 1400B18F */  lw         $s1, 0x14($sp)
    /* 2F968 8003F168 1000B08F */  lw         $s0, 0x10($sp)
    /* 2F96C 8003F16C 0800E003 */  jr         $ra
    /* 2F970 8003F170 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel func_8003F07C

/* Handwritten function */
nonmatching func_8003F174, 0xF0

glabel func_8003F174
    /* 2F974 8003F174 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 2F978 8003F178 4000B2AF */  sw         $s2, 0x40($sp)
    /* 2F97C 8003F17C 21908000 */  addu       $s2, $a0, $zero
    /* 2F980 8003F180 4C00BFAF */  sw         $ra, 0x4C($sp)
    /* 2F984 8003F184 4800B4AF */  sw         $s4, 0x48($sp)
    /* 2F988 8003F188 4400B3AF */  sw         $s3, 0x44($sp)
    /* 2F98C 8003F18C 3C00B1AF */  sw         $s1, 0x3C($sp)
    /* 2F990 8003F190 3800B0AF */  sw         $s0, 0x38($sp)
    /* 2F994 8003F194 08004292 */  lbu        $v0, 0x8($s2)
    /* 2F998 8003F198 00000000 */  nop
    /* 2F99C 8003F19C 29004010 */  beqz       $v0, .L8003F244
    /* 2F9A0 8003F1A0 21A0A000 */   addu      $s4, $a1, $zero
    /* 2F9A4 8003F1A4 09004292 */  lbu        $v0, 0x9($s2)
    /* 2F9A8 8003F1A8 00000000 */  nop
    /* 2F9AC 8003F1AC 25004010 */  beqz       $v0, .L8003F244
    /* 2F9B0 8003F1B0 21800000 */   addu      $s0, $zero, $zero
    /* 2F9B4 8003F1B4 0F80133C */  lui        $s3, %hi(D_800ED8C8)
    /* 2F9B8 8003F1B8 21884002 */  addu       $s1, $s2, $zero
  .L8003F1BC:
    /* 2F9BC 8003F1BC 08004292 */  lbu        $v0, 0x8($s2)
    /* 2F9C0 8003F1C0 00000000 */  nop
    /* 2F9C4 8003F1C4 2A100202 */  slt        $v0, $s0, $v0
    /* 2F9C8 8003F1C8 1E004010 */  beqz       $v0, .L8003F244
    /* 2F9CC 8003F1CC 00000000 */   nop
    /* 2F9D0 8003F1D0 C000238E */  lw         $v1, 0xC0($s1)
    /* 2F9D4 8003F1D4 00000000 */  nop
    /* 2F9D8 8003F1D8 18006224 */  addiu      $v0, $v1, 0x18
    /* 2F9DC 8003F1DC 00004C8C */  lw         $t4, 0x0($v0)
    /* 2F9E0 8003F1E0 04004D8C */  lw         $t5, 0x4($v0)
    /* 2F9E4 8003F1E4 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2F9E8 8003F1E8 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2F9EC 8003F1EC 08004C8C */  lw         $t4, 0x8($v0)
    /* 2F9F0 8003F1F0 0C004D8C */  lw         $t5, 0xC($v0)
    /* 2F9F4 8003F1F4 10004E8C */  lw         $t6, 0x10($v0)
    /* 2F9F8 8003F1F8 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2F9FC 8003F1FC 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2FA00 8003F200 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2FA04 8003F204 14004C8C */  lw         $t4, 0x14($v0)
    /* 2FA08 8003F208 18004D8C */  lw         $t5, 0x18($v0)
    /* 2FA0C 8003F20C 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2FA10 8003F210 1C004E8C */  lw         $t6, 0x1C($v0)
    /* 2FA14 8003F214 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2FA18 8003F218 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2FA1C 8003F21C 04003126 */  addiu      $s1, $s1, 0x4
    /* 2FA20 8003F220 4000648C */  lw         $a0, 0x40($v1)
    /* 2FA24 8003F224 C8D8658E */  lw         $a1, %lo(D_800ED8C8)($s3)
    /* 2FA28 8003F228 A6FD000C */  jal        func_8003F698
    /* 2FA2C 8003F22C 21308002 */   addu      $a2, $s4, $zero
    /* 2FA30 8003F230 09004292 */  lbu        $v0, 0x9($s2)
    /* 2FA34 8003F234 01001026 */  addiu      $s0, $s0, 0x1
    /* 2FA38 8003F238 2A100202 */  slt        $v0, $s0, $v0
    /* 2FA3C 8003F23C DFFF4014 */  bnez       $v0, .L8003F1BC
    /* 2FA40 8003F240 00000000 */   nop
  .L8003F244:
    /* 2FA44 8003F244 4C00BF8F */  lw         $ra, 0x4C($sp)
    /* 2FA48 8003F248 4800B48F */  lw         $s4, 0x48($sp)
    /* 2FA4C 8003F24C 4400B38F */  lw         $s3, 0x44($sp)
    /* 2FA50 8003F250 4000B28F */  lw         $s2, 0x40($sp)
    /* 2FA54 8003F254 3C00B18F */  lw         $s1, 0x3C($sp)
    /* 2FA58 8003F258 3800B08F */  lw         $s0, 0x38($sp)
    /* 2FA5C 8003F25C 0800E003 */  jr         $ra
    /* 2FA60 8003F260 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_8003F174

nonmatching func_8003F264, 0x94

glabel func_8003F264
    /* 2FA64 8003F264 0A80023C */  lui        $v0, %hi(D_800A3B0C)
    /* 2FA68 8003F268 0C3B4390 */  lbu        $v1, %lo(D_800A3B0C)($v0)
    /* 2FA6C 8003F26C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2FA70 8003F270 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2FA74 8003F274 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2FA78 8003F278 03006228 */  slti       $v0, $v1, 0x3
    /* 2FA7C 8003F27C 19004010 */  beqz       $v0, .L8003F2E4
    /* 2FA80 8003F280 1000B0AF */   sw        $s0, 0x10($sp)
    /* 2FA84 8003F284 17006010 */  beqz       $v1, .L8003F2E4
    /* 2FA88 8003F288 0C80113C */   lui       $s1, %hi(D_800BF544)
    /* 2FA8C 8003F28C 44F5308E */  lw         $s0, %lo(D_800BF544)($s1)
    /* 2FA90 8003F290 01000524 */  addiu      $a1, $zero, 0x1
    /* 2FA94 8003F294 6C0F020C */  jal        func_80083DB0
    /* 2FA98 8003F298 21200002 */   addu      $a0, $s0, $zero
    /* 2FA9C 8003F29C FF00043C */  lui        $a0, (0xFFFFFF >> 16)
    /* 2FAA0 8003F2A0 FFFF8434 */  ori        $a0, $a0, (0xFFFFFF & 0xFFFF)
    /* 2FAA4 8003F2A4 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2FAA8 8003F2A8 00FF063C */  lui        $a2, (0xFF000000 >> 16)
    /* 2FAAC 8003F2AC C8D8458C */  lw         $a1, %lo(D_800ED8C8)($v0)
    /* 2FAB0 8003F2B0 0000038E */  lw         $v1, 0x0($s0)
    /* 2FAB4 8003F2B4 FC1FA28C */  lw         $v0, 0x1FFC($a1)
    /* 2FAB8 8003F2B8 24186600 */  and        $v1, $v1, $a2
    /* 2FABC 8003F2BC 24104400 */  and        $v0, $v0, $a0
    /* 2FAC0 8003F2C0 25186200 */  or         $v1, $v1, $v0
    /* 2FAC4 8003F2C4 24200402 */  and        $a0, $s0, $a0
    /* 2FAC8 8003F2C8 000003AE */  sw         $v1, 0x0($s0)
    /* 2FACC 8003F2CC FC1FA28C */  lw         $v0, 0x1FFC($a1)
    /* 2FAD0 8003F2D0 0C001026 */  addiu      $s0, $s0, 0xC
    /* 2FAD4 8003F2D4 44F530AE */  sw         $s0, %lo(D_800BF544)($s1)
    /* 2FAD8 8003F2D8 24104600 */  and        $v0, $v0, $a2
    /* 2FADC 8003F2DC 25104400 */  or         $v0, $v0, $a0
    /* 2FAE0 8003F2E0 FC1FA2AC */  sw         $v0, 0x1FFC($a1)
  .L8003F2E4:
    /* 2FAE4 8003F2E4 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2FAE8 8003F2E8 1400B18F */  lw         $s1, 0x14($sp)
    /* 2FAEC 8003F2EC 1000B08F */  lw         $s0, 0x10($sp)
    /* 2FAF0 8003F2F0 0800E003 */  jr         $ra
    /* 2FAF4 8003F2F4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_8003F264

nonmatching func_8003F2F8, 0x24

glabel func_8003F2F8
    /* 2FAF8 8003F2F8 FF008430 */  andi       $a0, $a0, 0xFF
    /* 2FAFC 8003F2FC 81FF8424 */  addiu      $a0, $a0, -0x7F
    /* 2FB00 8003F300 FF00A530 */  andi       $a1, $a1, 0xFF
    /* 2FB04 8003F304 2128A400 */  addu       $a1, $a1, $a0
    /* 2FB08 8003F308 0200A104 */  bgez       $a1, .L8003F314
    /* 2FB0C 8003F30C 2110A000 */   addu      $v0, $a1, $zero
    /* 2FB10 8003F310 21100000 */  addu       $v0, $zero, $zero
  .L8003F314:
    /* 2FB14 8003F314 0800E003 */  jr         $ra
    /* 2FB18 8003F318 FF004230 */   andi      $v0, $v0, 0xFF
endlabel func_8003F2F8

nonmatching func_8003F31C, 0x28

glabel func_8003F31C
    /* 2FB1C 8003F31C FF008430 */  andi       $a0, $a0, 0xFF
    /* 2FB20 8003F320 FF00A530 */  andi       $a1, $a1, 0xFF
    /* 2FB24 8003F324 21208500 */  addu       $a0, $a0, $a1
    /* 2FB28 8003F328 21108000 */  addu       $v0, $a0, $zero
    /* 2FB2C 8003F32C 00018428 */  slti       $a0, $a0, 0x100
    /* 2FB30 8003F330 02008014 */  bnez       $a0, .L8003F33C
    /* 2FB34 8003F334 00000000 */   nop
    /* 2FB38 8003F338 FF000224 */  addiu      $v0, $zero, 0xFF
  .L8003F33C:
    /* 2FB3C 8003F33C 0800E003 */  jr         $ra
    /* 2FB40 8003F340 FF004230 */   andi      $v0, $v0, 0xFF
endlabel func_8003F31C

nonmatching func_8003F344, 0xB0

glabel func_8003F344
    /* 2FB44 8003F344 2B10A600 */  sltu       $v0, $a1, $a2
    /* 2FB48 8003F348 28004010 */  beqz       $v0, .L8003F3EC
    /* 2FB4C 8003F34C 0180023C */   lui       $v0, %hi(jtbl_80015088)
    /* 2FB50 8003F350 88504724 */  addiu      $a3, $v0, %lo(jtbl_80015088)
  .L8003F354:
    /* 2FB54 8003F354 0700A290 */  lbu        $v0, 0x7($a1)
    /* 2FB58 8003F358 00000000 */  nop
    /* 2FB5C 8003F35C FC004230 */  andi       $v0, $v0, 0xFC
    /* 2FB60 8003F360 E0FF4324 */  addiu      $v1, $v0, -0x20
    /* 2FB64 8003F364 1D00622C */  sltiu      $v0, $v1, 0x1D
    /* 2FB68 8003F368 1E004010 */  beqz       $v0, .L8003F3E4
    /* 2FB6C 8003F36C 2B10A600 */   sltu      $v0, $a1, $a2
    /* 2FB70 8003F370 80100300 */  sll        $v0, $v1, 2
    /* 2FB74 8003F374 21104700 */  addu       $v0, $v0, $a3
    /* 2FB78 8003F378 0000428C */  lw         $v0, 0x0($v0)
    /* 2FB7C 8003F37C 00000000 */  nop
    /* 2FB80 8003F380 08004000 */  jr         $v0
    /* 2FB84 8003F384 00000000 */   nop
    /* 2FB88 8003F388 5C008294 */  lhu        $v0, 0x5C($a0)
    /* 2FB8C 8003F38C 00000000 */  nop
    /* 2FB90 8003F390 0E00A2A4 */  sh         $v0, 0xE($a1)
    /* 2FB94 8003F394 F8FC0008 */  j          .L8003F3E0
    /* 2FB98 8003F398 3400A524 */   addiu     $a1, $a1, 0x34
    /* 2FB9C 8003F39C 5C008294 */  lhu        $v0, 0x5C($a0)
    /* 2FBA0 8003F3A0 00000000 */  nop
    /* 2FBA4 8003F3A4 0E00A2A4 */  sh         $v0, 0xE($a1)
    /* 2FBA8 8003F3A8 F8FC0008 */  j          .L8003F3E0
    /* 2FBAC 8003F3AC 2000A524 */   addiu     $a1, $a1, 0x20
    /* 2FBB0 8003F3B0 5C008294 */  lhu        $v0, 0x5C($a0)
    /* 2FBB4 8003F3B4 00000000 */  nop
    /* 2FBB8 8003F3B8 0E00A2A4 */  sh         $v0, 0xE($a1)
    /* 2FBBC 8003F3BC F8FC0008 */  j          .L8003F3E0
    /* 2FBC0 8003F3C0 2800A524 */   addiu     $a1, $a1, 0x28
    /* 2FBC4 8003F3C4 F8FC0008 */  j          .L8003F3E0
    /* 2FBC8 8003F3C8 1C00A524 */   addiu     $a1, $a1, 0x1C
    /* 2FBCC 8003F3CC F8FC0008 */  j          .L8003F3E0
    /* 2FBD0 8003F3D0 2400A524 */   addiu     $a1, $a1, 0x24
    /* 2FBD4 8003F3D4 F8FC0008 */  j          .L8003F3E0
    /* 2FBD8 8003F3D8 1400A524 */   addiu     $a1, $a1, 0x14
    /* 2FBDC 8003F3DC 1800A524 */  addiu      $a1, $a1, 0x18
  .L8003F3E0:
    /* 2FBE0 8003F3E0 2B10A600 */  sltu       $v0, $a1, $a2
  .L8003F3E4:
    /* 2FBE4 8003F3E4 DBFF4014 */  bnez       $v0, .L8003F354
    /* 2FBE8 8003F3E8 00000000 */   nop
  .L8003F3EC:
    /* 2FBEC 8003F3EC 0800E003 */  jr         $ra
    /* 2FBF0 8003F3F0 00000000 */   nop
endlabel func_8003F344

nonmatching func_8003F3F4, 0xD0

glabel func_8003F3F4
    /* 2FBF4 8003F3F4 2B10A600 */  sltu       $v0, $a1, $a2
    /* 2FBF8 8003F3F8 30004010 */  beqz       $v0, .L8003F4BC
    /* 2FBFC 8003F3FC 0180023C */   lui       $v0, %hi(jtbl_80015100)
    /* 2FC00 8003F400 00514724 */  addiu      $a3, $v0, %lo(jtbl_80015100)
    /* 2FC04 8003F404 0700A324 */  addiu      $v1, $a1, 0x7
  .L8003F408:
    /* 2FC08 8003F408 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FC0C 8003F40C 00000000 */  nop
    /* 2FC10 8003F410 FC004230 */  andi       $v0, $v0, 0xFC
    /* 2FC14 8003F414 E0FF4424 */  addiu      $a0, $v0, -0x20
    /* 2FC18 8003F418 1D00822C */  sltiu      $v0, $a0, 0x1D
    /* 2FC1C 8003F41C 25004010 */  beqz       $v0, .L8003F4B4
    /* 2FC20 8003F420 2B10A600 */   sltu      $v0, $a1, $a2
    /* 2FC24 8003F424 80100400 */  sll        $v0, $a0, 2
    /* 2FC28 8003F428 21104700 */  addu       $v0, $v0, $a3
    /* 2FC2C 8003F42C 0000428C */  lw         $v0, 0x0($v0)
    /* 2FC30 8003F430 00000000 */  nop
    /* 2FC34 8003F434 08004000 */  jr         $v0
    /* 2FC38 8003F438 00000000 */   nop
    /* 2FC3C 8003F43C 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FC40 8003F440 3400A524 */  addiu      $a1, $a1, 0x34
    /* 2FC44 8003F444 02004234 */  ori        $v0, $v0, 0x2
    /* 2FC48 8003F448 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FC4C 8003F44C 2CFD0008 */  j          .L8003F4B0
    /* 2FC50 8003F450 34006324 */   addiu     $v1, $v1, 0x34
    /* 2FC54 8003F454 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FC58 8003F458 2000A524 */  addiu      $a1, $a1, 0x20
    /* 2FC5C 8003F45C 02004234 */  ori        $v0, $v0, 0x2
    /* 2FC60 8003F460 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FC64 8003F464 2CFD0008 */  j          .L8003F4B0
    /* 2FC68 8003F468 20006324 */   addiu     $v1, $v1, 0x20
    /* 2FC6C 8003F46C 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FC70 8003F470 2800A524 */  addiu      $a1, $a1, 0x28
    /* 2FC74 8003F474 02004234 */  ori        $v0, $v0, 0x2
    /* 2FC78 8003F478 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FC7C 8003F47C 2CFD0008 */  j          .L8003F4B0
    /* 2FC80 8003F480 28006324 */   addiu     $v1, $v1, 0x28
    /* 2FC84 8003F484 1C006324 */  addiu      $v1, $v1, 0x1C
    /* 2FC88 8003F488 2CFD0008 */  j          .L8003F4B0
    /* 2FC8C 8003F48C 1C00A524 */   addiu     $a1, $a1, 0x1C
    /* 2FC90 8003F490 24006324 */  addiu      $v1, $v1, 0x24
    /* 2FC94 8003F494 2CFD0008 */  j          .L8003F4B0
    /* 2FC98 8003F498 2400A524 */   addiu     $a1, $a1, 0x24
    /* 2FC9C 8003F49C 14006324 */  addiu      $v1, $v1, 0x14
    /* 2FCA0 8003F4A0 2CFD0008 */  j          .L8003F4B0
    /* 2FCA4 8003F4A4 1400A524 */   addiu     $a1, $a1, 0x14
    /* 2FCA8 8003F4A8 18006324 */  addiu      $v1, $v1, 0x18
    /* 2FCAC 8003F4AC 1800A524 */  addiu      $a1, $a1, 0x18
  .L8003F4B0:
    /* 2FCB0 8003F4B0 2B10A600 */  sltu       $v0, $a1, $a2
  .L8003F4B4:
    /* 2FCB4 8003F4B4 D4FF4014 */  bnez       $v0, .L8003F408
    /* 2FCB8 8003F4B8 00000000 */   nop
  .L8003F4BC:
    /* 2FCBC 8003F4BC 0800E003 */  jr         $ra
    /* 2FCC0 8003F4C0 00000000 */   nop
endlabel func_8003F3F4

nonmatching func_8003F4C4, 0xD0

glabel func_8003F4C4
    /* 2FCC4 8003F4C4 2B10A600 */  sltu       $v0, $a1, $a2
    /* 2FCC8 8003F4C8 30004010 */  beqz       $v0, .L8003F58C
    /* 2FCCC 8003F4CC 0180023C */   lui       $v0, %hi(jtbl_80015178)
    /* 2FCD0 8003F4D0 78514724 */  addiu      $a3, $v0, %lo(jtbl_80015178)
    /* 2FCD4 8003F4D4 0700A324 */  addiu      $v1, $a1, 0x7
  .L8003F4D8:
    /* 2FCD8 8003F4D8 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FCDC 8003F4DC 00000000 */  nop
    /* 2FCE0 8003F4E0 FC004230 */  andi       $v0, $v0, 0xFC
    /* 2FCE4 8003F4E4 E0FF4424 */  addiu      $a0, $v0, -0x20
    /* 2FCE8 8003F4E8 1D00822C */  sltiu      $v0, $a0, 0x1D
    /* 2FCEC 8003F4EC 25004010 */  beqz       $v0, .L8003F584
    /* 2FCF0 8003F4F0 2B10A600 */   sltu      $v0, $a1, $a2
    /* 2FCF4 8003F4F4 80100400 */  sll        $v0, $a0, 2
    /* 2FCF8 8003F4F8 21104700 */  addu       $v0, $v0, $a3
    /* 2FCFC 8003F4FC 0000428C */  lw         $v0, 0x0($v0)
    /* 2FD00 8003F500 00000000 */  nop
    /* 2FD04 8003F504 08004000 */  jr         $v0
    /* 2FD08 8003F508 00000000 */   nop
    /* 2FD0C 8003F50C 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FD10 8003F510 3400A524 */  addiu      $a1, $a1, 0x34
    /* 2FD14 8003F514 FD004230 */  andi       $v0, $v0, 0xFD
    /* 2FD18 8003F518 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FD1C 8003F51C 60FD0008 */  j          .L8003F580
    /* 2FD20 8003F520 34006324 */   addiu     $v1, $v1, 0x34
    /* 2FD24 8003F524 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FD28 8003F528 2000A524 */  addiu      $a1, $a1, 0x20
    /* 2FD2C 8003F52C FD004230 */  andi       $v0, $v0, 0xFD
    /* 2FD30 8003F530 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FD34 8003F534 60FD0008 */  j          .L8003F580
    /* 2FD38 8003F538 20006324 */   addiu     $v1, $v1, 0x20
    /* 2FD3C 8003F53C 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FD40 8003F540 2800A524 */  addiu      $a1, $a1, 0x28
    /* 2FD44 8003F544 FD004230 */  andi       $v0, $v0, 0xFD
    /* 2FD48 8003F548 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FD4C 8003F54C 60FD0008 */  j          .L8003F580
    /* 2FD50 8003F550 28006324 */   addiu     $v1, $v1, 0x28
    /* 2FD54 8003F554 1C006324 */  addiu      $v1, $v1, 0x1C
    /* 2FD58 8003F558 60FD0008 */  j          .L8003F580
    /* 2FD5C 8003F55C 1C00A524 */   addiu     $a1, $a1, 0x1C
    /* 2FD60 8003F560 24006324 */  addiu      $v1, $v1, 0x24
    /* 2FD64 8003F564 60FD0008 */  j          .L8003F580
    /* 2FD68 8003F568 2400A524 */   addiu     $a1, $a1, 0x24
    /* 2FD6C 8003F56C 14006324 */  addiu      $v1, $v1, 0x14
    /* 2FD70 8003F570 60FD0008 */  j          .L8003F580
    /* 2FD74 8003F574 1400A524 */   addiu     $a1, $a1, 0x14
    /* 2FD78 8003F578 18006324 */  addiu      $v1, $v1, 0x18
    /* 2FD7C 8003F57C 1800A524 */  addiu      $a1, $a1, 0x18
  .L8003F580:
    /* 2FD80 8003F580 2B10A600 */  sltu       $v0, $a1, $a2
  .L8003F584:
    /* 2FD84 8003F584 D4FF4014 */  bnez       $v0, .L8003F4D8
    /* 2FD88 8003F588 00000000 */   nop
  .L8003F58C:
    /* 2FD8C 8003F58C 0800E003 */  jr         $ra
    /* 2FD90 8003F590 00000000 */   nop
endlabel func_8003F4C4

nonmatching func_8003F594, 0x104

glabel func_8003F594
    /* 2FD94 8003F594 1800878C */  lw         $a3, 0x18($a0)
    /* 2FD98 8003F598 2B10A600 */  sltu       $v0, $a1, $a2
    /* 2FD9C 8003F59C 3C004010 */  beqz       $v0, .L8003F690
    /* 2FDA0 8003F5A0 0180023C */   lui       $v0, %hi(jtbl_800151F0)
    /* 2FDA4 8003F5A4 F0514824 */  addiu      $t0, $v0, %lo(jtbl_800151F0)
    /* 2FDA8 8003F5A8 0700A324 */  addiu      $v1, $a1, 0x7
  .L8003F5AC:
    /* 2FDAC 8003F5AC 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FDB0 8003F5B0 00000000 */  nop
    /* 2FDB4 8003F5B4 FC004230 */  andi       $v0, $v0, 0xFC
    /* 2FDB8 8003F5B8 E0FF4424 */  addiu      $a0, $v0, -0x20
    /* 2FDBC 8003F5BC 1D00822C */  sltiu      $v0, $a0, 0x1D
    /* 2FDC0 8003F5C0 31004010 */  beqz       $v0, .L8003F688
    /* 2FDC4 8003F5C4 2B10A600 */   sltu      $v0, $a1, $a2
    /* 2FDC8 8003F5C8 80100400 */  sll        $v0, $a0, 2
    /* 2FDCC 8003F5CC 21104800 */  addu       $v0, $v0, $t0
    /* 2FDD0 8003F5D0 0000428C */  lw         $v0, 0x0($v0)
    /* 2FDD4 8003F5D4 00000000 */  nop
    /* 2FDD8 8003F5D8 08004000 */  jr         $v0
    /* 2FDDC 8003F5DC 00000000 */   nop
    /* 2FDE0 8003F5E0 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FDE4 8003F5E4 2800A524 */  addiu      $a1, $a1, 0x28
    /* 2FDE8 8003F5E8 FDFF67AC */  sw         $a3, -0x3($v1)
    /* 2FDEC 8003F5EC 090067AC */  sw         $a3, 0x9($v1)
    /* 2FDF0 8003F5F0 92FD0008 */  j          .L8003F648
    /* 2FDF4 8003F5F4 150067AC */   sw        $a3, 0x15($v1)
    /* 2FDF8 8003F5F8 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FDFC 8003F5FC 3400A524 */  addiu      $a1, $a1, 0x34
    /* 2FE00 8003F600 FDFF67AC */  sw         $a3, -0x3($v1)
    /* 2FE04 8003F604 090067AC */  sw         $a3, 0x9($v1)
    /* 2FE08 8003F608 150067AC */  sw         $a3, 0x15($v1)
    /* 2FE0C 8003F60C 210067AC */  sw         $a3, 0x21($v1)
    /* 2FE10 8003F610 02004234 */  ori        $v0, $v0, 0x2
    /* 2FE14 8003F614 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FE18 8003F618 A1FD0008 */  j          .L8003F684
    /* 2FE1C 8003F61C 34006324 */   addiu     $v1, $v1, 0x34
    /* 2FE20 8003F620 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FE24 8003F624 2000A524 */  addiu      $a1, $a1, 0x20
    /* 2FE28 8003F628 FDFF67AC */  sw         $a3, -0x3($v1)
    /* 2FE2C 8003F62C 02004234 */  ori        $v0, $v0, 0x2
    /* 2FE30 8003F630 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FE34 8003F634 A1FD0008 */  j          .L8003F684
    /* 2FE38 8003F638 20006324 */   addiu     $v1, $v1, 0x20
    /* 2FE3C 8003F63C 00006290 */  lbu        $v0, 0x0($v1)
    /* 2FE40 8003F640 2800A524 */  addiu      $a1, $a1, 0x28
    /* 2FE44 8003F644 FDFF67AC */  sw         $a3, -0x3($v1)
  .L8003F648:
    /* 2FE48 8003F648 02004234 */  ori        $v0, $v0, 0x2
    /* 2FE4C 8003F64C 000062A0 */  sb         $v0, 0x0($v1)
    /* 2FE50 8003F650 A1FD0008 */  j          .L8003F684
    /* 2FE54 8003F654 28006324 */   addiu     $v1, $v1, 0x28
    /* 2FE58 8003F658 1C006324 */  addiu      $v1, $v1, 0x1C
    /* 2FE5C 8003F65C A1FD0008 */  j          .L8003F684
    /* 2FE60 8003F660 1C00A524 */   addiu     $a1, $a1, 0x1C
    /* 2FE64 8003F664 24006324 */  addiu      $v1, $v1, 0x24
    /* 2FE68 8003F668 A1FD0008 */  j          .L8003F684
    /* 2FE6C 8003F66C 2400A524 */   addiu     $a1, $a1, 0x24
    /* 2FE70 8003F670 14006324 */  addiu      $v1, $v1, 0x14
    /* 2FE74 8003F674 A1FD0008 */  j          .L8003F684
    /* 2FE78 8003F678 1400A524 */   addiu     $a1, $a1, 0x14
    /* 2FE7C 8003F67C 18006324 */  addiu      $v1, $v1, 0x18
    /* 2FE80 8003F680 1800A524 */  addiu      $a1, $a1, 0x18
  .L8003F684:
    /* 2FE84 8003F684 2B10A600 */  sltu       $v0, $a1, $a2
  .L8003F688:
    /* 2FE88 8003F688 C8FF4014 */  bnez       $v0, .L8003F5AC
    /* 2FE8C 8003F68C 00000000 */   nop
  .L8003F690:
    /* 2FE90 8003F690 0800E003 */  jr         $ra
    /* 2FE94 8003F694 00000000 */   nop
endlabel func_8003F594

nonmatching func_8003F698, 0x108

glabel func_8003F698
    /* 2FE98 8003F698 801F023C */  lui        $v0, (0x1F800234 >> 16)
    /* 2FE9C 8003F69C 34024290 */  lbu        $v0, (0x1F800234 & 0xFFFF)($v0)
    /* 2FEA0 8003F6A0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2FEA4 8003F6A4 38004014 */  bnez       $v0, .L8003F788
    /* 2FEA8 8003F6A8 1000BFAF */   sw        $ra, 0x10($sp)
    /* 2FEAC 8003F6AC 0100C230 */  andi       $v0, $a2, 0x1
    /* 2FEB0 8003F6B0 35004014 */  bnez       $v0, .L8003F788
    /* 2FEB4 8003F6B4 0C80023C */   lui       $v0, %hi(D_800BF870)
    /* 2FEB8 8003F6B8 70F84390 */  lbu        $v1, %lo(D_800BF870)($v0)
    /* 2FEBC 8003F6BC 00000000 */  nop
    /* 2FEC0 8003F6C0 1600622C */  sltiu      $v0, $v1, 0x16
    /* 2FEC4 8003F6C4 30004010 */  beqz       $v0, .L8003F788
    /* 2FEC8 8003F6C8 0180023C */   lui       $v0, %hi(jtbl_80015268)
    /* 2FECC 8003F6CC 68524224 */  addiu      $v0, $v0, %lo(jtbl_80015268)
    /* 2FED0 8003F6D0 80180300 */  sll        $v1, $v1, 2
    /* 2FED4 8003F6D4 21186200 */  addu       $v1, $v1, $v0
    /* 2FED8 8003F6D8 0000628C */  lw         $v0, 0x0($v1)
    /* 2FEDC 8003F6DC 00000000 */  nop
    /* 2FEE0 8003F6E0 08004000 */  jr         $v0
    /* 2FEE4 8003F6E4 00000000 */   nop
    /* 2FEE8 8003F6E8 1E19050C */  jal        func_80146478
    /* 2FEEC 8003F6EC 00000000 */   nop
    /* 2FEF0 8003F6F0 E4FD0008 */  j          .L8003F790
    /* 2FEF4 8003F6F4 00000000 */   nop
    /* 2FEF8 8003F6F8 70CB040C */  jal        func_80132DC0
    /* 2FEFC 8003F6FC 00000000 */   nop
    /* 2FF00 8003F700 E4FD0008 */  j          .L8003F790
    /* 2FF04 8003F704 00000000 */   nop
    /* 2FF08 8003F708 5795040C */  jal        func_8012555C
    /* 2FF0C 8003F70C 00000000 */   nop
    /* 2FF10 8003F710 E4FD0008 */  j          .L8003F790
    /* 2FF14 8003F714 00000000 */   nop
    /* 2FF18 8003F718 BFF6040C */  jal        func_8013DAFC
    /* 2FF1C 8003F71C 00000000 */   nop
    /* 2FF20 8003F720 E4FD0008 */  j          .L8003F790
    /* 2FF24 8003F724 00000000 */   nop
    /* 2FF28 8003F728 B3D8040C */  jal        func_801362CC
    /* 2FF2C 8003F72C 00000000 */   nop
    /* 2FF30 8003F730 E4FD0008 */  j          .L8003F790
    /* 2FF34 8003F734 00000000 */   nop
    /* 2FF38 8003F738 5AF5040C */  jal        func_8013D568
    /* 2FF3C 8003F73C 00000000 */   nop
    /* 2FF40 8003F740 E4FD0008 */  j          .L8003F790
    /* 2FF44 8003F744 00000000 */   nop
    /* 2FF48 8003F748 68B8040C */  jal        func_8012E1A0
    /* 2FF4C 8003F74C 00000000 */   nop
    /* 2FF50 8003F750 E4FD0008 */  j          .L8003F790
    /* 2FF54 8003F754 00000000 */   nop
    /* 2FF58 8003F758 77AA040C */  jal        func_8012A9DC
    /* 2FF5C 8003F75C 00000000 */   nop
    /* 2FF60 8003F760 E4FD0008 */  j          .L8003F790
    /* 2FF64 8003F764 00000000 */   nop
    /* 2FF68 8003F768 C55A040C */  jal        func_80116B14
    /* 2FF6C 8003F76C 00000000 */   nop
    /* 2FF70 8003F770 E4FD0008 */  j          .L8003F790
    /* 2FF74 8003F774 00000000 */   nop
    /* 2FF78 8003F778 6E2C040C */  jal        func_8010B1B8
    /* 2FF7C 8003F77C 00000000 */   nop
    /* 2FF80 8003F780 E4FD0008 */  j          .L8003F790
    /* 2FF84 8003F784 00000000 */   nop
  .L8003F788:
    /* 2FF88 8003F788 F700020C */  jal        func_800803DC
    /* 2FF8C 8003F78C 00000000 */   nop
  .L8003F790:
    /* 2FF90 8003F790 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2FF94 8003F794 00000000 */  nop
    /* 2FF98 8003F798 0800E003 */  jr         $ra
    /* 2FF9C 8003F79C 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel func_8003F698

/* Handwritten function */
nonmatching func_8003F7A0, 0x38

glabel func_8003F7A0
    /* 2FFA0 8003F7A0 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 2FFA4 8003F7A4 000080C8 */  lwc2       $0, 0x0($a0)
    /* 2FFA8 8003F7A8 040081C8 */  lwc2       $1, 0x4($a0)
    /* 2FFAC 8003F7AC 00000000 */  nop
    /* 2FFB0 8003F7B0 00000000 */  nop
    /* 2FFB4 8003F7B4 0100184A */  rtps
    /* 2FFB8 8003F7B8 0000AEE8 */  swc2       $14, 0x0($a1)
    /* 2FFBC 8003F7BC 00980C48 */  mfc2       $t4, $19 /* handwritten instruction */
    /* 2FFC0 8003F7C0 00000000 */  nop
    /* 2FFC4 8003F7C4 83600C00 */  sra        $t4, $t4, 2
    /* 2FFC8 8003F7C8 0000ACAF */  sw         $t4, 0x0($sp)
    /* 2FFCC 8003F7CC 0000A28F */  lw         $v0, 0x0($sp)
    /* 2FFD0 8003F7D0 0800E003 */  jr         $ra
    /* 2FFD4 8003F7D4 0800BD27 */   addiu     $sp, $sp, 0x8
endlabel func_8003F7A0

/* Handwritten function */
nonmatching func_8003F7D8, 0xC0

glabel func_8003F7D8
    /* 2FFD8 8003F7D8 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 2FFDC 8003F7DC 0000A0C8 */  lwc2       $0, 0x0($a1)
    /* 2FFE0 8003F7E0 0400A1C8 */  lwc2       $1, 0x4($a1)
    /* 2FFE4 8003F7E4 0800A2C8 */  lwc2       $2, 0x8($a1)
    /* 2FFE8 8003F7E8 0C00A3C8 */  lwc2       $3, 0xC($a1)
    /* 2FFEC 8003F7EC 1000A4C8 */  lwc2       $4, 0x10($a1)
    /* 2FFF0 8003F7F0 1400A5C8 */  lwc2       $5, 0x14($a1)
    /* 2FFF4 8003F7F4 00000000 */  nop
    /* 2FFF8 8003F7F8 00000000 */  nop
    /* 2FFFC 8003F7FC 3000284A */  rtpt
    /* 30000 8003F800 00F84C48 */  cfc2       $t4, $31 /* handwritten instruction */
    /* 30004 8003F804 00000000 */  nop
    /* 30008 8003F808 0000CCAC */  sw         $t4, 0x0($a2)
    /* 3000C 8003F80C 0000C28C */  lw         $v0, 0x0($a2)
    /* 30010 8003F810 00000000 */  nop
    /* 30014 8003F814 1E004004 */  bltz       $v0, .L8003F890
    /* 30018 8003F818 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 3001C 8003F81C 08008CE8 */  swc2       $12, 0x8($a0)
    /* 30020 8003F820 10008DE8 */  swc2       $13, 0x10($a0)
    /* 30024 8003F824 18008EE8 */  swc2       $14, 0x18($a0)
    /* 30028 8003F828 00000000 */  nop
    /* 3002C 8003F82C 00000000 */  nop
    /* 30030 8003F830 0600404B */  nclip
    /* 30034 8003F834 0000D8E8 */  swc2       $24, 0x0($a2)
    /* 30038 8003F838 1800A224 */  addiu      $v0, $a1, 0x18
    /* 3003C 8003F83C 000040C8 */  lwc2       $0, 0x0($v0)
    /* 30040 8003F840 040041C8 */  lwc2       $1, 0x4($v0)
    /* 30044 8003F844 00000000 */  nop
    /* 30048 8003F848 00000000 */  nop
    /* 3004C 8003F84C 0100184A */  rtps
    /* 30050 8003F850 00F84C48 */  cfc2       $t4, $31 /* handwritten instruction */
    /* 30054 8003F854 00000000 */  nop
    /* 30058 8003F858 0000CCAC */  sw         $t4, 0x0($a2)
    /* 3005C 8003F85C 0000C28C */  lw         $v0, 0x0($a2)
    /* 30060 8003F860 00000000 */  nop
    /* 30064 8003F864 09004004 */  bltz       $v0, .L8003F88C
    /* 30068 8003F868 20008224 */   addiu     $v0, $a0, 0x20
    /* 3006C 8003F86C 00004EE8 */  swc2       $14, 0x0($v0)
    /* 30070 8003F870 00000000 */  nop
    /* 30074 8003F874 00000000 */  nop
    /* 30078 8003F878 2E00684B */  avsz4
    /* 3007C 8003F87C 0000A7EB */  swc2       $7, 0x0($sp)
    /* 30080 8003F880 0000A28F */  lw         $v0, 0x0($sp)
    /* 30084 8003F884 24FE0008 */  j          .L8003F890
    /* 30088 8003F888 00000000 */   nop
  .L8003F88C:
    /* 3008C 8003F88C FFFF0224 */  addiu      $v0, $zero, -0x1
  .L8003F890:
    /* 30090 8003F890 0800E003 */  jr         $ra
    /* 30094 8003F894 0800BD27 */   addiu     $sp, $sp, 0x8
endlabel func_8003F7D8

nonmatching func_8003F898, 0x110

glabel func_8003F898
    /* 30098 8003F898 98FFBD27 */  addiu      $sp, $sp, -0x68
    /* 3009C 8003F89C 5C00B1AF */  sw         $s1, 0x5C($sp)
    /* 300A0 8003F8A0 21888000 */  addu       $s1, $a0, $zero
    /* 300A4 8003F8A4 6000BFAF */  sw         $ra, 0x60($sp)
    /* 300A8 8003F8A8 5800B0AF */  sw         $s0, 0x58($sp)
    /* 300AC 8003F8AC 3800228E */  lw         $v0, 0x38($s1)
    /* 300B0 8003F8B0 00000000 */  nop
    /* 300B4 8003F8B4 37004010 */  beqz       $v0, .L8003F994
    /* 300B8 8003F8B8 1000A427 */   addiu     $a0, $sp, 0x10
    /* 300BC 8003F8BC 00004284 */  lh         $v0, 0x0($v0)
    /* 300C0 8003F8C0 3C00238E */  lw         $v1, 0x3C($s1)
    /* 300C4 8003F8C4 3C00258E */  lw         $a1, 0x3C($s1)
    /* 300C8 8003F8C8 80100200 */  sll        $v0, $v0, 2
    /* 300CC 8003F8CC 21186200 */  addu       $v1, $v1, $v0
    /* 300D0 8003F8D0 02006284 */  lh         $v0, 0x2($v1)
    /* 300D4 8003F8D4 21300000 */  addu       $a2, $zero, $zero
    /* 300D8 8003F8D8 15EC000C */  jal        func_8003B054
    /* 300DC 8003F8DC 2128A200 */   addu      $a1, $a1, $v0
    /* 300E0 8003F8E0 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 300E4 8003F8E4 1700A2A3 */  sb         $v0, 0x17($sp)
    /* 300E8 8003F8E8 60002296 */  lhu        $v0, 0x60($s1)
    /* 300EC 8003F8EC 00000000 */  nop
    /* 300F0 8003F8F0 3800A2A7 */  sh         $v0, 0x38($sp)
    /* 300F4 8003F8F4 62002296 */  lhu        $v0, 0x62($s1)
    /* 300F8 8003F8F8 00000000 */  nop
    /* 300FC 8003F8FC 3A00A2A7 */  sh         $v0, 0x3A($sp)
    /* 30100 8003F900 64002296 */  lhu        $v0, 0x64($s1)
    /* 30104 8003F904 00000000 */  nop
    /* 30108 8003F908 3C00A2A7 */  sh         $v0, 0x3C($sp)
    /* 3010C 8003F90C 66002296 */  lhu        $v0, 0x66($s1)
    /* 30110 8003F910 00000000 */  nop
    /* 30114 8003F914 4000A2A7 */  sh         $v0, 0x40($sp)
    /* 30118 8003F918 68002296 */  lhu        $v0, 0x68($s1)
    /* 3011C 8003F91C 00000000 */  nop
    /* 30120 8003F920 4200A2A7 */  sh         $v0, 0x42($sp)
    /* 30124 8003F924 6A002296 */  lhu        $v0, 0x6A($s1)
    /* 30128 8003F928 00000000 */  nop
    /* 3012C 8003F92C 4400A2A7 */  sh         $v0, 0x44($sp)
    /* 30130 8003F930 6C002296 */  lhu        $v0, 0x6C($s1)
    /* 30134 8003F934 00000000 */  nop
    /* 30138 8003F938 4800A2A7 */  sh         $v0, 0x48($sp)
    /* 3013C 8003F93C 6E002296 */  lhu        $v0, 0x6E($s1)
    /* 30140 8003F940 00000000 */  nop
    /* 30144 8003F944 4A00A2A7 */  sh         $v0, 0x4A($sp)
    /* 30148 8003F948 70002296 */  lhu        $v0, 0x70($s1)
    /* 3014C 8003F94C 00000000 */  nop
    /* 30150 8003F950 4C00A2A7 */  sh         $v0, 0x4C($sp)
    /* 30154 8003F954 72002296 */  lhu        $v0, 0x72($s1)
    /* 30158 8003F958 801F103C */  lui        $s0, %hi(D_1F8000F8)
    /* 3015C 8003F95C 5000A2A7 */  sh         $v0, 0x50($sp)
    /* 30160 8003F960 74002296 */  lhu        $v0, 0x74($s1)
    /* 30164 8003F964 F8001026 */  addiu      $s0, $s0, %lo(D_1F8000F8)
    /* 30168 8003F968 5200A2A7 */  sh         $v0, 0x52($sp)
    /* 3016C 8003F96C 76002296 */  lhu        $v0, 0x76($s1)
    /* 30170 8003F970 21200002 */  addu       $a0, $s0, $zero
    /* 30174 8003F974 9811020C */  jal        func_80084660
    /* 30178 8003F978 5400A2A7 */   sh        $v0, 0x54($sp)
    /* 3017C 8003F97C A411020C */  jal        func_80084690
    /* 30180 8003F980 21200002 */   addu      $a0, $s0, $zero
    /* 30184 8003F984 1000A427 */  addiu      $a0, $sp, 0x10
    /* 30188 8003F988 3800A527 */  addiu      $a1, $sp, 0x38
    /* 3018C 8003F98C C8EC000C */  jal        func_8003B320
    /* 30190 8003F990 10000624 */   addiu     $a2, $zero, 0x10
  .L8003F994:
    /* 30194 8003F994 6000BF8F */  lw         $ra, 0x60($sp)
    /* 30198 8003F998 5C00B18F */  lw         $s1, 0x5C($sp)
    /* 3019C 8003F99C 5800B08F */  lw         $s0, 0x58($sp)
    /* 301A0 8003F9A0 0800E003 */  jr         $ra
    /* 301A4 8003F9A4 6800BD27 */   addiu     $sp, $sp, 0x68
endlabel func_8003F898
