.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching GPU_Render3DSprite, 0x348

glabel GPU_Render3DSprite
    /* 2DA3C 8003D23C D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2DA40 8003D240 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2DA44 8003D244 21908000 */  addu       $s2, $a0, $zero
    /* 2DA48 8003D248 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2DA4C 8003D24C 801F133C */  lui        $s3, (0x1F800020 >> 16)
    /* 2DA50 8003D250 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2DA54 8003D254 801F113C */  lui        $s1, %hi(D_1F800000)
    /* 2DA58 8003D258 00003126 */  addiu      $s1, $s1, %lo(D_1F800000)
    /* 2DA5C 8003D25C 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2DA60 8003D260 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2DA64 8003D264 0C004296 */  lhu        $v0, 0xC($s2)
    /* 2DA68 8003D268 21202002 */  addu       $a0, $s1, $zero
    /* 2DA6C 8003D26C 80280200 */  sll        $a1, $v0, 2
    /* 2DA70 8003D270 2128A200 */  addu       $a1, $a1, $v0
    /* 2DA74 8003D274 002C0500 */  sll        $a1, $a1, 16
    /* 2DA78 8003D278 032C0500 */  sra        $a1, $a1, 16
    /* 2DA7C 8003D27C 2130A000 */  addu       $a2, $a1, $zero
    /* 2DA80 8003D280 EF45010C */  jal        func_800517BC
    /* 2DA84 8003D284 2138A000 */   addu      $a3, $a1, $zero
    /* 2DA88 8003D288 801F103C */  lui        $s0, %hi(D_1F800020)
    /* 2DA8C 8003D28C 20001026 */  addiu      $s0, $s0, %lo(D_1F800020)
    /* 2DA90 8003D290 E545010C */  jal        func_80051794
    /* 2DA94 8003D294 21200002 */   addu      $a0, $s0, $zero
    /* 2DA98 8003D298 28004426 */  addiu      $a0, $s2, 0x28
    /* 2DA9C 8003D29C FC11020C */  jal        func_800847F0
    /* 2DAA0 8003D2A0 21280002 */   addu      $a1, $s0, $zero
    /* 2DAA4 8003D2A4 21200002 */  addu       $a0, $s0, $zero
    /* 2DAA8 8003D2A8 21282002 */  addu       $a1, $s1, $zero
    /* 2DAAC 8003D2AC 801F103C */  lui        $s0, %hi(D_1F800040)
    /* 2DAB0 8003D2B0 40001026 */  addiu      $s0, $s0, %lo(D_1F800040)
    /* 2DAB4 8003D2B4 4410020C */  jal        func_80084110
    /* 2DAB8 8003D2B8 21300002 */   addu      $a2, $s0, $zero
    /* 2DABC 8003D2BC 801F023C */  lui        $v0, (0x1F8000C0 >> 16)
    /* 2DAC0 8003D2C0 20007336 */  ori        $s3, $s3, (0x1F800020 & 0xFFFF)
    /* 2DAC4 8003D2C4 801F113C */  lui        $s1, (0x1F80001C >> 16)
    /* 2DAC8 8003D2C8 1E004396 */  lhu        $v1, 0x1E($s2)
    /* 2DACC 8003D2CC 801F083C */  lui        $t0, %hi(D_1F8000F8)
    /* 2DAD0 8003D2D0 C00043A4 */  sh         $v1, (0x1F8000C0 & 0xFFFF)($v0)
    /* 2DAD4 8003D2D4 22004396 */  lhu        $v1, 0x22($s2)
    /* 2DAD8 8003D2D8 C0004224 */  addiu      $v0, $v0, %lo(D_1F8000C0)
    /* 2DADC 8003D2DC 020043A4 */  sh         $v1, 0x2($v0)
    /* 2DAE0 8003D2E0 26004396 */  lhu        $v1, 0x26($s2)
    /* 2DAE4 8003D2E4 F8000825 */  addiu      $t0, $t0, %lo(D_1F8000F8)
    /* 2DAE8 8003D2E8 040043A4 */  sh         $v1, 0x4($v0)
    /* 2DAEC 8003D2EC 00000C8D */  lw         $t4, 0x0($t0)
    /* 2DAF0 8003D2F0 04000D8D */  lw         $t5, 0x4($t0)
    /* 2DAF4 8003D2F4 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2DAF8 8003D2F8 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2DAFC 8003D2FC 08000C8D */  lw         $t4, 0x8($t0)
    /* 2DB00 8003D300 0C000D8D */  lw         $t5, 0xC($t0)
    /* 2DB04 8003D304 10000E8D */  lw         $t6, 0x10($t0)
    /* 2DB08 8003D308 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2DB0C 8003D30C 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2DB10 8003D310 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2DB14 8003D314 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2DB18 8003D318 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2DB1C 8003D31C 00000000 */  nop
    /* 2DB20 8003D320 00000000 */  nop
    /* 2DB24 8003D324 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 2DB28 8003D328 801F083C */  lui        $t0, %hi(D_1F800054)
    /* 2DB2C 8003D32C 54000825 */  addiu      $t0, $t0, %lo(D_1F800054)
    /* 2DB30 8003D330 000019E9 */  swc2       $25, 0x0($t0)
    /* 2DB34 8003D334 04001AE9 */  swc2       $26, 0x4($t0) /* handwritten instruction */
    /* 2DB38 8003D338 08001BE9 */  swc2       $27, 0x8($t0) /* handwritten instruction */
    /* 2DB3C 8003D33C 801F043C */  lui        $a0, %hi(D_1F8000D0)
    /* 2DB40 8003D340 D0008424 */  addiu      $a0, $a0, %lo(D_1F8000D0)
    /* 2DB44 8003D344 1400028E */  lw         $v0, 0x14($s0)
    /* 2DB48 8003D348 3C00838C */  lw         $v1, 0x3C($a0)
    /* 2DB4C 8003D34C 00000000 */  nop
    /* 2DB50 8003D350 21104300 */  addu       $v0, $v0, $v1
    /* 2DB54 8003D354 140002AE */  sw         $v0, 0x14($s0)
    /* 2DB58 8003D358 1800028E */  lw         $v0, 0x18($s0)
    /* 2DB5C 8003D35C 4000858C */  lw         $a1, 0x40($a0)
    /* 2DB60 8003D360 1C00038E */  lw         $v1, 0x1C($s0)
    /* 2DB64 8003D364 4400848C */  lw         $a0, 0x44($a0)
    /* 2DB68 8003D368 21104500 */  addu       $v0, $v0, $a1
    /* 2DB6C 8003D36C 21186400 */  addu       $v1, $v1, $a0
    /* 2DB70 8003D370 180002AE */  sw         $v0, 0x18($s0)
    /* 2DB74 8003D374 1C0003AE */  sw         $v1, 0x1C($s0)
    /* 2DB78 8003D378 00000C8E */  lw         $t4, 0x0($s0)
    /* 2DB7C 8003D37C 04000D8E */  lw         $t5, 0x4($s0)
    /* 2DB80 8003D380 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 2DB84 8003D384 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 2DB88 8003D388 08000C8E */  lw         $t4, 0x8($s0)
    /* 2DB8C 8003D38C 0C000D8E */  lw         $t5, 0xC($s0)
    /* 2DB90 8003D390 10000E8E */  lw         $t6, 0x10($s0)
    /* 2DB94 8003D394 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 2DB98 8003D398 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 2DB9C 8003D39C 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 2DBA0 8003D3A0 14000C8E */  lw         $t4, 0x14($s0)
    /* 2DBA4 8003D3A4 18000D8E */  lw         $t5, 0x18($s0)
    /* 2DBA8 8003D3A8 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 2DBAC 8003D3AC 1C000E8E */  lw         $t6, 0x1C($s0)
    /* 2DBB0 8003D3B0 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 2DBB4 8003D3B4 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 2DBB8 8003D3B8 07004392 */  lbu        $v1, 0x7($s2)
    /* 2DBBC 8003D3BC 00000000 */  nop
    /* 2DBC0 8003D3C0 40100300 */  sll        $v0, $v1, 1
    /* 2DBC4 8003D3C4 21104300 */  addu       $v0, $v0, $v1
    /* 2DBC8 8003D3C8 C0100200 */  sll        $v0, $v0, 3
    /* 2DBCC 8003D3CC 0A80033C */  lui        $v1, %hi(D_8009D46C)
    /* 2DBD0 8003D3D0 6CD46324 */  addiu      $v1, $v1, %lo(D_8009D46C)
    /* 2DBD4 8003D3D4 21104300 */  addu       $v0, $v0, $v1
    /* 2DBD8 8003D3D8 000040C8 */  lwc2       $0, 0x0($v0)
    /* 2DBDC 8003D3DC 040041C8 */  lwc2       $1, 0x4($v0)
    /* 2DBE0 8003D3E0 080042C8 */  lwc2       $2, 0x8($v0)
    /* 2DBE4 8003D3E4 0C0043C8 */  lwc2       $3, 0xC($v0)
    /* 2DBE8 8003D3E8 100044C8 */  lwc2       $4, 0x10($v0)
    /* 2DBEC 8003D3EC 140045C8 */  lwc2       $5, 0x14($v0)
    /* 2DBF0 8003D3F0 00000000 */  nop
    /* 2DBF4 8003D3F4 00000000 */  nop
    /* 2DBF8 8003D3F8 3000284A */  rtpt
    /* 2DBFC 8003D3FC 08002CEA */  swc2       $12, (0x1F800008 & 0xFFFF)($s1)
    /* 2DC00 8003D400 10002DEA */  swc2       $13, (0x1F800010 & 0xFFFF)($s1)
    /* 2DC04 8003D404 18002EEA */  swc2       $14, (0x1F800018 & 0xFFFF)($s1)
    /* 2DC08 8003D408 00000000 */  nop
    /* 2DC0C 8003D40C 00000000 */  nop
    /* 2DC10 8003D410 2D00584B */  avsz3
    /* 2DC14 8003D414 000067EA */  swc2       $7, 0x0($s3)
    /* 2DC18 8003D418 0000628E */  lw         $v0, 0x0($s3)
    /* 2DC1C 8003D41C 00000000 */  nop
    /* 2DC20 8003D420 831A0200 */  sra        $v1, $v0, 10
    /* 2DC24 8003D424 07106200 */  srav       $v0, $v0, $v1
    /* 2DC28 8003D428 401A0300 */  sll        $v1, $v1, 9
    /* 2DC2C 8003D42C 21104300 */  addu       $v0, $v0, $v1
    /* 2DC30 8003D430 000062AE */  sw         $v0, 0x0($s3)
    /* 2DC34 8003D434 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* 2DC38 8003D438 FC07422C */  sltiu      $v0, $v0, 0x7FC
    /* 2DC3C 8003D43C 02004014 */  bnez       $v0, .L8003D448
    /* 2DC40 8003D440 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 2DC44 8003D444 000062AE */  sw         $v0, 0x0($s3)
  .L8003D448:
    /* 2DC48 8003D448 0000668E */  lw         $a2, 0x0($s3)
    /* 2DC4C 8003D44C 00000000 */  nop
    /* 2DC50 8003D450 4500C004 */  bltz       $a2, .L8003D568
    /* 2DC54 8003D454 0C80043C */   lui       $a0, %hi(D_800BF544)
    /* 2DC58 8003D458 0E004292 */  lbu        $v0, 0xE($s2)
    /* 2DC5C 8003D45C 44F5858C */  lw         $a1, %lo(D_800BF544)($a0)
    /* 2DC60 8003D460 070022A2 */  sb         $v0, (0x1F800007 & 0xFFFF)($s1)
    /* 2DC64 8003D464 34004292 */  lbu        $v0, 0x34($s2)
    /* 2DC68 8003D468 00000000 */  nop
    /* 2DC6C 8003D46C 0C0022A2 */  sb         $v0, (0x1F80000C & 0xFFFF)($s1)
    /* 2DC70 8003D470 35004292 */  lbu        $v0, 0x35($s2)
    /* 2DC74 8003D474 00000000 */  nop
    /* 2DC78 8003D478 0D0022A2 */  sb         $v0, (0x1F80000D & 0xFFFF)($s1)
    /* 2DC7C 8003D47C 38004292 */  lbu        $v0, 0x38($s2)
    /* 2DC80 8003D480 00000000 */  nop
    /* 2DC84 8003D484 140022A2 */  sb         $v0, (0x1F800014 & 0xFFFF)($s1)
    /* 2DC88 8003D488 39004292 */  lbu        $v0, 0x39($s2)
    /* 2DC8C 8003D48C 00000000 */  nop
    /* 2DC90 8003D490 150022A2 */  sb         $v0, (0x1F800015 & 0xFFFF)($s1)
    /* 2DC94 8003D494 3C004292 */  lbu        $v0, 0x3C($s2)
    /* 2DC98 8003D498 00000000 */  nop
    /* 2DC9C 8003D49C 1C0022A2 */  sb         $v0, (0x1F80001C & 0xFFFF)($s1)
    /* 2DCA0 8003D4A0 3D004292 */  lbu        $v0, 0x3D($s2)
    /* 2DCA4 8003D4A4 00000000 */  nop
    /* 2DCA8 8003D4A8 1D0022A2 */  sb         $v0, (0x1F80001D & 0xFFFF)($s1)
    /* 2DCAC 8003D4AC 3A004296 */  lhu        $v0, 0x3A($s2)
    /* 2DCB0 8003D4B0 00000000 */  nop
    /* 2DCB4 8003D4B4 160022A6 */  sh         $v0, (0x1F800016 & 0xFFFF)($s1)
    /* 2DCB8 8003D4B8 36004296 */  lhu        $v0, 0x36($s2)
    /* 2DCBC 8003D4BC 00000000 */  nop
    /* 2DCC0 8003D4C0 0E0022A6 */  sh         $v0, (0x1F80000E & 0xFFFF)($s1)
    /* 2DCC4 8003D4C4 30004292 */  lbu        $v0, 0x30($s2)
    /* 2DCC8 8003D4C8 00000000 */  nop
    /* 2DCCC 8003D4CC 040022A2 */  sb         $v0, (0x1F800004 & 0xFFFF)($s1)
    /* 2DCD0 8003D4D0 31004292 */  lbu        $v0, 0x31($s2)
    /* 2DCD4 8003D4D4 00000000 */  nop
    /* 2DCD8 8003D4D8 050022A2 */  sb         $v0, (0x1F800005 & 0xFFFF)($s1)
    /* 2DCDC 8003D4DC 32004392 */  lbu        $v1, 0x32($s2)
    /* 2DCE0 8003D4E0 2000A224 */  addiu      $v0, $a1, 0x20
    /* 2DCE4 8003D4E4 44F582AC */  sw         $v0, %lo(D_800BF544)($a0)
    /* 2DCE8 8003D4E8 060023A2 */  sb         $v1, (0x1F800006 & 0xFFFF)($s1)
    /* 2DCEC 8003D4EC 0F80023C */  lui        $v0, %hi(D_800ED8C8)
    /* 2DCF0 8003D4F0 C8D8448C */  lw         $a0, %lo(D_800ED8C8)($v0)
    /* 2DCF4 8003D4F4 80100600 */  sll        $v0, $a2, 2
    /* 2DCF8 8003D4F8 21208200 */  addu       $a0, $a0, $v0
    /* 2DCFC 8003D4FC 0000828C */  lw         $v0, 0x0($a0)
    /* 2DD00 8003D500 0007033C */  lui        $v1, (0x7000000 >> 16)
    /* 2DD04 8003D504 25104300 */  or         $v0, $v0, $v1
    /* 2DD08 8003D508 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD0C 8003D50C 000085AC */  sw         $a1, 0x0($a0)
    /* 2DD10 8003D510 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2DD14 8003D514 0400228E */  lw         $v0, (0x1F800004 & 0xFFFF)($s1)
    /* 2DD18 8003D518 00000000 */  nop
    /* 2DD1C 8003D51C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD20 8003D520 0800228E */  lw         $v0, (0x1F800008 & 0xFFFF)($s1)
    /* 2DD24 8003D524 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2DD28 8003D528 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD2C 8003D52C 0C00228E */  lw         $v0, (0x1F80000C & 0xFFFF)($s1)
    /* 2DD30 8003D530 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2DD34 8003D534 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD38 8003D538 1000228E */  lw         $v0, (0x1F800010 & 0xFFFF)($s1)
    /* 2DD3C 8003D53C 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2DD40 8003D540 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD44 8003D544 1400228E */  lw         $v0, (0x1F800014 & 0xFFFF)($s1)
    /* 2DD48 8003D548 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2DD4C 8003D54C 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD50 8003D550 1800228E */  lw         $v0, (0x1F800018 & 0xFFFF)($s1)
    /* 2DD54 8003D554 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2DD58 8003D558 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2DD5C 8003D55C 1C00228E */  lw         $v0, (0x1F80001C & 0xFFFF)($s1)
    /* 2DD60 8003D560 00000000 */  nop
    /* 2DD64 8003D564 0400A2AC */  sw         $v0, 0x4($a1)
  .L8003D568:
    /* 2DD68 8003D568 2000BF8F */  lw         $ra, 0x20($sp)
    /* 2DD6C 8003D56C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2DD70 8003D570 1800B28F */  lw         $s2, 0x18($sp)
    /* 2DD74 8003D574 1400B18F */  lw         $s1, 0x14($sp)
    /* 2DD78 8003D578 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DD7C 8003D57C 0800E003 */  jr         $ra
    /* 2DD80 8003D580 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel GPU_Render3DSprite

nonmatching GPU_ModulateOTColors, 0x980

glabel GPU_ModulateOTColors
    /* 2DD84 8003D584 2B10A600 */  sltu       $v0, $a1, $a2
    /* 2DD88 8003D588 5C024010 */  beqz       $v0, .L8003DEFC
    /* 2DD8C 8003D58C 0600A724 */   addiu     $a3, $a1, 0x6
  .L8003D590:
    /* 2DD90 8003D590 0100E290 */  lbu        $v0, 0x1($a3)
    /* 2DD94 8003D594 00000000 */  nop
    /* 2DD98 8003D598 FC004230 */  andi       $v0, $v0, 0xFC
    /* 2DD9C 8003D59C E0FF4324 */  addiu      $v1, $v0, -0x20
    /* 2DDA0 8003D5A0 1D00622C */  sltiu      $v0, $v1, 0x1D
    /* 2DDA4 8003D5A4 53024010 */  beqz       $v0, .L8003DEF4
    /* 2DDA8 8003D5A8 2B10A600 */   sltu      $v0, $a1, $a2
    /* 2DDAC 8003D5AC 0180023C */  lui        $v0, %hi(jtbl_80014F48)
    /* 2DDB0 8003D5B0 484F4224 */  addiu      $v0, $v0, %lo(jtbl_80014F48)
    /* 2DDB4 8003D5B4 80180300 */  sll        $v1, $v1, 2
    /* 2DDB8 8003D5B8 21186200 */  addu       $v1, $v1, $v0
    /* 2DDBC 8003D5BC 0000628C */  lw         $v0, 0x0($v1)
    /* 2DDC0 8003D5C0 00000000 */  nop
    /* 2DDC4 8003D5C4 08004000 */  jr         $v0
    /* 2DDC8 8003D5C8 00000000 */   nop
    /* 2DDCC 8003D5CC 18008890 */  lbu        $t0, 0x18($a0)
    /* 2DDD0 8003D5D0 00000000 */  nop
    /* 2DDD4 8003D5D4 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2DDD8 8003D5D8 1F004014 */  bnez       $v0, .L8003D658
    /* 2DDDC 8003D5DC 00160800 */   sll       $v0, $t0, 24
    /* 2DDE0 8003D5E0 FEFFE290 */  lbu        $v0, -0x2($a3)
    /* 2DDE4 8003D5E4 00000000 */  nop
    /* 2DDE8 8003D5E8 21100201 */  addu       $v0, $t0, $v0
    /* 2DDEC 8003D5EC 21184000 */  addu       $v1, $v0, $zero
    /* 2DDF0 8003D5F0 00014228 */  slti       $v0, $v0, 0x100
    /* 2DDF4 8003D5F4 02004014 */  bnez       $v0, .L8003D600
    /* 2DDF8 8003D5F8 00000000 */   nop
    /* 2DDFC 8003D5FC FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D600:
    /* 2DE00 8003D600 0A00E290 */  lbu        $v0, 0xA($a3)
    /* 2DE04 8003D604 FEFFE3A0 */  sb         $v1, -0x2($a3)
    /* 2DE08 8003D608 18008390 */  lbu        $v1, 0x18($a0)
    /* 2DE0C 8003D60C 00000000 */  nop
    /* 2DE10 8003D610 21104300 */  addu       $v0, $v0, $v1
    /* 2DE14 8003D614 21184000 */  addu       $v1, $v0, $zero
    /* 2DE18 8003D618 00014228 */  slti       $v0, $v0, 0x100
    /* 2DE1C 8003D61C 02004014 */  bnez       $v0, .L8003D628
    /* 2DE20 8003D620 00000000 */   nop
    /* 2DE24 8003D624 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D628:
    /* 2DE28 8003D628 1600E290 */  lbu        $v0, 0x16($a3)
    /* 2DE2C 8003D62C 0A00E3A0 */  sb         $v1, 0xA($a3)
    /* 2DE30 8003D630 18008390 */  lbu        $v1, 0x18($a0)
    /* 2DE34 8003D634 00000000 */  nop
    /* 2DE38 8003D638 21104300 */  addu       $v0, $v0, $v1
    /* 2DE3C 8003D63C 21184000 */  addu       $v1, $v0, $zero
    /* 2DE40 8003D640 00014228 */  slti       $v0, $v0, 0x100
    /* 2DE44 8003D644 02004014 */  bnez       $v0, .L8003D650
    /* 2DE48 8003D648 00000000 */   nop
    /* 2DE4C 8003D64C FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D650:
    /* 2DE50 8003D650 B0F50008 */  j          .L8003D6C0
    /* 2DE54 8003D654 1600E3A0 */   sb        $v1, 0x16($a3)
  .L8003D658:
    /* 2DE58 8003D658 19004004 */  bltz       $v0, .L8003D6C0
    /* 2DE5C 8003D65C FF000231 */   andi      $v0, $t0, 0xFF
    /* 2DE60 8003D660 FEFFE390 */  lbu        $v1, -0x2($a3)
    /* 2DE64 8003D664 00000000 */  nop
    /* 2DE68 8003D668 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2DE6C 8003D66C 21104300 */  addu       $v0, $v0, $v1
    /* 2DE70 8003D670 02004104 */  bgez       $v0, .L8003D67C
    /* 2DE74 8003D674 21184000 */   addu      $v1, $v0, $zero
    /* 2DE78 8003D678 21180000 */  addu       $v1, $zero, $zero
  .L8003D67C:
    /* 2DE7C 8003D67C 0A00E290 */  lbu        $v0, 0xA($a3)
    /* 2DE80 8003D680 FEFFE3A0 */  sb         $v1, -0x2($a3)
    /* 2DE84 8003D684 18008390 */  lbu        $v1, 0x18($a0)
    /* 2DE88 8003D688 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2DE8C 8003D68C 21186200 */  addu       $v1, $v1, $v0
    /* 2DE90 8003D690 02006104 */  bgez       $v1, .L8003D69C
    /* 2DE94 8003D694 21106000 */   addu      $v0, $v1, $zero
    /* 2DE98 8003D698 21100000 */  addu       $v0, $zero, $zero
  .L8003D69C:
    /* 2DE9C 8003D69C 0A00E2A0 */  sb         $v0, 0xA($a3)
    /* 2DEA0 8003D6A0 1600E290 */  lbu        $v0, 0x16($a3)
    /* 2DEA4 8003D6A4 18008390 */  lbu        $v1, 0x18($a0)
    /* 2DEA8 8003D6A8 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2DEAC 8003D6AC 21186200 */  addu       $v1, $v1, $v0
    /* 2DEB0 8003D6B0 02006104 */  bgez       $v1, .L8003D6BC
    /* 2DEB4 8003D6B4 21106000 */   addu      $v0, $v1, $zero
    /* 2DEB8 8003D6B8 21100000 */  addu       $v0, $zero, $zero
  .L8003D6BC:
    /* 2DEBC 8003D6BC 1600E2A0 */  sb         $v0, 0x16($a3)
  .L8003D6C0:
    /* 2DEC0 8003D6C0 19008890 */  lbu        $t0, 0x19($a0)
    /* 2DEC4 8003D6C4 00000000 */  nop
    /* 2DEC8 8003D6C8 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2DECC 8003D6CC 1F004014 */  bnez       $v0, .L8003D74C
    /* 2DED0 8003D6D0 00160800 */   sll       $v0, $t0, 24
    /* 2DED4 8003D6D4 FFFFE290 */  lbu        $v0, -0x1($a3)
    /* 2DED8 8003D6D8 00000000 */  nop
    /* 2DEDC 8003D6DC 21100201 */  addu       $v0, $t0, $v0
    /* 2DEE0 8003D6E0 21184000 */  addu       $v1, $v0, $zero
    /* 2DEE4 8003D6E4 00014228 */  slti       $v0, $v0, 0x100
    /* 2DEE8 8003D6E8 02004014 */  bnez       $v0, .L8003D6F4
    /* 2DEEC 8003D6EC 00000000 */   nop
    /* 2DEF0 8003D6F0 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D6F4:
    /* 2DEF4 8003D6F4 0B00E290 */  lbu        $v0, 0xB($a3)
    /* 2DEF8 8003D6F8 FFFFE3A0 */  sb         $v1, -0x1($a3)
    /* 2DEFC 8003D6FC 19008390 */  lbu        $v1, 0x19($a0)
    /* 2DF00 8003D700 00000000 */  nop
    /* 2DF04 8003D704 21104300 */  addu       $v0, $v0, $v1
    /* 2DF08 8003D708 21184000 */  addu       $v1, $v0, $zero
    /* 2DF0C 8003D70C 00014228 */  slti       $v0, $v0, 0x100
    /* 2DF10 8003D710 02004014 */  bnez       $v0, .L8003D71C
    /* 2DF14 8003D714 00000000 */   nop
    /* 2DF18 8003D718 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D71C:
    /* 2DF1C 8003D71C 1700E290 */  lbu        $v0, 0x17($a3)
    /* 2DF20 8003D720 0B00E3A0 */  sb         $v1, 0xB($a3)
    /* 2DF24 8003D724 19008390 */  lbu        $v1, 0x19($a0)
    /* 2DF28 8003D728 00000000 */  nop
    /* 2DF2C 8003D72C 21104300 */  addu       $v0, $v0, $v1
    /* 2DF30 8003D730 21184000 */  addu       $v1, $v0, $zero
    /* 2DF34 8003D734 00014228 */  slti       $v0, $v0, 0x100
    /* 2DF38 8003D738 02004014 */  bnez       $v0, .L8003D744
    /* 2DF3C 8003D73C 00000000 */   nop
    /* 2DF40 8003D740 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D744:
    /* 2DF44 8003D744 EDF50008 */  j          .L8003D7B4
    /* 2DF48 8003D748 1700E3A0 */   sb        $v1, 0x17($a3)
  .L8003D74C:
    /* 2DF4C 8003D74C 19004004 */  bltz       $v0, .L8003D7B4
    /* 2DF50 8003D750 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2DF54 8003D754 FFFFE390 */  lbu        $v1, -0x1($a3)
    /* 2DF58 8003D758 00000000 */  nop
    /* 2DF5C 8003D75C 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2DF60 8003D760 21104300 */  addu       $v0, $v0, $v1
    /* 2DF64 8003D764 02004104 */  bgez       $v0, .L8003D770
    /* 2DF68 8003D768 21184000 */   addu      $v1, $v0, $zero
    /* 2DF6C 8003D76C 21180000 */  addu       $v1, $zero, $zero
  .L8003D770:
    /* 2DF70 8003D770 0B00E290 */  lbu        $v0, 0xB($a3)
    /* 2DF74 8003D774 FFFFE3A0 */  sb         $v1, -0x1($a3)
    /* 2DF78 8003D778 19008390 */  lbu        $v1, 0x19($a0)
    /* 2DF7C 8003D77C 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2DF80 8003D780 21186200 */  addu       $v1, $v1, $v0
    /* 2DF84 8003D784 02006104 */  bgez       $v1, .L8003D790
    /* 2DF88 8003D788 21106000 */   addu      $v0, $v1, $zero
    /* 2DF8C 8003D78C 21100000 */  addu       $v0, $zero, $zero
  .L8003D790:
    /* 2DF90 8003D790 0B00E2A0 */  sb         $v0, 0xB($a3)
    /* 2DF94 8003D794 1700E290 */  lbu        $v0, 0x17($a3)
    /* 2DF98 8003D798 19008390 */  lbu        $v1, 0x19($a0)
    /* 2DF9C 8003D79C 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2DFA0 8003D7A0 21186200 */  addu       $v1, $v1, $v0
    /* 2DFA4 8003D7A4 02006104 */  bgez       $v1, .L8003D7B0
    /* 2DFA8 8003D7A8 21106000 */   addu      $v0, $v1, $zero
    /* 2DFAC 8003D7AC 21100000 */  addu       $v0, $zero, $zero
  .L8003D7B0:
    /* 2DFB0 8003D7B0 1700E2A0 */  sb         $v0, 0x17($a3)
  .L8003D7B4:
    /* 2DFB4 8003D7B4 1A008890 */  lbu        $t0, 0x1A($a0)
    /* 2DFB8 8003D7B8 00000000 */  nop
    /* 2DFBC 8003D7BC 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2DFC0 8003D7C0 1F004014 */  bnez       $v0, .L8003D840
    /* 2DFC4 8003D7C4 00160800 */   sll       $v0, $t0, 24
    /* 2DFC8 8003D7C8 0000E290 */  lbu        $v0, 0x0($a3)
    /* 2DFCC 8003D7CC 00000000 */  nop
    /* 2DFD0 8003D7D0 21100201 */  addu       $v0, $t0, $v0
    /* 2DFD4 8003D7D4 21184000 */  addu       $v1, $v0, $zero
    /* 2DFD8 8003D7D8 00014228 */  slti       $v0, $v0, 0x100
    /* 2DFDC 8003D7DC 02004014 */  bnez       $v0, .L8003D7E8
    /* 2DFE0 8003D7E0 00000000 */   nop
    /* 2DFE4 8003D7E4 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D7E8:
    /* 2DFE8 8003D7E8 0C00E290 */  lbu        $v0, 0xC($a3)
    /* 2DFEC 8003D7EC 0000E3A0 */  sb         $v1, 0x0($a3)
    /* 2DFF0 8003D7F0 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2DFF4 8003D7F4 00000000 */  nop
    /* 2DFF8 8003D7F8 21104300 */  addu       $v0, $v0, $v1
    /* 2DFFC 8003D7FC 21184000 */  addu       $v1, $v0, $zero
    /* 2E000 8003D800 00014228 */  slti       $v0, $v0, 0x100
    /* 2E004 8003D804 02004014 */  bnez       $v0, .L8003D810
    /* 2E008 8003D808 00000000 */   nop
    /* 2E00C 8003D80C FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D810:
    /* 2E010 8003D810 1800E290 */  lbu        $v0, 0x18($a3)
    /* 2E014 8003D814 0C00E3A0 */  sb         $v1, 0xC($a3)
    /* 2E018 8003D818 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E01C 8003D81C 00000000 */  nop
    /* 2E020 8003D820 21104300 */  addu       $v0, $v0, $v1
    /* 2E024 8003D824 21184000 */  addu       $v1, $v0, $zero
    /* 2E028 8003D828 00014228 */  slti       $v0, $v0, 0x100
    /* 2E02C 8003D82C 02004014 */  bnez       $v0, .L8003D838
    /* 2E030 8003D830 00000000 */   nop
    /* 2E034 8003D834 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D838:
    /* 2E038 8003D838 AEF70008 */  j          .L8003DEB8
    /* 2E03C 8003D83C 1800E3A0 */   sb        $v1, 0x18($a3)
  .L8003D840:
    /* 2E040 8003D840 9D014004 */  bltz       $v0, .L8003DEB8
    /* 2E044 8003D844 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E048 8003D848 0000E390 */  lbu        $v1, 0x0($a3)
    /* 2E04C 8003D84C 00000000 */  nop
    /* 2E050 8003D850 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E054 8003D854 21104300 */  addu       $v0, $v0, $v1
    /* 2E058 8003D858 02004104 */  bgez       $v0, .L8003D864
    /* 2E05C 8003D85C 21184000 */   addu      $v1, $v0, $zero
    /* 2E060 8003D860 21180000 */  addu       $v1, $zero, $zero
  .L8003D864:
    /* 2E064 8003D864 0C00E290 */  lbu        $v0, 0xC($a3)
    /* 2E068 8003D868 0000E3A0 */  sb         $v1, 0x0($a3)
    /* 2E06C 8003D86C 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E070 8003D870 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E074 8003D874 21186200 */  addu       $v1, $v1, $v0
    /* 2E078 8003D878 02006104 */  bgez       $v1, .L8003D884
    /* 2E07C 8003D87C 21106000 */   addu      $v0, $v1, $zero
    /* 2E080 8003D880 21100000 */  addu       $v0, $zero, $zero
  .L8003D884:
    /* 2E084 8003D884 0C00E2A0 */  sb         $v0, 0xC($a3)
    /* 2E088 8003D888 1800E290 */  lbu        $v0, 0x18($a3)
    /* 2E08C 8003D88C 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E090 8003D890 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E094 8003D894 21186200 */  addu       $v1, $v1, $v0
    /* 2E098 8003D898 02006104 */  bgez       $v1, .L8003D8A4
    /* 2E09C 8003D89C 21106000 */   addu      $v0, $v1, $zero
    /* 2E0A0 8003D8A0 21100000 */  addu       $v0, $zero, $zero
  .L8003D8A4:
    /* 2E0A4 8003D8A4 AEF70008 */  j          .L8003DEB8
    /* 2E0A8 8003D8A8 1800E2A0 */   sb        $v0, 0x18($a3)
    /* 2E0AC 8003D8AC 18008890 */  lbu        $t0, 0x18($a0)
    /* 2E0B0 8003D8B0 00000000 */  nop
    /* 2E0B4 8003D8B4 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E0B8 8003D8B8 29004014 */  bnez       $v0, .L8003D960
    /* 2E0BC 8003D8BC 00160800 */   sll       $v0, $t0, 24
    /* 2E0C0 8003D8C0 FEFFE290 */  lbu        $v0, -0x2($a3)
    /* 2E0C4 8003D8C4 00000000 */  nop
    /* 2E0C8 8003D8C8 21100201 */  addu       $v0, $t0, $v0
    /* 2E0CC 8003D8CC 21184000 */  addu       $v1, $v0, $zero
    /* 2E0D0 8003D8D0 00014228 */  slti       $v0, $v0, 0x100
    /* 2E0D4 8003D8D4 02004014 */  bnez       $v0, .L8003D8E0
    /* 2E0D8 8003D8D8 00000000 */   nop
    /* 2E0DC 8003D8DC FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D8E0:
    /* 2E0E0 8003D8E0 0A00E290 */  lbu        $v0, 0xA($a3)
    /* 2E0E4 8003D8E4 FEFFE3A0 */  sb         $v1, -0x2($a3)
    /* 2E0E8 8003D8E8 18008390 */  lbu        $v1, 0x18($a0)
    /* 2E0EC 8003D8EC 00000000 */  nop
    /* 2E0F0 8003D8F0 21104300 */  addu       $v0, $v0, $v1
    /* 2E0F4 8003D8F4 21184000 */  addu       $v1, $v0, $zero
    /* 2E0F8 8003D8F8 00014228 */  slti       $v0, $v0, 0x100
    /* 2E0FC 8003D8FC 02004014 */  bnez       $v0, .L8003D908
    /* 2E100 8003D900 00000000 */   nop
    /* 2E104 8003D904 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D908:
    /* 2E108 8003D908 1600E290 */  lbu        $v0, 0x16($a3)
    /* 2E10C 8003D90C 0A00E3A0 */  sb         $v1, 0xA($a3)
    /* 2E110 8003D910 18008390 */  lbu        $v1, 0x18($a0)
    /* 2E114 8003D914 00000000 */  nop
    /* 2E118 8003D918 21104300 */  addu       $v0, $v0, $v1
    /* 2E11C 8003D91C 21184000 */  addu       $v1, $v0, $zero
    /* 2E120 8003D920 00014228 */  slti       $v0, $v0, 0x100
    /* 2E124 8003D924 02004014 */  bnez       $v0, .L8003D930
    /* 2E128 8003D928 00000000 */   nop
    /* 2E12C 8003D92C FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D930:
    /* 2E130 8003D930 2200E290 */  lbu        $v0, 0x22($a3)
    /* 2E134 8003D934 1600E3A0 */  sb         $v1, 0x16($a3)
    /* 2E138 8003D938 18008390 */  lbu        $v1, 0x18($a0)
    /* 2E13C 8003D93C 00000000 */  nop
    /* 2E140 8003D940 21104300 */  addu       $v0, $v0, $v1
    /* 2E144 8003D944 21184000 */  addu       $v1, $v0, $zero
    /* 2E148 8003D948 00014228 */  slti       $v0, $v0, 0x100
    /* 2E14C 8003D94C 02004014 */  bnez       $v0, .L8003D958
    /* 2E150 8003D950 00000000 */   nop
    /* 2E154 8003D954 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003D958:
    /* 2E158 8003D958 7AF60008 */  j          .L8003D9E8
    /* 2E15C 8003D95C 2200E3A0 */   sb        $v1, 0x22($a3)
  .L8003D960:
    /* 2E160 8003D960 21004004 */  bltz       $v0, .L8003D9E8
    /* 2E164 8003D964 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E168 8003D968 FEFFE390 */  lbu        $v1, -0x2($a3)
    /* 2E16C 8003D96C 00000000 */  nop
    /* 2E170 8003D970 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E174 8003D974 21104300 */  addu       $v0, $v0, $v1
    /* 2E178 8003D978 02004104 */  bgez       $v0, .L8003D984
    /* 2E17C 8003D97C 21184000 */   addu      $v1, $v0, $zero
    /* 2E180 8003D980 21180000 */  addu       $v1, $zero, $zero
  .L8003D984:
    /* 2E184 8003D984 0A00E290 */  lbu        $v0, 0xA($a3)
    /* 2E188 8003D988 FEFFE3A0 */  sb         $v1, -0x2($a3)
    /* 2E18C 8003D98C 18008390 */  lbu        $v1, 0x18($a0)
    /* 2E190 8003D990 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E194 8003D994 21186200 */  addu       $v1, $v1, $v0
    /* 2E198 8003D998 02006104 */  bgez       $v1, .L8003D9A4
    /* 2E19C 8003D99C 21106000 */   addu      $v0, $v1, $zero
    /* 2E1A0 8003D9A0 21100000 */  addu       $v0, $zero, $zero
  .L8003D9A4:
    /* 2E1A4 8003D9A4 0A00E2A0 */  sb         $v0, 0xA($a3)
    /* 2E1A8 8003D9A8 1600E290 */  lbu        $v0, 0x16($a3)
    /* 2E1AC 8003D9AC 18008390 */  lbu        $v1, 0x18($a0)
    /* 2E1B0 8003D9B0 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E1B4 8003D9B4 21186200 */  addu       $v1, $v1, $v0
    /* 2E1B8 8003D9B8 02006104 */  bgez       $v1, .L8003D9C4
    /* 2E1BC 8003D9BC 21106000 */   addu      $v0, $v1, $zero
    /* 2E1C0 8003D9C0 21100000 */  addu       $v0, $zero, $zero
  .L8003D9C4:
    /* 2E1C4 8003D9C4 1600E2A0 */  sb         $v0, 0x16($a3)
    /* 2E1C8 8003D9C8 2200E290 */  lbu        $v0, 0x22($a3)
    /* 2E1CC 8003D9CC 18008390 */  lbu        $v1, 0x18($a0)
    /* 2E1D0 8003D9D0 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E1D4 8003D9D4 21186200 */  addu       $v1, $v1, $v0
    /* 2E1D8 8003D9D8 02006104 */  bgez       $v1, .L8003D9E4
    /* 2E1DC 8003D9DC 21106000 */   addu      $v0, $v1, $zero
    /* 2E1E0 8003D9E0 21100000 */  addu       $v0, $zero, $zero
  .L8003D9E4:
    /* 2E1E4 8003D9E4 2200E2A0 */  sb         $v0, 0x22($a3)
  .L8003D9E8:
    /* 2E1E8 8003D9E8 19008890 */  lbu        $t0, 0x19($a0)
    /* 2E1EC 8003D9EC 00000000 */  nop
    /* 2E1F0 8003D9F0 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E1F4 8003D9F4 29004014 */  bnez       $v0, .L8003DA9C
    /* 2E1F8 8003D9F8 00160800 */   sll       $v0, $t0, 24
    /* 2E1FC 8003D9FC FFFFE290 */  lbu        $v0, -0x1($a3)
    /* 2E200 8003DA00 00000000 */  nop
    /* 2E204 8003DA04 21100201 */  addu       $v0, $t0, $v0
    /* 2E208 8003DA08 21184000 */  addu       $v1, $v0, $zero
    /* 2E20C 8003DA0C 00014228 */  slti       $v0, $v0, 0x100
    /* 2E210 8003DA10 02004014 */  bnez       $v0, .L8003DA1C
    /* 2E214 8003DA14 00000000 */   nop
    /* 2E218 8003DA18 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DA1C:
    /* 2E21C 8003DA1C 0B00E290 */  lbu        $v0, 0xB($a3)
    /* 2E220 8003DA20 FFFFE3A0 */  sb         $v1, -0x1($a3)
    /* 2E224 8003DA24 19008390 */  lbu        $v1, 0x19($a0)
    /* 2E228 8003DA28 00000000 */  nop
    /* 2E22C 8003DA2C 21104300 */  addu       $v0, $v0, $v1
    /* 2E230 8003DA30 21184000 */  addu       $v1, $v0, $zero
    /* 2E234 8003DA34 00014228 */  slti       $v0, $v0, 0x100
    /* 2E238 8003DA38 02004014 */  bnez       $v0, .L8003DA44
    /* 2E23C 8003DA3C 00000000 */   nop
    /* 2E240 8003DA40 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DA44:
    /* 2E244 8003DA44 1700E290 */  lbu        $v0, 0x17($a3)
    /* 2E248 8003DA48 0B00E3A0 */  sb         $v1, 0xB($a3)
    /* 2E24C 8003DA4C 19008390 */  lbu        $v1, 0x19($a0)
    /* 2E250 8003DA50 00000000 */  nop
    /* 2E254 8003DA54 21104300 */  addu       $v0, $v0, $v1
    /* 2E258 8003DA58 21184000 */  addu       $v1, $v0, $zero
    /* 2E25C 8003DA5C 00014228 */  slti       $v0, $v0, 0x100
    /* 2E260 8003DA60 02004014 */  bnez       $v0, .L8003DA6C
    /* 2E264 8003DA64 00000000 */   nop
    /* 2E268 8003DA68 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DA6C:
    /* 2E26C 8003DA6C 2300E290 */  lbu        $v0, 0x23($a3)
    /* 2E270 8003DA70 1700E3A0 */  sb         $v1, 0x17($a3)
    /* 2E274 8003DA74 19008390 */  lbu        $v1, 0x19($a0)
    /* 2E278 8003DA78 00000000 */  nop
    /* 2E27C 8003DA7C 21104300 */  addu       $v0, $v0, $v1
    /* 2E280 8003DA80 21184000 */  addu       $v1, $v0, $zero
    /* 2E284 8003DA84 00014228 */  slti       $v0, $v0, 0x100
    /* 2E288 8003DA88 02004014 */  bnez       $v0, .L8003DA94
    /* 2E28C 8003DA8C 00000000 */   nop
    /* 2E290 8003DA90 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DA94:
    /* 2E294 8003DA94 C9F60008 */  j          .L8003DB24
    /* 2E298 8003DA98 2300E3A0 */   sb        $v1, 0x23($a3)
  .L8003DA9C:
    /* 2E29C 8003DA9C 21004004 */  bltz       $v0, .L8003DB24
    /* 2E2A0 8003DAA0 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E2A4 8003DAA4 FFFFE390 */  lbu        $v1, -0x1($a3)
    /* 2E2A8 8003DAA8 00000000 */  nop
    /* 2E2AC 8003DAAC 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E2B0 8003DAB0 21104300 */  addu       $v0, $v0, $v1
    /* 2E2B4 8003DAB4 02004104 */  bgez       $v0, .L8003DAC0
    /* 2E2B8 8003DAB8 21184000 */   addu      $v1, $v0, $zero
    /* 2E2BC 8003DABC 21180000 */  addu       $v1, $zero, $zero
  .L8003DAC0:
    /* 2E2C0 8003DAC0 0B00E290 */  lbu        $v0, 0xB($a3)
    /* 2E2C4 8003DAC4 FFFFE3A0 */  sb         $v1, -0x1($a3)
    /* 2E2C8 8003DAC8 19008390 */  lbu        $v1, 0x19($a0)
    /* 2E2CC 8003DACC 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E2D0 8003DAD0 21186200 */  addu       $v1, $v1, $v0
    /* 2E2D4 8003DAD4 02006104 */  bgez       $v1, .L8003DAE0
    /* 2E2D8 8003DAD8 21106000 */   addu      $v0, $v1, $zero
    /* 2E2DC 8003DADC 21100000 */  addu       $v0, $zero, $zero
  .L8003DAE0:
    /* 2E2E0 8003DAE0 0B00E2A0 */  sb         $v0, 0xB($a3)
    /* 2E2E4 8003DAE4 1700E290 */  lbu        $v0, 0x17($a3)
    /* 2E2E8 8003DAE8 19008390 */  lbu        $v1, 0x19($a0)
    /* 2E2EC 8003DAEC 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E2F0 8003DAF0 21186200 */  addu       $v1, $v1, $v0
    /* 2E2F4 8003DAF4 02006104 */  bgez       $v1, .L8003DB00
    /* 2E2F8 8003DAF8 21106000 */   addu      $v0, $v1, $zero
    /* 2E2FC 8003DAFC 21100000 */  addu       $v0, $zero, $zero
  .L8003DB00:
    /* 2E300 8003DB00 1700E2A0 */  sb         $v0, 0x17($a3)
    /* 2E304 8003DB04 2300E290 */  lbu        $v0, 0x23($a3)
    /* 2E308 8003DB08 19008390 */  lbu        $v1, 0x19($a0)
    /* 2E30C 8003DB0C 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E310 8003DB10 21186200 */  addu       $v1, $v1, $v0
    /* 2E314 8003DB14 02006104 */  bgez       $v1, .L8003DB20
    /* 2E318 8003DB18 21106000 */   addu      $v0, $v1, $zero
    /* 2E31C 8003DB1C 21100000 */  addu       $v0, $zero, $zero
  .L8003DB20:
    /* 2E320 8003DB20 2300E2A0 */  sb         $v0, 0x23($a3)
  .L8003DB24:
    /* 2E324 8003DB24 1A008890 */  lbu        $t0, 0x1A($a0)
    /* 2E328 8003DB28 00000000 */  nop
    /* 2E32C 8003DB2C 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E330 8003DB30 29004014 */  bnez       $v0, .L8003DBD8
    /* 2E334 8003DB34 00160800 */   sll       $v0, $t0, 24
    /* 2E338 8003DB38 0000E290 */  lbu        $v0, 0x0($a3)
    /* 2E33C 8003DB3C 00000000 */  nop
    /* 2E340 8003DB40 21100201 */  addu       $v0, $t0, $v0
    /* 2E344 8003DB44 21184000 */  addu       $v1, $v0, $zero
    /* 2E348 8003DB48 00014228 */  slti       $v0, $v0, 0x100
    /* 2E34C 8003DB4C 02004014 */  bnez       $v0, .L8003DB58
    /* 2E350 8003DB50 00000000 */   nop
    /* 2E354 8003DB54 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DB58:
    /* 2E358 8003DB58 0C00E290 */  lbu        $v0, 0xC($a3)
    /* 2E35C 8003DB5C 0000E3A0 */  sb         $v1, 0x0($a3)
    /* 2E360 8003DB60 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E364 8003DB64 00000000 */  nop
    /* 2E368 8003DB68 21104300 */  addu       $v0, $v0, $v1
    /* 2E36C 8003DB6C 21184000 */  addu       $v1, $v0, $zero
    /* 2E370 8003DB70 00014228 */  slti       $v0, $v0, 0x100
    /* 2E374 8003DB74 02004014 */  bnez       $v0, .L8003DB80
    /* 2E378 8003DB78 00000000 */   nop
    /* 2E37C 8003DB7C FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DB80:
    /* 2E380 8003DB80 1800E290 */  lbu        $v0, 0x18($a3)
    /* 2E384 8003DB84 0C00E3A0 */  sb         $v1, 0xC($a3)
    /* 2E388 8003DB88 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E38C 8003DB8C 00000000 */  nop
    /* 2E390 8003DB90 21104300 */  addu       $v0, $v0, $v1
    /* 2E394 8003DB94 21184000 */  addu       $v1, $v0, $zero
    /* 2E398 8003DB98 00014228 */  slti       $v0, $v0, 0x100
    /* 2E39C 8003DB9C 02004014 */  bnez       $v0, .L8003DBA8
    /* 2E3A0 8003DBA0 00000000 */   nop
    /* 2E3A4 8003DBA4 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DBA8:
    /* 2E3A8 8003DBA8 2400E290 */  lbu        $v0, 0x24($a3)
    /* 2E3AC 8003DBAC 1800E3A0 */  sb         $v1, 0x18($a3)
    /* 2E3B0 8003DBB0 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E3B4 8003DBB4 00000000 */  nop
    /* 2E3B8 8003DBB8 21104300 */  addu       $v0, $v0, $v1
    /* 2E3BC 8003DBBC 21184000 */  addu       $v1, $v0, $zero
    /* 2E3C0 8003DBC0 00014228 */  slti       $v0, $v0, 0x100
    /* 2E3C4 8003DBC4 02004014 */  bnez       $v0, .L8003DBD0
    /* 2E3C8 8003DBC8 00000000 */   nop
    /* 2E3CC 8003DBCC FF000324 */  addiu      $v1, $zero, 0xFF
  .L8003DBD0:
    /* 2E3D0 8003DBD0 18F70008 */  j          .L8003DC60
    /* 2E3D4 8003DBD4 2400E3A0 */   sb        $v1, 0x24($a3)
  .L8003DBD8:
    /* 2E3D8 8003DBD8 21004004 */  bltz       $v0, .L8003DC60
    /* 2E3DC 8003DBDC FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E3E0 8003DBE0 0000E390 */  lbu        $v1, 0x0($a3)
    /* 2E3E4 8003DBE4 00000000 */  nop
    /* 2E3E8 8003DBE8 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E3EC 8003DBEC 21104300 */  addu       $v0, $v0, $v1
    /* 2E3F0 8003DBF0 02004104 */  bgez       $v0, .L8003DBFC
    /* 2E3F4 8003DBF4 21184000 */   addu      $v1, $v0, $zero
    /* 2E3F8 8003DBF8 21180000 */  addu       $v1, $zero, $zero
  .L8003DBFC:
    /* 2E3FC 8003DBFC 0C00E290 */  lbu        $v0, 0xC($a3)
    /* 2E400 8003DC00 0000E3A0 */  sb         $v1, 0x0($a3)
    /* 2E404 8003DC04 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E408 8003DC08 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E40C 8003DC0C 21186200 */  addu       $v1, $v1, $v0
    /* 2E410 8003DC10 02006104 */  bgez       $v1, .L8003DC1C
    /* 2E414 8003DC14 21106000 */   addu      $v0, $v1, $zero
    /* 2E418 8003DC18 21100000 */  addu       $v0, $zero, $zero
  .L8003DC1C:
    /* 2E41C 8003DC1C 0C00E2A0 */  sb         $v0, 0xC($a3)
    /* 2E420 8003DC20 1800E290 */  lbu        $v0, 0x18($a3)
    /* 2E424 8003DC24 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E428 8003DC28 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E42C 8003DC2C 21186200 */  addu       $v1, $v1, $v0
    /* 2E430 8003DC30 02006104 */  bgez       $v1, .L8003DC3C
    /* 2E434 8003DC34 21106000 */   addu      $v0, $v1, $zero
    /* 2E438 8003DC38 21100000 */  addu       $v0, $zero, $zero
  .L8003DC3C:
    /* 2E43C 8003DC3C 1800E2A0 */  sb         $v0, 0x18($a3)
    /* 2E440 8003DC40 2400E290 */  lbu        $v0, 0x24($a3)
    /* 2E444 8003DC44 1A008390 */  lbu        $v1, 0x1A($a0)
    /* 2E448 8003DC48 81FF4224 */  addiu      $v0, $v0, -0x7F
    /* 2E44C 8003DC4C 21186200 */  addu       $v1, $v1, $v0
    /* 2E450 8003DC50 02006104 */  bgez       $v1, .L8003DC5C
    /* 2E454 8003DC54 21106000 */   addu      $v0, $v1, $zero
    /* 2E458 8003DC58 21100000 */  addu       $v0, $zero, $zero
  .L8003DC5C:
    /* 2E45C 8003DC5C 2400E2A0 */  sb         $v0, 0x24($a3)
  .L8003DC60:
    /* 2E460 8003DC60 3400E724 */  addiu      $a3, $a3, 0x34
    /* 2E464 8003DC64 BCF70008 */  j          .L8003DEF0
    /* 2E468 8003DC68 3400A524 */   addiu     $a1, $a1, 0x34
    /* 2E46C 8003DC6C 18008890 */  lbu        $t0, 0x18($a0)
    /* 2E470 8003DC70 00000000 */  nop
    /* 2E474 8003DC74 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E478 8003DC78 0A004014 */  bnez       $v0, .L8003DCA4
    /* 2E47C 8003DC7C 00160800 */   sll       $v0, $t0, 24
    /* 2E480 8003DC80 FEFFE290 */  lbu        $v0, -0x2($a3)
    /* 2E484 8003DC84 00000000 */  nop
    /* 2E488 8003DC88 21100201 */  addu       $v0, $t0, $v0
    /* 2E48C 8003DC8C 21184000 */  addu       $v1, $v0, $zero
    /* 2E490 8003DC90 00014228 */  slti       $v0, $v0, 0x100
    /* 2E494 8003DC94 0C004014 */  bnez       $v0, .L8003DCC8
    /* 2E498 8003DC98 00000000 */   nop
    /* 2E49C 8003DC9C 32F70008 */  j          .L8003DCC8
    /* 2E4A0 8003DCA0 FF000324 */   addiu     $v1, $zero, 0xFF
  .L8003DCA4:
    /* 2E4A4 8003DCA4 09004004 */  bltz       $v0, .L8003DCCC
    /* 2E4A8 8003DCA8 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E4AC 8003DCAC FEFFE390 */  lbu        $v1, -0x2($a3)
    /* 2E4B0 8003DCB0 00000000 */  nop
    /* 2E4B4 8003DCB4 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E4B8 8003DCB8 21104300 */  addu       $v0, $v0, $v1
    /* 2E4BC 8003DCBC 02004104 */  bgez       $v0, .L8003DCC8
    /* 2E4C0 8003DCC0 21184000 */   addu      $v1, $v0, $zero
    /* 2E4C4 8003DCC4 21180000 */  addu       $v1, $zero, $zero
  .L8003DCC8:
    /* 2E4C8 8003DCC8 FEFFE3A0 */  sb         $v1, -0x2($a3)
  .L8003DCCC:
    /* 2E4CC 8003DCCC 19008890 */  lbu        $t0, 0x19($a0)
    /* 2E4D0 8003DCD0 00000000 */  nop
    /* 2E4D4 8003DCD4 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E4D8 8003DCD8 0A004014 */  bnez       $v0, .L8003DD04
    /* 2E4DC 8003DCDC 00160800 */   sll       $v0, $t0, 24
    /* 2E4E0 8003DCE0 FFFFE290 */  lbu        $v0, -0x1($a3)
    /* 2E4E4 8003DCE4 00000000 */  nop
    /* 2E4E8 8003DCE8 21100201 */  addu       $v0, $t0, $v0
    /* 2E4EC 8003DCEC 21184000 */  addu       $v1, $v0, $zero
    /* 2E4F0 8003DCF0 00014228 */  slti       $v0, $v0, 0x100
    /* 2E4F4 8003DCF4 0C004014 */  bnez       $v0, .L8003DD28
    /* 2E4F8 8003DCF8 00000000 */   nop
    /* 2E4FC 8003DCFC 4AF70008 */  j          .L8003DD28
    /* 2E500 8003DD00 FF000324 */   addiu     $v1, $zero, 0xFF
  .L8003DD04:
    /* 2E504 8003DD04 09004004 */  bltz       $v0, .L8003DD2C
    /* 2E508 8003DD08 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E50C 8003DD0C FFFFE390 */  lbu        $v1, -0x1($a3)
    /* 2E510 8003DD10 00000000 */  nop
    /* 2E514 8003DD14 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E518 8003DD18 21104300 */  addu       $v0, $v0, $v1
    /* 2E51C 8003DD1C 02004104 */  bgez       $v0, .L8003DD28
    /* 2E520 8003DD20 21184000 */   addu      $v1, $v0, $zero
    /* 2E524 8003DD24 21180000 */  addu       $v1, $zero, $zero
  .L8003DD28:
    /* 2E528 8003DD28 FFFFE3A0 */  sb         $v1, -0x1($a3)
  .L8003DD2C:
    /* 2E52C 8003DD2C 1A008890 */  lbu        $t0, 0x1A($a0)
    /* 2E530 8003DD30 00000000 */  nop
    /* 2E534 8003DD34 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E538 8003DD38 0A004014 */  bnez       $v0, .L8003DD64
    /* 2E53C 8003DD3C 00160800 */   sll       $v0, $t0, 24
    /* 2E540 8003DD40 0000E290 */  lbu        $v0, 0x0($a3)
    /* 2E544 8003DD44 00000000 */  nop
    /* 2E548 8003DD48 21100201 */  addu       $v0, $t0, $v0
    /* 2E54C 8003DD4C 21184000 */  addu       $v1, $v0, $zero
    /* 2E550 8003DD50 00014228 */  slti       $v0, $v0, 0x100
    /* 2E554 8003DD54 0C004014 */  bnez       $v0, .L8003DD88
    /* 2E558 8003DD58 00000000 */   nop
    /* 2E55C 8003DD5C 62F70008 */  j          .L8003DD88
    /* 2E560 8003DD60 FF000324 */   addiu     $v1, $zero, 0xFF
  .L8003DD64:
    /* 2E564 8003DD64 09004004 */  bltz       $v0, .L8003DD8C
    /* 2E568 8003DD68 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E56C 8003DD6C 0000E390 */  lbu        $v1, 0x0($a3)
    /* 2E570 8003DD70 00000000 */  nop
    /* 2E574 8003DD74 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E578 8003DD78 21104300 */  addu       $v0, $v0, $v1
    /* 2E57C 8003DD7C 02004104 */  bgez       $v0, .L8003DD88
    /* 2E580 8003DD80 21184000 */   addu      $v1, $v0, $zero
    /* 2E584 8003DD84 21180000 */  addu       $v1, $zero, $zero
  .L8003DD88:
    /* 2E588 8003DD88 0000E3A0 */  sb         $v1, 0x0($a3)
  .L8003DD8C:
    /* 2E58C 8003DD8C 2000E724 */  addiu      $a3, $a3, 0x20
    /* 2E590 8003DD90 BCF70008 */  j          .L8003DEF0
    /* 2E594 8003DD94 2000A524 */   addiu     $a1, $a1, 0x20
    /* 2E598 8003DD98 18008890 */  lbu        $t0, 0x18($a0)
    /* 2E59C 8003DD9C 00000000 */  nop
    /* 2E5A0 8003DDA0 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E5A4 8003DDA4 0A004014 */  bnez       $v0, .L8003DDD0
    /* 2E5A8 8003DDA8 00160800 */   sll       $v0, $t0, 24
    /* 2E5AC 8003DDAC FEFFE290 */  lbu        $v0, -0x2($a3)
    /* 2E5B0 8003DDB0 00000000 */  nop
    /* 2E5B4 8003DDB4 21100201 */  addu       $v0, $t0, $v0
    /* 2E5B8 8003DDB8 21184000 */  addu       $v1, $v0, $zero
    /* 2E5BC 8003DDBC 00014228 */  slti       $v0, $v0, 0x100
    /* 2E5C0 8003DDC0 0C004014 */  bnez       $v0, .L8003DDF4
    /* 2E5C4 8003DDC4 00000000 */   nop
    /* 2E5C8 8003DDC8 7DF70008 */  j          .L8003DDF4
    /* 2E5CC 8003DDCC FF000324 */   addiu     $v1, $zero, 0xFF
  .L8003DDD0:
    /* 2E5D0 8003DDD0 09004004 */  bltz       $v0, .L8003DDF8
    /* 2E5D4 8003DDD4 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E5D8 8003DDD8 FEFFE390 */  lbu        $v1, -0x2($a3)
    /* 2E5DC 8003DDDC 00000000 */  nop
    /* 2E5E0 8003DDE0 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E5E4 8003DDE4 21104300 */  addu       $v0, $v0, $v1
    /* 2E5E8 8003DDE8 02004104 */  bgez       $v0, .L8003DDF4
    /* 2E5EC 8003DDEC 21184000 */   addu      $v1, $v0, $zero
    /* 2E5F0 8003DDF0 21180000 */  addu       $v1, $zero, $zero
  .L8003DDF4:
    /* 2E5F4 8003DDF4 FEFFE3A0 */  sb         $v1, -0x2($a3)
  .L8003DDF8:
    /* 2E5F8 8003DDF8 19008890 */  lbu        $t0, 0x19($a0)
    /* 2E5FC 8003DDFC 00000000 */  nop
    /* 2E600 8003DE00 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E604 8003DE04 0A004014 */  bnez       $v0, .L8003DE30
    /* 2E608 8003DE08 00160800 */   sll       $v0, $t0, 24
    /* 2E60C 8003DE0C FFFFE290 */  lbu        $v0, -0x1($a3)
    /* 2E610 8003DE10 00000000 */  nop
    /* 2E614 8003DE14 21100201 */  addu       $v0, $t0, $v0
    /* 2E618 8003DE18 21184000 */  addu       $v1, $v0, $zero
    /* 2E61C 8003DE1C 00014228 */  slti       $v0, $v0, 0x100
    /* 2E620 8003DE20 0C004014 */  bnez       $v0, .L8003DE54
    /* 2E624 8003DE24 00000000 */   nop
    /* 2E628 8003DE28 95F70008 */  j          .L8003DE54
    /* 2E62C 8003DE2C FF000324 */   addiu     $v1, $zero, 0xFF
  .L8003DE30:
    /* 2E630 8003DE30 09004004 */  bltz       $v0, .L8003DE58
    /* 2E634 8003DE34 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E638 8003DE38 FFFFE390 */  lbu        $v1, -0x1($a3)
    /* 2E63C 8003DE3C 00000000 */  nop
    /* 2E640 8003DE40 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E644 8003DE44 21104300 */  addu       $v0, $v0, $v1
    /* 2E648 8003DE48 02004104 */  bgez       $v0, .L8003DE54
    /* 2E64C 8003DE4C 21184000 */   addu      $v1, $v0, $zero
    /* 2E650 8003DE50 21180000 */  addu       $v1, $zero, $zero
  .L8003DE54:
    /* 2E654 8003DE54 FFFFE3A0 */  sb         $v1, -0x1($a3)
  .L8003DE58:
    /* 2E658 8003DE58 1A008890 */  lbu        $t0, 0x1A($a0)
    /* 2E65C 8003DE5C 00000000 */  nop
    /* 2E660 8003DE60 8100022D */  sltiu      $v0, $t0, 0x81
    /* 2E664 8003DE64 0A004014 */  bnez       $v0, .L8003DE90
    /* 2E668 8003DE68 00160800 */   sll       $v0, $t0, 24
    /* 2E66C 8003DE6C 0000E290 */  lbu        $v0, 0x0($a3)
    /* 2E670 8003DE70 00000000 */  nop
    /* 2E674 8003DE74 21100201 */  addu       $v0, $t0, $v0
    /* 2E678 8003DE78 21184000 */  addu       $v1, $v0, $zero
    /* 2E67C 8003DE7C 00014228 */  slti       $v0, $v0, 0x100
    /* 2E680 8003DE80 0C004014 */  bnez       $v0, .L8003DEB4
    /* 2E684 8003DE84 00000000 */   nop
    /* 2E688 8003DE88 ADF70008 */  j          .L8003DEB4
    /* 2E68C 8003DE8C FF000324 */   addiu     $v1, $zero, 0xFF
  .L8003DE90:
    /* 2E690 8003DE90 09004004 */  bltz       $v0, .L8003DEB8
    /* 2E694 8003DE94 FF000231 */   andi      $v0, $t0, 0xFF
    /* 2E698 8003DE98 0000E390 */  lbu        $v1, 0x0($a3)
    /* 2E69C 8003DE9C 00000000 */  nop
    /* 2E6A0 8003DEA0 81FF6324 */  addiu      $v1, $v1, -0x7F
    /* 2E6A4 8003DEA4 21104300 */  addu       $v0, $v0, $v1
    /* 2E6A8 8003DEA8 02004104 */  bgez       $v0, .L8003DEB4
    /* 2E6AC 8003DEAC 21184000 */   addu      $v1, $v0, $zero
    /* 2E6B0 8003DEB0 21180000 */  addu       $v1, $zero, $zero
  .L8003DEB4:
    /* 2E6B4 8003DEB4 0000E3A0 */  sb         $v1, 0x0($a3)
  .L8003DEB8:
    /* 2E6B8 8003DEB8 2800E724 */  addiu      $a3, $a3, 0x28
    /* 2E6BC 8003DEBC BCF70008 */  j          .L8003DEF0
    /* 2E6C0 8003DEC0 2800A524 */   addiu     $a1, $a1, 0x28
    /* 2E6C4 8003DEC4 1C00E724 */  addiu      $a3, $a3, 0x1C
    /* 2E6C8 8003DEC8 BCF70008 */  j          .L8003DEF0
    /* 2E6CC 8003DECC 1C00A524 */   addiu     $a1, $a1, 0x1C
    /* 2E6D0 8003DED0 2400E724 */  addiu      $a3, $a3, 0x24
    /* 2E6D4 8003DED4 BCF70008 */  j          .L8003DEF0
    /* 2E6D8 8003DED8 2400A524 */   addiu     $a1, $a1, 0x24
    /* 2E6DC 8003DEDC 1400E724 */  addiu      $a3, $a3, 0x14
    /* 2E6E0 8003DEE0 BCF70008 */  j          .L8003DEF0
    /* 2E6E4 8003DEE4 1400A524 */   addiu     $a1, $a1, 0x14
    /* 2E6E8 8003DEE8 1800E724 */  addiu      $a3, $a3, 0x18
    /* 2E6EC 8003DEEC 1800A524 */  addiu      $a1, $a1, 0x18
  .L8003DEF0:
    /* 2E6F0 8003DEF0 2B10A600 */  sltu       $v0, $a1, $a2
  .L8003DEF4:
    /* 2E6F4 8003DEF4 A6FD4014 */  bnez       $v0, .L8003D590
    /* 2E6F8 8003DEF8 00000000 */   nop
  .L8003DEFC:
    /* 2E6FC 8003DEFC 0800E003 */  jr         $ra
    /* 2E700 8003DF00 00000000 */   nop
endlabel GPU_ModulateOTColors
